INSERT INTO Hotel VALUES(1,'Hotel Host','ICICI Bank ATM, Taj Ganj',3.7,1,0);
INSERT INTO Hotel VALUES(2,'Hotel Deluxe Inn','Howard Park Plaza, Fatehabad Road',3.5,1,0);
INSERT INTO Hotel VALUES(3,'Hotel Sagar','Fatehabad Road, Taj Ganj',3.5,1,0);
INSERT INTO Hotel VALUES(4,'Moti Palace Hotel & Restaur...','Opposite Garg, M G Road',3.8,1,0);
INSERT INTO Hotel VALUES(5,'9 Star Hotel','Opposite Kailash Cinema, Taj Ganj',2.6,1,0);
INSERT INTO Hotel VALUES(6,'Hotel East Gate','Nagari Phase-1, Fatehabad Road',3.5,1,0);
INSERT INTO Hotel VALUES(7,'MBD Tour And Travel','Madiya Katra, Loha Mandi',5.0,1,0);
INSERT INTO Hotel VALUES(8,'Hotel Ashish Palace','Jivan Ram Chowk, Fatehabad Road',3.7,1,0);
INSERT INTO Hotel VALUES(9,'Howard Plaza Hotel','Pizza Hut, Fatehabad Road',3.9,1,0);
INSERT INTO Hotel VALUES(10,'Hotel Dharamlok','M G Road, Raja Mandi',4.0,1,0);
INSERT INTO Hotel VALUES(11,'Narayani Hotels And Resorts...','Airport Gandhinagar Road, Airport',3.9,2,0);
INSERT INTO Hotel VALUES(12,'Neelkanth Group of Hotels','Paldi Cross Road, Paldi',3.9,2,0);
INSERT INTO Hotel VALUES(13,'Hotel Bridge','Sakar 2 4, Ellis Bridge',3.6,2,0);
INSERT INTO Hotel VALUES(14,'Hotel Kalash Residency','Oppsite Jain Temple, Navrangpura',4.1,2,0);
INSERT INTO Hotel VALUES(15,'Hotel Radiant','Paldi Cross Road, Paldi',3.9,2,0);
INSERT INTO Hotel VALUES(16,'Hotel Heritage','Paldi Cross Road, Paldi',3.8,2,0);
INSERT INTO Hotel VALUES(17,'Hotel Formule 1','Venus Atlantis, Prahladnagar',3.9,2,0);
INSERT INTO Hotel VALUES(18,'Host Inn Hotel','Shahpur Center Road, Khanpur',4.0,2,0);
INSERT INTO Hotel VALUES(19,'Hotel Krishna Palace','Nehru Park Cross Road, Vastrapur',5.0,2,0);
INSERT INTO Hotel VALUES(20,'Hotel Nami Residency','V S Hospital, Ellis Bridge',4.0,2,0);
INSERT INTO Hotel VALUES(21,'Hotel Furfura Darbar','Delhi Gate, Dargah Shareef',3.3,3,0);
INSERT INTO Hotel VALUES(22,'Hotel Payal','Prithviraj Marg, Ajmer Ho',4.1,3,0);
INSERT INTO Hotel VALUES(23,'Hotel Embassy A Unit Of Var...','Jaipur Road, Ajmer HO',3.8,3,0);
INSERT INTO Hotel VALUES(24,'Hotel Siddharth','Jaipur Road, Ajmer Ho',3.8,3,0);
INSERT INTO Hotel VALUES(25,'Hotel Kanak Sagar','P R Marg, Ajmer Ho',3.9,3,0);
INSERT INTO Hotel VALUES(26,'Hotel Sanskar','Railway Station, Ajmer Ho',5.0,3,0);
INSERT INTO Hotel VALUES(27,'Hotel Sukh Sagar & Hotel','Dhan Mandi, Dargah Shareef',3.3,3,0);
INSERT INTO Hotel VALUES(28,'Hotel Mahatma Inn','Near Railway Station, Ajmer Ho',4.7,3,0);
INSERT INTO Hotel VALUES(29,'Regal Hotel','Dargah Road, Ajmer Ho',3.8,3,0);
INSERT INTO Hotel VALUES(30,'Hotel Ajmer Inn','Purani Mandi, Ajmer Ho',3.5,3,0);
INSERT INTO Hotel VALUES(31,'Hotel Raiban','ALAPPUZHA, Alappuzha HO',4.3,4,0);
INSERT INTO Hotel VALUES(32,'Royal Rooms','47, Alappuzha District Hospital',5.0,4,0);
INSERT INTO Hotel VALUES(33,'Lake City Resort','Nh 47, Pathirappally',5.0,4,0);
INSERT INTO Hotel VALUES(34,'Western Classic Inn','Ccsb Road, Alappuzha Ho',4.2,4,0);
INSERT INTO Hotel VALUES(35,'Hotel Sisir Palace','Point Road, Thathampally',4.3,4,0);
INSERT INTO Hotel VALUES(36,'Hotel Picasso Castle','Junction, Thathampally',4.3,4,0);
INSERT INTO Hotel VALUES(37,'Thottuchira Tourist Land Pr...','Ksrtc Bus Stand, Alappuzha Ho',3.5,4,0);
INSERT INTO Hotel VALUES(38,'The Lloyds Residency','Nehru Trophy Road, Thathampally',5.0,4,0);
INSERT INTO Hotel VALUES(39,'Pagoda Resorts','Ccnb Road, Chungam',3.9,4,0);
INSERT INTO Hotel VALUES(40,'Citrus Retreats','Paravoor Village, Punnapra North',4.1,4,0);
INSERT INTO Hotel VALUES(41,'Martins Inn Beach Hotel','Arnala Beach, Arnala',3.7,5,0);
INSERT INTO Hotel VALUES(42,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,5,0);
INSERT INTO Hotel VALUES(43,'Hotel Golden Tulipz','Military Road, Andheri East',3.4,5,0);
INSERT INTO Hotel VALUES(44,'Hotel Orange Inn','Makwana Road, Andheri East',3.4,5,0);
INSERT INTO Hotel VALUES(45,'Oyo Rooms','Ghatkopar Link Road, Andheri East',3.8,5,0);
INSERT INTO Hotel VALUES(46,'Waterstones Hotel','Sahar Road, Andheri East',4.1,5,0);
INSERT INTO Hotel VALUES(47,'Hotel Capitol','Ghodbunder Road, Thane West',3.9,5,0);
INSERT INTO Hotel VALUES(48,'Hotel City Point','Dr Ambedkar Road, Dadar East',3.7,5,0);
INSERT INTO Hotel VALUES(49,'Hotel Hira Palace','Sleater Road, Grant Road',3.1,5,0);
INSERT INTO Hotel VALUES(50,'Landmark Fort Hotel','P D Mello Road, Fort',3.8,5,0);
INSERT INTO Hotel VALUES(51,'Platinum Inn','Hanuman Mandir, Civil Lines',4.5,6,0);
INSERT INTO Hotel VALUES(52,'Blessings The Ultimate','Behind Big Bazar, Civil Lines',3.9,6,0);
INSERT INTO Hotel VALUES(53,'Kundan Guest House','Tagore Town, Tagore Town',4.2,6,0);
INSERT INTO Hotel VALUES(54,'Hotel Aman Palace','mayohall, Stainly Road',5.0,6,0);
INSERT INTO Hotel VALUES(55,'Hotel Ravisha Continental','D Tandon Road, Allahabad City',3.8,6,0);
INSERT INTO Hotel VALUES(56,'Hotel Galaxy','M G Marg, Civil Lines',3.9,6,0);
INSERT INTO Hotel VALUES(57,'Hotel Limra','Niranjan Cinema, Johnstonganj',4.1,6,0);
INSERT INTO Hotel VALUES(58,'Hotel Rajpoot','Old City, Allahabad City',3.2,6,0);
INSERT INTO Hotel VALUES(59,'Subhash Hotel','Subhash Market, Johnstonganj',3.5,6,0);
INSERT INTO Hotel VALUES(60,'Prayag Hotel','Railway Station, Noorullah Road',3.8,6,0);
INSERT INTO Hotel VALUES(61,'Hotel Sunita','Kausani Road, Almora HO',3.0,7,0);
INSERT INTO Hotel VALUES(62,'The Green Village Eco Resort','Nr Jageshwar Temple, Jageshwar',4.5,7,0);
INSERT INTO Hotel VALUES(63,'Club Mahindra Binsar Valley','Almora Bageshwar Road, Binsar',4.6,7,0);
INSERT INTO Hotel VALUES(64,'Hotel Shikhar','The Mall, Almora Ho',4.0,7,0);
INSERT INTO Hotel VALUES(65,'Kasaar Jungle Resort','Binsar Road, Almora Ho',4.0,7,0);
INSERT INTO Hotel VALUES(66,'Krishna Mountview Mountain Resort','Kausani',4.5,7,0);
INSERT INTO Hotel VALUES(67,'Hotel Shivalik Almora','Vishal Mega Mart, Almora Ho',3.9,7,0);
INSERT INTO Hotel VALUES(68,'Chevron ECO Lodge','Estate Guest House Road, Kausani',5.0,7,0);
INSERT INTO Hotel VALUES(69,'Suman Royal Resort','VIP Road, Kausani',4.0,7,0);
INSERT INTO Hotel VALUES(70,'Himalaya Darshan Resort','Kausani Bhatariya Road, Kausani',5.0,7,0);
INSERT INTO Hotel VALUES(71,'Hotel Hilltop','Near Yatri Niwas, Pahalgam',3.9,8,0);
INSERT INTO Hotel VALUES(72,'Hotel Pahalgam Duke','Chandanwari Road, Pahalgam',0.0,8,0);
INSERT INTO Hotel VALUES(73,'Aksa Resort','Mandir Road, Pahalgam',0.0,8,0);
INSERT INTO Hotel VALUES(74,'Paristaan Resorts','Chandanwari Road, Pahalgam',0.0,8,0);
INSERT INTO Hotel VALUES(75,'Hotel Raj Palace','Main Market, Pahalgam',0.0,8,0);
INSERT INTO Hotel VALUES(76,'Hotel Abshar','Chandan Wari Road, Pahalgam',3.0,8,0);
INSERT INTO Hotel VALUES(77,'Mala Castle','Chandniware Road, Pahalgam',3.5,8,0);
INSERT INTO Hotel VALUES(78,'Pahalgam Resorts','Chandanwari Road, Pahalgam',3.5,8,0);
INSERT INTO Hotel VALUES(79,'Hamdard Resort','Laripora, Pahalgam',1.0,8,0);
INSERT INTO Hotel VALUES(80,'Hotel Fifth Season','Higher Secordary School, Pahalgam',0.0,8,0);
INSERT INTO Hotel VALUES(81,'Hotel Hong Kong Inn','Chowk Queens Road, Amritsar Gpo',3.8,9,0);
INSERT INTO Hotel VALUES(82,'Best Western Merrion','B- Block, Ranjit Avenue',4.3,9,0);
INSERT INTO Hotel VALUES(83,'Hotel Mg Residency','Telephone Exchange, Golden Temple',4.5,9,0);
INSERT INTO Hotel VALUES(84,'Hotel Ritz Plaza','The Mall, Amritsar GPO',4.2,9,0);
INSERT INTO Hotel VALUES(85,'S S Hotels','Maha Singh Gate, Amritsar Gpo',3.5,9,0);
INSERT INTO Hotel VALUES(86,'Avaas Lifestyle Hotel','Near Bansal Sweets, Lawrence Road',4.3,9,0);
INSERT INTO Hotel VALUES(87,'Hotel Winner Inn','Near Crystal Chowk, Amritsar Gpo',4.8,9,0);
INSERT INTO Hotel VALUES(88,'Hotel Punnu International','Bank Of Baroda, Amritsar Gpo',4.3,9,0);
INSERT INTO Hotel VALUES(89,'Hotel Robin','Jallianwala Bagh, Golden Temple',4.3,9,0);
INSERT INTO Hotel VALUES(90,'Hotel Shiraz Regency','Queens Road, Amritsar Gpo',4.0,9,0);
INSERT INTO Hotel VALUES(91,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,10,0);
INSERT INTO Hotel VALUES(92,'Hotel Golden Tulipz','Military Road, Andheri East',3.4,10,0);
INSERT INTO Hotel VALUES(93,'Hotel Orange Inn','Makwana Road, Andheri East',3.4,10,0);
INSERT INTO Hotel VALUES(94,'Oyo Rooms','Ghatkopar Link Road, Andheri East',3.8,10,0);
INSERT INTO Hotel VALUES(95,'Waterstones Hotel','Sahar Road, Andheri East',4.1,10,0);
INSERT INTO Hotel VALUES(96,'Hotel Capitol','Ghodbunder Road, Thane West',3.9,10,0);
INSERT INTO Hotel VALUES(97,'Hotel City Point','Dr Ambedkar Road, Dadar East',3.7,10,0);
INSERT INTO Hotel VALUES(98,'Hotel Hira Palace','Sleater Road, Grant Road',3.1,10,0);
INSERT INTO Hotel VALUES(99,'Landmark Fort Hotel','P D Mello Road, Fort',3.8,10,0);
INSERT INTO Hotel VALUES(100,'Hotel Yogi Executive','Sector 24, Vashi',3.9,10,0);
INSERT INTO Hotel VALUES(101,'Parkinn Resort','Appartment, Boring Road',3.4,11,0);
INSERT INTO Hotel VALUES(102,'Pearl Club Guest House & Ba...','Vivekanad Marg, Boring Road',3.5,11,0);
INSERT INTO Hotel VALUES(103,'Hotel Vinayak International','Jamal Road',4.3,11,0);
INSERT INTO Hotel VALUES(104,'La Casa','Nageshwar Colony, Boring Road',5.0,11,0);
INSERT INTO Hotel VALUES(105,'Baseraz Guest House','Sardar Patel Path, Boring Road',5.0,11,0);
INSERT INTO Hotel VALUES(106,'Hotel Fort','Station Road, Patna Gpo',3.6,11,0);
INSERT INTO Hotel VALUES(107,'Shagun','Dak Bunglow, Dak Bunglow Road',3.9,11,0);
INSERT INTO Hotel VALUES(108,'The Corporate Residence','Jagat Trade Centre, Frazer Road',2.5,11,0);
INSERT INTO Hotel VALUES(109,'Hotel Gargee Grand','Exhibition Road, Exhibition Road',4.4,11,0);
INSERT INTO Hotel VALUES(110,'Hotel Ritz And Payal Restau...','Near Patna University, Bankipur',3.6,11,0);
INSERT INTO Hotel VALUES(111,'Classic Comfort','Off Godbunder Road, Thane West',4.5,12,0);
INSERT INTO Hotel VALUES(112,'Ibis Hotel','Thane Belapur Road, Turbhe',4.0,12,0);
INSERT INTO Hotel VALUES(113,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,12,0);
INSERT INTO Hotel VALUES(114,'Oyo Rooms','Ghatkopar Link Road, Andheri East',3.8,12,0);
INSERT INTO Hotel VALUES(115,'Hotel Golden Tulipz','Military Road, Andheri East',3.4,12,0);
INSERT INTO Hotel VALUES(116,'Hotel Orange Inn','Makwana Road, Andheri East',3.4,12,0);
INSERT INTO Hotel VALUES(117,'Waterstones Hotel','Sahar Road, Andheri East',4.1,12,0);
INSERT INTO Hotel VALUES(118,'Hotel Capitol','Ghodbunder Road, Thane West',3.9,12,0);
INSERT INTO Hotel VALUES(119,'Hotel City Point','Dr Ambedkar Road, Dadar East',3.7,12,0);
INSERT INTO Hotel VALUES(120,'Landmark Fort Hotel','P D Mello Road, Fort',3.8,12,0);
INSERT INTO Hotel VALUES(121,'The Regenza By Tunga','Sector 30 A, Vashi',4.1,13,0);
INSERT INTO Hotel VALUES(122,'Hotel Jawahar','Cross Hospital, Ulhasnagar No 3',3.9,13,0);
INSERT INTO Hotel VALUES(123,'Oritel Service Apartment','Studio Road, Andheri East',3.6,13,0);
INSERT INTO Hotel VALUES(124,'Ace Residency','Military Road, Andheri East',3.6,13,0);
INSERT INTO Hotel VALUES(125,'Stay In','Sakhi Vhiar Road, Sakinaka',4.3,13,0);
INSERT INTO Hotel VALUES(126,'The Resort','Madh-Marve Road, Malad West',4.0,13,0);
INSERT INTO Hotel VALUES(127,'Hotel Royal Park','Andheri Kurla Road, Andheri East',3.8,13,0);
INSERT INTO Hotel VALUES(128,'Hotel Planet Plaza','Andheri Kurla Road, Andheri East',3.6,13,0);
INSERT INTO Hotel VALUES(129,'Martins Inn Beach Hotel','Arnala, Virar West',3.7,13,0);
INSERT INTO Hotel VALUES(130,'Hotel Check Inn','Chakala, Andheri East',2.0,13,0);
INSERT INTO Hotel VALUES(131,'Chakrie Residency Hotel','Tiruchanur Road, Tiruchanoor Road',4.2,14,0);
INSERT INTO Hotel VALUES(132,'Chethans Inn Service Apartm...','Old Tiruchanoor Road, Tirupati Ho',4.3,14,0);
INSERT INTO Hotel VALUES(133,'Elite Stays','S J Nagar, Tirupati Ho',4.0,14,0);
INSERT INTO Hotel VALUES(134,'Fortune Select Grand Ridge','Near Urbanheart, Tirupati Ho',4.2,14,0);
INSERT INTO Hotel VALUES(135,'Agarala Residency','Bhuma Cine Complex, T.P.Area',4.4,14,0);
INSERT INTO Hotel VALUES(136,'Hotel Srinivasa','Vivekananda Circle, Tirupati Ho',3.9,14,0);
INSERT INTO Hotel VALUES(137,'GPR Residency','Tirumala Bypass Arch, Tirupati Ho',4.3,14,0);
INSERT INTO Hotel VALUES(138,'Ramee Guest Line Hotel','& Post, Tirupati Ho',3.8,14,0);
INSERT INTO Hotel VALUES(139,'Bhanu Residency','Shiva Jyothi Nagar, Tirupati HO',4.0,14,0);
INSERT INTO Hotel VALUES(140,'Grand World 3-Star Hotel & ...','Karakambadi Road, Tirupathi Ho',3.9,14,0);
INSERT INTO Hotel VALUES(141,'Birla Dharmshala','Nr Bus Station, Ayodhya HO',3.1,16,0);
INSERT INTO Hotel VALUES(142,'Ramprastha Hotel','Naya Ghat Ayodhya, Ayodhya Ho',4.3,16,0);
INSERT INTO Hotel VALUES(143,'Ram Dham Guest House','Railway Station Road, Ayodhya HO',4.0,16,0);
INSERT INTO Hotel VALUES(144,'Gujarat Bhawan Dharamshala','Ayodhya, Ayodhya HO',4.0,16,0);
INSERT INTO Hotel VALUES(145,'Shri Ram Hotel','Near Hanuman Garhi, Ayodhya Ho',3.3,16,0);
INSERT INTO Hotel VALUES(146,'Nilkanth Guest House','Ranopali, Ayodhya Ho',0.0,16,0);
INSERT INTO Hotel VALUES(147,'Sahu Dharmshala','Dantdhawan Kund, Ayodhya Ho',5.0,16,0);
INSERT INTO Hotel VALUES(148,'Gupta Guest House','Nayaghat, Nayaghat',0.0,16,0);
INSERT INTO Hotel VALUES(149,'Ram Anugsah Vishram Sadan','Chhoti Chhawani Marg, Ayodhya HO',0.0,16,0);
INSERT INTO Hotel VALUES(150,'Akshay International Hotel','Commissioner Office, Navanagar',3.6,17,0);
INSERT INTO Hotel VALUES(151,'Kanthi Resort','Nh-218, Navanagar',3.5,17,0);
INSERT INTO Hotel VALUES(152,'Anand Deluxe Hotel','Beside Bus Stand, Badami',3.9,17,0);
INSERT INTO Hotel VALUES(153,'Royal Deluxe Lodge','Station Road, Badami',5.0,17,0);
INSERT INTO Hotel VALUES(154,'Rajsangam International Hotel','Station Road, Badami',3.4,17,0);
INSERT INTO Hotel VALUES(155,'The Heritage Resort','Station Road, Badami',4.4,17,0);
INSERT INTO Hotel VALUES(156,'Hotel Badami Court','Station Road, Badami',4.3,17,0);
INSERT INTO Hotel VALUES(157,'Hotel Mayura Chalukya','Ramdurg Road, Badami',4.2,17,0);
INSERT INTO Hotel VALUES(158,'Hotel Mookambika Deluxe','Station Road, Badami',4.0,17,0);
INSERT INTO Hotel VALUES(159,'Sanman Delux Lodge','Near Bus Stand, Badami',4.0,17,0);
INSERT INTO Hotel VALUES(160,'The Wild Flower at Bandhavgarh','Road, Bandhavgarh National Park',4.1,19,0);
INSERT INTO Hotel VALUES(161,'Tigers Den Resort','Petrol, Bandhavgarh National Park',4.0,19,0);
INSERT INTO Hotel VALUES(162,'The Celebration Van Vilas','Tala, Bandhavgarh National Park',3.5,19,0);
INSERT INTO Hotel VALUES(163,'Hotel Whisepering Grass','Tala, Bandhavgarh National Park',3.5,19,0);
INSERT INTO Hotel VALUES(164,'Mogli Jungle Resorts','Tala, Bandhavgarh National Park',3.5,19,0);
INSERT INTO Hotel VALUES(165,'Mahua Kothi','Umaria, Bandhavgarh National Park',2.7,19,0);
INSERT INTO Hotel VALUES(166,'Bandhavgarh Meadows Resort','Tala, Bandhavgarh National Park',4.9,19,0);
INSERT INTO Hotel VALUES(167,'Tiger Lagoon Resort','Tala, Bandhavgarh National Park',4.0,19,0);
INSERT INTO Hotel VALUES(168,'Syna Tiger Resort','Tala, Bandhavgarh National Park',3.6,19,0);
INSERT INTO Hotel VALUES(169,'Bandhav Vilas Resort','Tala, Bandhavgarh National Park',5.0,19,0);
INSERT INTO Hotel VALUES(170,'Hotel Crystal Paark Inn','Nazarabad Main Road, Nazarbad',3.9,20,0);
INSERT INTO Hotel VALUES(171,'Sandesh The Prince Hotel','Nazarbad Main Road, Nazarbad',4.2,20,0);
INSERT INTO Hotel VALUES(172,'The Grand Inn Mysore','Iyengar Road, Lashkar Mohalla',4.3,20,0);
INSERT INTO Hotel VALUES(173,'Silent Shores Resort And Spa','Krs Road, Hootagalli',4.2,20,0);
INSERT INTO Hotel VALUES(174,'Jalmahal Resort And Spa','Bhugathagalli Village, Mysore',4.3,20,0);
INSERT INTO Hotel VALUES(175,'The Quorum Hotel','B-1, Vinoba Road',2.5,20,0);
INSERT INTO Hotel VALUES(176,'Ganesh Prasad Lodge','Main Road, Shivarampet',3.7,20,0);
INSERT INTO Hotel VALUES(177,'Aishwarya Suites','New Bamboo Bazar, Banni Mantap',3.9,20,0);
INSERT INTO Hotel VALUES(178,'Young Island Resorts','Srirangapatna, Mysore',3.6,20,0);
INSERT INTO Hotel VALUES(179,'Yashas Residency','Bogadi 2nd Stage, Bogadi',3.6,20,0);
INSERT INTO Hotel VALUES(180,'West Nature Cottages','West Lake Nilgiri, Ooty Ho',4.2,21,0);
INSERT INTO Hotel VALUES(181,'Sana Cottage','Upper Bazaar, Ooty HO',3.9,21,0);
INSERT INTO Hotel VALUES(182,'The Monarch Hotel','Off Havelock Road, Ooty Ho',4.3,21,0);
INSERT INTO Hotel VALUES(183,'Hotel Sapphire Paradise','Ettines Road, Ooty Ho',4.2,21,0);
INSERT INTO Hotel VALUES(184,'Kurinji Residency','Near Ganapathi Theatre, Ooty Ho',3.7,21,0);
INSERT INTO Hotel VALUES(185,'Mystique Ville','Ghat Road Kalhatti, Theetukal',4.6,21,0);
INSERT INTO Hotel VALUES(186,'Royal Mist','Westbury, Mysore Road',3.8,21,0);
INSERT INTO Hotel VALUES(187,'Sierra Vale','M Palada, Ooty',3.9,21,0);
INSERT INTO Hotel VALUES(188,'R K Homes','DAS Prakash Road, Ooty HO',3.9,21,0);
INSERT INTO Hotel VALUES(189,'Oaks Villa','Orange Grove Road, Wellington',3.5,21,0);
INSERT INTO Hotel VALUES(190,'Hotel Adarsha Palace','Lingaraj, College Road Belgaum',4.0,22,0);
INSERT INTO Hotel VALUES(191,'Pai Hotel And Lodging','P B Road, Belgaum Ho',3.9,22,0);
INSERT INTO Hotel VALUES(192,'Rakshit International Hotel','Medical, Belgaum Nehru Nagar',3.8,22,0);
INSERT INTO Hotel VALUES(193,'Hotel Anupam','Railway, Shivaji Road Belgaum',3.8,22,0);
INSERT INTO Hotel VALUES(194,'Sukh Sagar Lodge And Restau...','Congress Road, Tilakwadi Belgaum',4.7,22,0);
INSERT INTO Hotel VALUES(195,'Alurkar Resorts','Hukkeri Taluk, Bugatealur Belgaum',3.5,22,0);
INSERT INTO Hotel VALUES(196,'Pai Resort','Road, Gandhi Nagar Belgaum',3.9,22,0);
INSERT INTO Hotel VALUES(197,'Hotel Comfort Inn','Navyug Complex, Khade Bazaar',3.3,22,0);
INSERT INTO Hotel VALUES(198,'Hotel Satkar','Maruti Lane, Maruti Galli Belgaum',4.1,22,0);
INSERT INTO Hotel VALUES(199,'Hotel Comfort Inn','P, P B Road Belgaum',1.0,22,0);
INSERT INTO Hotel VALUES(200,'Ashok Hotel','Chinoy Road, Matheran Ho',4.0,23,0);
INSERT INTO Hotel VALUES(201,'Hotel Krishna Matheran','Kasturba Road, Matheran HO',3.5,23,0);
INSERT INTO Hotel VALUES(202,'Bombay View Hotel Matheran','Road Chinoy Road, Matheran Ho',4.0,23,0);
INSERT INTO Hotel VALUES(203,'Spring Wood Heritage','Kasturba Road, Matheran Ho',4.7,23,0);
INSERT INTO Hotel VALUES(204,'Hotel Anandritz Presstige','Police Station, Matheran HO',3.5,23,0);
INSERT INTO Hotel VALUES(205,'The Byke Hotel','M G Road, Matheran Ho',3.8,23,0);
INSERT INTO Hotel VALUES(206,'Horseland Hotel & Mountain Spa','Kotwal Road, Matheran Ho',3.9,23,0);
INSERT INTO Hotel VALUES(207,'Adamo The Resort','M G Road, Matheran Ho',3.9,23,0);
INSERT INTO Hotel VALUES(208,'Regal Hotel','Kasturba Road, Matheran Ho',4.0,23,0);
INSERT INTO Hotel VALUES(209,'Usha Ascot','M G Road, Matheran Ho',3.8,23,0);
INSERT INTO Hotel VALUES(210,'Minerva Residency','Lalbagh Fort Road, Mavalli',3.7,24,0);
INSERT INTO Hotel VALUES(211,'Pai Comforts','2nd Phase, J P Nagar',4.1,24,0);
INSERT INTO Hotel VALUES(212,'Oyo Rooms','Rest House Road, Brigade Road',3.5,24,0);
INSERT INTO Hotel VALUES(213,'Dass Suites','Koramangala 4th Block',4.6,24,0);
INSERT INTO Hotel VALUES(214,'Oyo Rooms','Main Road, Bangalore City',3.3,24,0);
INSERT INTO Hotel VALUES(215,'Sri Sai Hotel','4th Block, Koramangala',3.5,24,0);
INSERT INTO Hotel VALUES(216,'Elim Resorts','Bollare Post, Kanakapura Road',3.8,24,0);
INSERT INTO Hotel VALUES(217,'Royal Orchid Central','Manipal Centre, Dickenson Road',4.0,24,0);
INSERT INTO Hotel VALUES(218,'Liwa Hotel','Airport Road, Hebbal',4.1,24,0);
INSERT INTO Hotel VALUES(219,'The Chevron Hotel','Offlice, Infantry Road',3.7,24,0);
INSERT INTO Hotel VALUES(220,'Shivam Inn','& Haniman Crossing, Gomti Nagar',4.2,25,0);
INSERT INTO Hotel VALUES(221,'S B G Guest Inn','Beside City Mall, Gomti Nagar',3.5,25,0);
INSERT INTO Hotel VALUES(222,'Hotel S P International','Near, Gautam Budh Marg(Gb Marg)',4.1,25,0);
INSERT INTO Hotel VALUES(223,'Anr Hotels','Gurudwara Road, Lucknow',3.8,25,0);
INSERT INTO Hotel VALUES(224,'Awadh Court Guest House','Vivek Khand, Gomti Nagar',4.3,25,0);
INSERT INTO Hotel VALUES(225,'Garden Gates Inn','Viraj Khand, Gomti Nagar',5.0,25,0);
INSERT INTO Hotel VALUES(226,'Hotel G Rest','Opposite Bata Showroom, Aminabad',4.5,25,0);
INSERT INTO Hotel VALUES(227,'Hotel Budha Residency','All India, Vidhan Sabha Marg',3.8,25,0);
INSERT INTO Hotel VALUES(228,'Saubhagyam Residency','Nagar Police Station, Gomti Nagar',3.3,25,0);
INSERT INTO Hotel VALUES(229,'Crown Inn','R T College, Gomti Nagar',5.0,25,0);
INSERT INTO Hotel VALUES(230,'Hotel Gayatri Palace','Ahiyapur, Ahiyapur',4.2,26,0);
INSERT INTO Hotel VALUES(231,'Hotel Simna International','Main Road, Muzaffarpur Ho',4.7,26,0);
INSERT INTO Hotel VALUES(232,'Hotel Chandralok Continental','Chandralok Market, Naya Tola',4.9,26,0);
INSERT INTO Hotel VALUES(233,'Hotel Classic Executive and...','Akharaghat Road, Akharaghat',3.3,26,0);
INSERT INTO Hotel VALUES(234,'The Park','Mithanpura Club Road, Ramna',4.0,26,0);
INSERT INTO Hotel VALUES(235,'Hotel Shivam Inn','Motijheel, Motijheel',4.4,26,0);
INSERT INTO Hotel VALUES(236,'Hotel Aastha','Chatti Main Road, Imili Chatti',3.5,26,0);
INSERT INTO Hotel VALUES(237,'Hotel L B Continental','Kalyani Chowk, Motijheel',3.7,26,0);
INSERT INTO Hotel VALUES(238,'Minakshi International Hotel','Railway Station, Muzaffarpur HO',4.1,26,0);
INSERT INTO Hotel VALUES(239,'Hotel Milan Residential','Kalambagh Chowk, Muzaffarpur Ho',4.5,26,0);
INSERT INTO Hotel VALUES(240,'Hotel The Nook','Mahaboopalayam, Madurai City',4.0,27,0);
INSERT INTO Hotel VALUES(241,'M3 Boutique Hotel','Road Shenoy Nagar, Shenoy Nagar',4.2,27,0);
INSERT INTO Hotel VALUES(242,'GRT Regency','7 Madakulam Road, Palanganatham',4.2,27,0);
INSERT INTO Hotel VALUES(243,'Hotel Vaani Villa Service A...','College Road, Thirupparankundram',4.2,27,0);
INSERT INTO Hotel VALUES(244,'V Grand Hotel','Surveyor Colony Road, Madurai Ho',4.1,27,0);
INSERT INTO Hotel VALUES(245,'P K N Residency','Theni Main Road, Kochadai',3.4,27,0);
INSERT INTO Hotel VALUES(246,'Hotel Royal Court','West Veli Street, Madurai Ho',4.2,27,0);
INSERT INTO Hotel VALUES(247,'Hotel Chentoor','Maistry Street, Madurai City',3.9,27,0);
INSERT INTO Hotel VALUES(248,'Hotel Jeyasakthi','Bye Pass, S S Colony',3.9,27,0);
INSERT INTO Hotel VALUES(249,'Amohaa Service Apartment','Colony North, S S Colony',3.5,27,0);
INSERT INTO Hotel VALUES(250,'Kolkars Lodge','Sector No 12, Panvel',3.7,28,0);
INSERT INTO Hotel VALUES(251,'Hotel Sharanam','Service Road, Thane West',3.8,28,0);
INSERT INTO Hotel VALUES(252,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,28,0);
INSERT INTO Hotel VALUES(253,'Hotel Golden Tulipz','Military Road, Andheri East',3.4,28,0);
INSERT INTO Hotel VALUES(254,'Hotel Orange Inn','Makwana Road, Andheri East',3.4,28,0);
INSERT INTO Hotel VALUES(255,'Oyo Rooms','Ghatkopar Link Road, Andheri East',3.8,28,0);
INSERT INTO Hotel VALUES(256,'Hotel Capitol','Ghodbunder Road, Thane West',3.9,28,0);
INSERT INTO Hotel VALUES(257,'Hotel City Point','Dr Ambedkar Road, Dadar East',3.7,28,0);
INSERT INTO Hotel VALUES(258,'Hotel Hira Palace','Sleater Road, Grant Road',3.1,28,0);
INSERT INTO Hotel VALUES(259,'Landmark Fort Hotel','P D Mello Road, Fort',3.8,28,0);
INSERT INTO Hotel VALUES(260,'Hotel Shiva International','Bus Stand, Udgir Road Bidar',4.1,29,0);
INSERT INTO Hotel VALUES(261,'Mayura Hotel','Udgir Road, Bidar Ho',3.5,29,0);
INSERT INTO Hotel VALUES(262,'Blackbuck Resort','Vilaspur Post, Bidar Ho',4.2,29,0);
INSERT INTO Hotel VALUES(263,'Sapna International Hotel','Near Central, Udgir Road Bidar',4.0,29,0);
INSERT INTO Hotel VALUES(264,'Sapna Continental Hotel','Udgir Road, Bidar Ho',3.8,29,0);
INSERT INTO Hotel VALUES(265,'Rajdhani Travels','Old Bus Stand, Bidar Ho',5.0,29,0);
INSERT INTO Hotel VALUES(266,'Ashoka Hotel','Sales Tax Office, Bidar Ho',3.9,29,0);
INSERT INTO Hotel VALUES(267,'Shanti Lodge','Old Bus, Railway Station Bidar',3.3,29,0);
INSERT INTO Hotel VALUES(268,'Krishna Regency Hotel','New Bus, Udgir Road Bidar',3.8,29,0);
INSERT INTO Hotel VALUES(269,'Jyothi Way Side Resort & Amuse...','Main Road, Humnabad',0.0,29,0);
INSERT INTO Hotel VALUES(270,'Hotel City View','Sector 24, Sanpada',3.7,30,0);
INSERT INTO Hotel VALUES(271,'Gcc Hotels Pvt Ltd','Mira Bhayandar Road, Mira Road',4.0,30,0);
INSERT INTO Hotel VALUES(272,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,30,0);
INSERT INTO Hotel VALUES(273,'Hotel Golden Tulipz','Military Road, Andheri East',3.4,30,0);
INSERT INTO Hotel VALUES(274,'Oyo Rooms','Ghatkopar Link Road, Andheri East',3.8,30,0);
INSERT INTO Hotel VALUES(275,'Hotel Orange Inn','Makwana Road, Andheri East',3.4,30,0);
INSERT INTO Hotel VALUES(276,'Waterstones Hotel','Sahar Road, Andheri East',4.1,30,0);
INSERT INTO Hotel VALUES(277,'Hotel Capitol','Ghodbunder Road, Thane West',3.9,30,0);
INSERT INTO Hotel VALUES(278,'Hotel City Point','Dr Ambedkar Road, Dadar East',3.7,30,0);
INSERT INTO Hotel VALUES(279,'Landmark Fort Hotel','P D Mello Road, Fort',3.8,30,0);
INSERT INTO Hotel VALUES(280,'Executive Enclave Hotel','Dr Ambedkar Road, Bandra West',3.8,31,0);
INSERT INTO Hotel VALUES(281,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,31,0);
INSERT INTO Hotel VALUES(282,'Oyo Rooms','Ghatkopar Link Road, Andheri East',3.8,31,0);
INSERT INTO Hotel VALUES(283,'Hotel Golden Tulipz','Military Road, Andheri East',3.4,31,0);
INSERT INTO Hotel VALUES(284,'Hotel Orange Inn','Makwana Road, Andheri East',3.4,31,0);
INSERT INTO Hotel VALUES(285,'Waterstones Hotel','Sahar Road, Andheri East',4.1,31,0);
INSERT INTO Hotel VALUES(286,'Hotel Capitol','Ghodbunder Road, Thane West',3.9,31,0);
INSERT INTO Hotel VALUES(287,'Hotel City Point','Dr Ambedkar Road, Dadar East',3.7,31,0);
INSERT INTO Hotel VALUES(288,'Landmark Fort Hotel','P D Mello Road, Fort',3.8,31,0);
INSERT INTO Hotel VALUES(289,'Hotel Hira Palace','Sleater Road, Grant Road',3.1,31,0);
INSERT INTO Hotel VALUES(290,'Sambodhi Retreat','Village Hathiyar, Bodhgaya HO',4.2,32,0);
INSERT INTO Hotel VALUES(291,'The Royal Residency Hotel','Dumuhan Road, Bodhgaya HO',3.6,32,0);
INSERT INTO Hotel VALUES(292,'Hotel Taj Darbar','Mastipur, Bodhgaya Ho',4.3,32,0);
INSERT INTO Hotel VALUES(293,'Niranjana Hotel','Infront Of Museum, Bodhgaya HO',2.7,32,0);
INSERT INTO Hotel VALUES(294,'Bodhgaya Regency Hotel','Japanese Temple, Bodhgaya Ho',5.0,32,0);
INSERT INTO Hotel VALUES(295,'Lotus Nikko Hotel','Near Asi Museum, Bodhgaya HO',5.0,32,0);
INSERT INTO Hotel VALUES(296,'Tathagat International Hotel','Maha Bodhi Temple, Bodhgaya HO',0.0,32,0);
INSERT INTO Hotel VALUES(297,'Hotel Buddha International','Near Japanese Temple, Bodhgaya HO',4.5,32,0);
INSERT INTO Hotel VALUES(298,'Hotel Galaxy Intercontinental','Bodhgaya HO',0.0,32,0);
INSERT INTO Hotel VALUES(299,'R K International Hotel','Near Thai Temple, Bodhgaya HO',3.0,32,0);
INSERT INTO Hotel VALUES(300,'Hotel Triveni','Bolangir, Balangir HO',3.9,33,0);
INSERT INTO Hotel VALUES(301,'Ashok Hotel','Balangir, Balangir HO',3.8,33,0);
INSERT INTO Hotel VALUES(302,'Samrat Hotel','Balangir, Balangir HO',3.6,33,0);
INSERT INTO Hotel VALUES(303,'Hotel Old Paradies','Balangir, Balangir HO',4.0,33,0);
INSERT INTO Hotel VALUES(304,'Hotel Bhammars','Mandir Road, Balangir Ho',3.0,33,0);
INSERT INTO Hotel VALUES(305,'Anadi Communication','Old Palace Road, Balangir Ho',0.0,33,0);
INSERT INTO Hotel VALUES(306,'Raj Kumar Agency','Odisha, Balangir Ho',0.0,33,0);
INSERT INTO Hotel VALUES(307,'Ganapati Lodge','Balangir Ho',0.0,33,0);
INSERT INTO Hotel VALUES(308,'Nilachakra Lodge','Gopalji Road, Balangir Ho',0.0,33,0);
INSERT INTO Hotel VALUES(309,'Alishan Palace Resort Pvt Ltd','Road, Kantabanji Bazar',3.9,33,0);
INSERT INTO Hotel VALUES(310,'Oritel Service Apartment','Studio Road, Andheri East',3.6,34,0);
INSERT INTO Hotel VALUES(311,'Hotel City Point','Dr Ambedkar Road, Dadar East',3.7,34,0);
INSERT INTO Hotel VALUES(312,'Ace Residency','Military Road, Andheri East',3.6,34,0);
INSERT INTO Hotel VALUES(313,'The Resort','Madh-Marve Road, Malad West',4.0,34,0);
INSERT INTO Hotel VALUES(314,'Stay In','Sakhi Vhiar Road, Sakinaka',4.3,34,0);
INSERT INTO Hotel VALUES(315,'Hotel Royal Park','Andheri Kurla Road, Andheri East',3.8,34,0);
INSERT INTO Hotel VALUES(316,'Hotel Planet Plaza','Andheri Kurla Road, Andheri East',3.6,34,0);
INSERT INTO Hotel VALUES(317,'The Regenza By Tunga','Sector 30 A, Vashi',4.1,34,0);
INSERT INTO Hotel VALUES(318,'Martins Inn Beach Hotel','Arnala, Virar West',3.7,34,0);
INSERT INTO Hotel VALUES(319,'Abbott Hotel','Sector 2, Vashi',4.0,34,0);
INSERT INTO Hotel VALUES(320,'Hotel Royal Dreams','Pathankot Highway, Chamba Ho',5.0,35,0);
INSERT INTO Hotel VALUES(321,'Hotel Hritik Palace','Chamba Khajjiar Road, Khajjiar',2.5,35,0);
INSERT INTO Hotel VALUES(322,'Royal Residency','Khajjiar Chamba Road, Chamba Ho',3.8,35,0);
INSERT INTO Hotel VALUES(323,'Hotel Mini Swiss','Khajjiar',3.7,35,0);
INSERT INTO Hotel VALUES(324,'Devdar Hotel','Khajjiar',3.7,35,0);
INSERT INTO Hotel VALUES(325,'Anantson Resorts','Chamba Tissa Road, Chamba Ho',0.0,35,0);
INSERT INTO Hotel VALUES(326,'Aroma Palace Hotel','Court Ln, Chamba Ho',3.5,35,0);
INSERT INTO Hotel VALUES(327,'Ashiana Regency Hotel','Upper Julahkari, Chamba Ho',4.2,35,0);
INSERT INTO Hotel VALUES(328,'City Heart Hotel','Oppsite Chowgan, Chamba Ho',4.0,35,0);
INSERT INTO Hotel VALUES(329,'Shining Star Resort Dalhousie','Near Dalhousie, Khajjiar',4.0,35,0);
INSERT INTO Hotel VALUES(330,'The Sonnet','Salt Lake City,',4.0,36,0);
INSERT INTO Hotel VALUES(331,'Hotel Vip International','Free School Street, Park Street',3.6,36,0);
INSERT INTO Hotel VALUES(332,'Senses Hotel','Salt Lake City Sector 5',4.1,36,0);
INSERT INTO Hotel VALUES(333,'Orkos Hotel','Prantik Pally,',4.1,36,0);
INSERT INTO Hotel VALUES(334,'Marble Palace Guest House','Near Menoka Cinema Hall,',3.6,36,0);
INSERT INTO Hotel VALUES(335,'Green View Hotel','Park Circus Maidan,',3.6,36,0);
INSERT INTO Hotel VALUES(336,'Panasia Guest House','Near Technopolis Building,',3.8,36,0);
INSERT INTO Hotel VALUES(337,'Dee Empresa Hotel','Kyd Street,',3.7,36,0);
INSERT INTO Hotel VALUES(338,'Malik Guest House','Harish Mukherjee Road,',3.8,36,0);
INSERT INTO Hotel VALUES(339,'Park Guest House pvt Ltd','Gariahat Road South,',3.6,36,0);
INSERT INTO Hotel VALUES(340,'Hotel Emerald','Marag, Chandigarh Sector 8c',4.3,37,0);
INSERT INTO Hotel VALUES(341,'Best Western Premier Almeida','Chandigarh Airport, Zirakpur HO',4.8,37,0);
INSERT INTO Hotel VALUES(342,'Hotel Rajshree','Phase-1, Industrial Area',4.0,37,0);
INSERT INTO Hotel VALUES(343,'Hotel Dreamland','Near Housing Board, Mani Majra',4.0,37,0);
INSERT INTO Hotel VALUES(344,'Hotel Diamond Plaza','Markfed, Chandigarh Sector 22c',3.9,37,0);
INSERT INTO Hotel VALUES(345,'Oyo Rooms','Chandigarh',3.5,37,0);
INSERT INTO Hotel VALUES(346,'The First Hotel','Sector 43b, Chandigarh Sector 43',4.3,37,0);
INSERT INTO Hotel VALUES(347,'Majors Serviced Apartment A...','Major HP Singh, Mohali',3.5,37,0);
INSERT INTO Hotel VALUES(348,'Hotel City Heart Residency','Isbt, Chandigarh Sector 22b',4.1,37,0);
INSERT INTO Hotel VALUES(349,'Hotel Star Welcome','Bharat Gas, Chandigarh Sector 42c',3.2,37,0);
INSERT INTO Hotel VALUES(350,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,38,0);
INSERT INTO Hotel VALUES(351,'Kolkars Lodge','Sector No 12, Panvel',3.7,38,0);
INSERT INTO Hotel VALUES(352,'Oritel Service Apartment','Studio Road, Andheri East',3.6,38,0);
INSERT INTO Hotel VALUES(353,'Hotel Golden Tulipz','Military Road, Andheri East',3.4,38,0);
INSERT INTO Hotel VALUES(354,'Hotel Orange Inn','Makwana Road, Andheri East',3.4,38,0);
INSERT INTO Hotel VALUES(355,'Oyo Rooms','Ghatkopar Link Road, Andheri East',3.8,38,0);
INSERT INTO Hotel VALUES(356,'Hotel Hira Palace','Sleater Road, Grant Road',3.1,38,0);
INSERT INTO Hotel VALUES(357,'Hotel Capitol','Ghodbunder Road, Thane West',3.9,38,0);
INSERT INTO Hotel VALUES(358,'Hotel City Point','Dr Ambedkar Road, Dadar East',3.7,38,0);
INSERT INTO Hotel VALUES(359,'Landmark Fort Hotel','P D Mello Road, Fort',3.8,38,0);
INSERT INTO Hotel VALUES(360,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,39,0);
INSERT INTO Hotel VALUES(361,'Hotel Golden Tulipz','Military Road, Andheri East',3.4,39,0);
INSERT INTO Hotel VALUES(362,'Hotel Orange Inn','Makwana Road, Andheri East',3.4,39,0);
INSERT INTO Hotel VALUES(363,'Oyo Rooms','Ghatkopar Link Road, Andheri East',3.8,39,0);
INSERT INTO Hotel VALUES(364,'Hotel Hira Palace','Sleater Road, Grant Road',3.1,39,0);
INSERT INTO Hotel VALUES(365,'Hotel Capitol','Ghodbunder Road, Thane West',3.9,39,0);
INSERT INTO Hotel VALUES(366,'Hotel City Point','Dr Ambedkar Road, Dadar East',3.7,39,0);
INSERT INTO Hotel VALUES(367,'Landmark Fort Hotel','P D Mello Road, Fort',3.8,39,0);
INSERT INTO Hotel VALUES(368,'Hotel Mourya Residency Pvt Ltd','Platform No 2, Thane West',3.9,39,0);
INSERT INTO Hotel VALUES(369,'Hotel Nice','Station Road, Goregaon West',3.5,39,0);
INSERT INTO Hotel VALUES(370,'Oyo Rooms','Vadapalani, Chennai Ho',3.5,40,0);
INSERT INTO Hotel VALUES(371,'Leisure Stays','Ecr Road, Injambakkam',4.1,40,0);
INSERT INTO Hotel VALUES(372,'The Checkers','Mount Road Anna Salai, Saidapet',3.8,40,0);
INSERT INTO Hotel VALUES(373,'Hotel Chennai Gateway','Jn 100 Feet Road, Koyambedu',3.8,40,0);
INSERT INTO Hotel VALUES(374,'Indeco Leisure Hotels Pvt Ltd','Ecr Road, Thiruvanmiyur',4.0,40,0);
INSERT INTO Hotel VALUES(375,'Chennai Stays','Street Habibullah Road, T Nagar',3.8,40,0);
INSERT INTO Hotel VALUES(376,'Esthell Continental Hotels ...','Besant Avenue Road, Adyar',3.9,40,0);
INSERT INTO Hotel VALUES(377,'Hotel Royal Plaza','E Road, Koyambedu',4.0,40,0);
INSERT INTO Hotel VALUES(378,'Sai Mohanashree Shelters','Nehru Street, Sholinganallur',3.8,40,0);
INSERT INTO Hotel VALUES(379,'Sikara','Johnson Street, Tambaram West',3.3,40,0);
INSERT INTO Hotel VALUES(380,'Heavens Land Hotel','Main Road, Chidambaram Ho',3.9,41,0);
INSERT INTO Hotel VALUES(381,'Arudhra Residency','East Sannathi, Chidambaram Ho',4.4,41,0);
INSERT INTO Hotel VALUES(382,'Natraja Residency','Sp Koil Street, Chidambaram Ho',3.9,41,0);
INSERT INTO Hotel VALUES(383,'Nakshatra Lodge','P Kovil Street, Chidambaram Ho',3.0,41,0);
INSERT INTO Hotel VALUES(384,'Hotel Grand Park','East car street, Chidambaram Ho',3.7,41,0);
INSERT INTO Hotel VALUES(385,'Vandayar Hotel','Vgp Street, Chidambaram Ho',4.2,41,0);
INSERT INTO Hotel VALUES(386,'Akshaya Hotel','East Car Street, Chidambaram Ho',4.0,41,0);
INSERT INTO Hotel VALUES(387,'R K Residency Hotel','Vgp Street, Chidambaram Ho',3.6,41,0);
INSERT INTO Hotel VALUES(388,'Jayaraman Hotel','P Koil Street, Chidambaram HO',3.9,41,0);
INSERT INTO Hotel VALUES(389,'Grand Palace Stay Hotel','Feeder Road, Chidambaram Ho',3.8,41,0);
INSERT INTO Hotel VALUES(390,'Laila Palace','LIC Colony Road, Alagapuram',3.9,42,0);
INSERT INTO Hotel VALUES(391,'Vasantham Hotel','Vasantham Road, Alagapuram',4.0,42,0);
INSERT INTO Hotel VALUES(392,'Juhu Grand Service Apartment','reddiyur, Alagapurampudur',3.9,42,0);
INSERT INTO Hotel VALUES(393,'Kirthika Palace Hotel','Road Ram Bazaar, Alagapuram',3.9,42,0);
INSERT INTO Hotel VALUES(394,'Sri Velumuragan Lodge','Trichy Main Road, Kitchipalayam',4.2,42,0);
INSERT INTO Hotel VALUES(395,'Gold Ray Residency','Brindavan Road, Fair Lands',4.0,42,0);
INSERT INTO Hotel VALUES(396,'Sri Sai Vikas Lodge','Main Road, Suramangalam',4.0,42,0);
INSERT INTO Hotel VALUES(397,'Sri Akb Classic Lodge','Second Agraharam, Agraharam',3.7,42,0);
INSERT INTO Hotel VALUES(398,'Hotel Amr Evvergreen','Omalur Main Road, Arisipalayam',4.1,42,0);
INSERT INTO Hotel VALUES(399,'Park Plaza Hotel','Highway Road, Jagir Ammapalayam',4.2,42,0);
INSERT INTO Hotel VALUES(400,'Sree Murugan Hotel','Hall Road, Coimbatore Central',3.9,43,0);
INSERT INTO Hotel VALUES(401,'The Kr Residency','Road, Coimbatore Aerodrome',4.3,43,0);
INSERT INTO Hotel VALUES(402,'Grand Plazza','Hall Road, Coimbatore Central',4.1,43,0);
INSERT INTO Hotel VALUES(403,'Metro Park Inn And Barbeque...','Raja Street, Town Hall',3.9,43,0);
INSERT INTO Hotel VALUES(404,'Hotel Jansi Deluxe','Cut Road, Gandhipuram Coimbatore',4.1,43,0);
INSERT INTO Hotel VALUES(405,'Illas Domain Service Apartm...','Avinashi Road, Peelamedu',3.9,43,0);
INSERT INTO Hotel VALUES(406,'Hotel Vijai Paradise','S R Road, Saibaba Colony',4.0,43,0);
INSERT INTO Hotel VALUES(407,'The Premier Residency','B R Puram, Peelamedu',3.9,43,0);
INSERT INTO Hotel VALUES(408,'Hotel Raamus','& Co Lane, Coimbatore Central',4.0,43,0);
INSERT INTO Hotel VALUES(409,'The Arcadia','Goldwins, Coimbatore Aerodrome',4.1,43,0);
INSERT INTO Hotel VALUES(410,'Sree Harshav Cottages','Springfield, Coonoor Ho',5.0,44,0);
INSERT INTO Hotel VALUES(411,'Oaks Villa','Orange Grove Road, Coonoor Ho',4.1,44,0);
INSERT INTO Hotel VALUES(412,'Greenview Rest House','Ottupattarai, Coonoor Ho',5.0,44,0);
INSERT INTO Hotel VALUES(413,'Sunvalley Homestay','Near Stanley Park, Coonoor Ho',4.3,44,0);
INSERT INTO Hotel VALUES(414,'The Gateway Hotel','Church Road, Coonoor Ho',4.1,44,0);
INSERT INTO Hotel VALUES(415,'Vivek Hotel','Of 8 Road, Coonoor HO',3.9,44,0);
INSERT INTO Hotel VALUES(416,'Kurumba Village Resort','Mettupalayam Road, Coonoor Rs',4.6,44,0);
INSERT INTO Hotel VALUES(417,'Sree Venkateswara Lodge','Near Railway Station, Coonoor RS',3.8,44,0);
INSERT INTO Hotel VALUES(418,'Blue Hills Hotel','Mount Road, Coonoor HO',3.6,44,0);
INSERT INTO Hotel VALUES(419,'Kumars Mountain View Cottage','Kotagiri Road, Coonoor HO',5.0,44,0);
INSERT INTO Hotel VALUES(420,'The Regenza By Tunga','Sector 30 A, Vashi',4.1,45,0);
INSERT INTO Hotel VALUES(421,'Ace Residency','Military Road, Andheri East',3.6,45,0);
INSERT INTO Hotel VALUES(422,'Stay In','Sakhi Vhiar Road, Sakinaka',4.3,45,0);
INSERT INTO Hotel VALUES(423,'The Resort','Madh-Marve Road, Malad West',4.0,45,0);
INSERT INTO Hotel VALUES(424,'Hotel Royal Park','Andheri Kurla Road, Andheri East',3.8,45,0);
INSERT INTO Hotel VALUES(425,'Hotel Planet Plaza','Andheri Kurla Road, Andheri East',3.6,45,0);
INSERT INTO Hotel VALUES(426,'Martins Inn Beach Hotel','Arnala, Virar West',3.7,45,0);
INSERT INTO Hotel VALUES(427,'Oritel Service Apartment','Studio Road, Andheri East',3.6,45,0);
INSERT INTO Hotel VALUES(428,'Hotel Check Inn','Chakala, Andheri East',2.0,45,0);
INSERT INTO Hotel VALUES(429,'Karl Residency','Lallubhai Park, Andheri West',3.8,45,0);
INSERT INTO Hotel VALUES(430,'The Senate Hotel','Road North End, Ernakulam North',4.3,46,0);
INSERT INTO Hotel VALUES(431,'Hotel Srinivas','M G, M G Road',4.0,46,0);
INSERT INTO Hotel VALUES(432,'Hotel Millennium Continental','Junction, Ernakulam College',3.9,46,0);
INSERT INTO Hotel VALUES(433,'Sree Radha Nivas','Convent Road Kochi, Ernakulam',3.5,46,0);
INSERT INTO Hotel VALUES(434,'Brunton Boatyard Hotel','Fort Cochin, Kochi',4.5,46,0);
INSERT INTO Hotel VALUES(435,'Malabar House Residency Pvt Ltd','Fort Cochin, Kochi Fort',4.0,46,0);
INSERT INTO Hotel VALUES(436,'Seagull Hotel','Fort Kochi, Kochi',3.6,46,0);
INSERT INTO Hotel VALUES(437,'Old Lighthouse Bristow Hotel','Fort Kochi, Kochi',4.7,46,0);
INSERT INTO Hotel VALUES(438,'Hotel Fort Queen','Pandikudy, Kochi Fort',4.1,46,0);
INSERT INTO Hotel VALUES(439,'Alapatt Regency','Ernakulam, Kochi',3.0,46,0);
INSERT INTO Hotel VALUES(440,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,48,0);
INSERT INTO Hotel VALUES(441,'Landmark Fort Hotel','P D Mello Road, Fort',3.8,48,0);
INSERT INTO Hotel VALUES(442,'Oritel Service Apartment','Studio Road, Andheri East',3.6,48,0);
INSERT INTO Hotel VALUES(443,'Hotel Golden Tulipz','Military Road, Andheri East',3.4,48,0);
INSERT INTO Hotel VALUES(444,'Hotel Orange Inn','Makwana Road, Andheri East',3.4,48,0);
INSERT INTO Hotel VALUES(445,'Oyo Rooms','Ghatkopar Link Road, Andheri East',3.8,48,0);
INSERT INTO Hotel VALUES(446,'Hotel Hira Palace','Sleater Road, Grant Road',3.1,48,0);
INSERT INTO Hotel VALUES(447,'Hotel Capitol','Ghodbunder Road, Thane West',3.9,48,0);
INSERT INTO Hotel VALUES(448,'Hotel City Point','Dr Ambedkar Road, Dadar East',3.7,48,0);
INSERT INTO Hotel VALUES(449,'Hotel Mourya Residency Pvt Ltd','Platform No 2, Thane West',3.9,48,0);
INSERT INTO Hotel VALUES(450,'Mohan Palace Hotel','Kahajiar Road, Dalhousie Cantt',3.8,49,0);
INSERT INTO Hotel VALUES(451,'Super Star Hotel','Statue Chandra Bose, Dalhousie HO',4.7,49,0);
INSERT INTO Hotel VALUES(452,'Sagrika Resort','Court Road, Dalhousie HO',3.3,49,0);
INSERT INTO Hotel VALUES(453,'Hotel Dalhousie Heights','Near Bus Stand, Dalhousie Ho',3.6,49,0);
INSERT INTO Hotel VALUES(454,'Alps Resort','Khajjiar Road, Dalhousie Cantt',4.0,49,0);
INSERT INTO Hotel VALUES(455,'Shining Star Resort','Khajjiar, Dalhousie Ho',3.3,49,0);
INSERT INTO Hotel VALUES(456,'Kumars Hotel','Bus Stand Dalhousie, Dalhousie Ho',3.9,49,0);
INSERT INTO Hotel VALUES(457,'Hotel New Palace','Near Subhash Chowk, Dalhousie Ho',5.0,49,0);
INSERT INTO Hotel VALUES(458,'Grand View Hotel','Near Bus Stand, Dalhousie Ho',4.4,49,0);
INSERT INTO Hotel VALUES(459,'Aamod Resort','Khajjiar Road, Dalhousie Ho',4.2,49,0);
INSERT INTO Hotel VALUES(460,'Lotus Resort','Lotus Eco Village, Konark Ho',4.0,50,0);
INSERT INTO Hotel VALUES(461,'Sun Temple Hotel','Near Bus Stand, Konark Ho',0.0,50,0);
INSERT INTO Hotel VALUES(462,'Panthanivas Hotel','Konark HO',3.5,50,0);
INSERT INTO Hotel VALUES(463,'Konark Lodge','Konark HO',0.0,50,0);
INSERT INTO Hotel VALUES(464,'Yatrinivas hotels','Near Medical Chowk, Konark HO',3.9,50,0);
INSERT INTO Hotel VALUES(465,'Marwadi Hotel and Lodge','Ring Bus Stand, Konark Ho',0.0,50,0);
INSERT INTO Hotel VALUES(466,'Royal Lodge','Opposite Konark Temple, Konark HO',0.0,50,0);
INSERT INTO Hotel VALUES(467,'Banita Lodge','Konark HO',0.0,50,0);
INSERT INTO Hotel VALUES(468,'Tarini Lodge','Konark HO',0.0,50,0);
INSERT INTO Hotel VALUES(469,'Sun Tour & Travels','Near Sun Temple, Konark HO',4.0,50,0);
INSERT INTO Hotel VALUES(470,'Cidade De Daman','Devka Beach Road, Daman Ho',3.9,51,0);
INSERT INTO Hotel VALUES(471,'Hotel Sea Rock Inn','Devka Beach, Daman Ho',3.9,51,0);
INSERT INTO Hotel VALUES(472,'Hotel Hany Garden','Dabhel, Daman Ho',4.6,51,0);
INSERT INTO Hotel VALUES(473,'Hotel Shilton & Sohil Bar','Devka Beach, Nani Daman',3.9,51,0);
INSERT INTO Hotel VALUES(474,'Sagar Presidency Hotel','Near Tin Batti, Nani Daman',3.6,51,0);
INSERT INTO Hotel VALUES(475,'Hotel The Emerald','Sea Face Road, Daman Ho',4.1,51,0);
INSERT INTO Hotel VALUES(476,'Hotel Royal Garden','Vapi Daman Checkpost, Daman Ho',3.8,51,0);
INSERT INTO Hotel VALUES(477,'Hotel Sukh Sagar','Police Stattion, Nani Daman',3.7,51,0);
INSERT INTO Hotel VALUES(478,'Hotel Saikripa Imperial','Airport Road, Nani Daman',3.9,51,0);
INSERT INTO Hotel VALUES(479,'Hotel Sai Regency','Devka Road, Nani Daman',4.3,51,0);
INSERT INTO Hotel VALUES(480,'Hotel A P Palace','Lalbagh, Darbhanga Ho',4.1,52,0);
INSERT INTO Hotel VALUES(481,'Hotel IRA Palace','Gami Path, Darbhanga Ho',3.5,52,0);
INSERT INTO Hotel VALUES(482,'Hotel Beena Mansion','Hospital Road, Benta Chowk',4.8,52,0);
INSERT INTO Hotel VALUES(483,'Hotel Rama Residency','Laheriasarai, Benta South',4.5,52,0);
INSERT INTO Hotel VALUES(484,'Natraj Hotel','Tower Chowk, Darbhanga HO',3.5,52,0);
INSERT INTO Hotel VALUES(485,'Hotel Grand Sm Regency','MIRZAPUR CHOWK, Mirzapur',4.2,52,0);
INSERT INTO Hotel VALUES(486,'Hotel P& P International','Benta Hospital Road, Benta South',5.0,52,0);
INSERT INTO Hotel VALUES(487,'Hotel Ganga Only For Residence','Darbhanga, Darbhanga Ho',4.3,52,0);
INSERT INTO Hotel VALUES(488,'Durga Hotel','Bakarganj, Darbhanga Ho',4.0,52,0);
INSERT INTO Hotel VALUES(489,'Arvind Hotel','Tower Chowk, Darbhanga Ho',3.2,52,0);
INSERT INTO Hotel VALUES(490,'Hotel  Shail Raj','Vpo Nagwain, Kullu H O',4.3,53,0);
INSERT INTO Hotel VALUES(491,'Hotel Samrat','Mall Road, Kullu H O',3.5,53,0);
INSERT INTO Hotel VALUES(492,'Sangam Hotel','Mani Karan, Kullu H O',4.2,53,0);
INSERT INTO Hotel VALUES(493,'Hotel Rishi Palace','Near Gayatri Temple, Jagatsukh',3.5,53,0);
INSERT INTO Hotel VALUES(494,'Himalyan Kothikais','Post Office, Kullu H O',3.5,53,0);
INSERT INTO Hotel VALUES(495,'Apple Valley Resorts','Nh 21, Mohal',4.4,53,0);
INSERT INTO Hotel VALUES(496,'Hotel Shail Raj','Vpo: Nagwain, Kullu H O',3.5,53,0);
INSERT INTO Hotel VALUES(497,'Himalayan Hamlet Valley View','Nath, Kullu H O',3.7,53,0);
INSERT INTO Hotel VALUES(498,'Alpine Guest House','6 Km, Kullu H O',4.0,53,0);
INSERT INTO Hotel VALUES(499,'Span Resort & Spa','Kullu Manali Highway, Katrain',4.6,53,0);
INSERT INTO Hotel VALUES(500,'Lava Vews','Lava',4.0,54,0);
INSERT INTO Hotel VALUES(501,'Summit Hotels & Resorts','Jalpahar, Darjeeling H O',3.6,54,0);
INSERT INTO Hotel VALUES(502,'Hindustan Residency','R DAS Road, Darjeeling Bazar',3.5,54,0);
INSERT INTO Hotel VALUES(503,'Krishna Residency Service A...','Lebong Cart, Darjeeling H O',4.2,54,0);
INSERT INTO Hotel VALUES(504,'Roma Holiday INN','Gandhi Road, Darjeeling Bazar',4.4,54,0);
INSERT INTO Hotel VALUES(505,'The Janani Villa Hotel','Kutchery Road, Darjeeling Bazar',5.0,54,0);
INSERT INTO Hotel VALUES(506,'Dil Hotel','Rock Vill, Darjeeling H O',3.0,54,0);
INSERT INTO Hotel VALUES(507,'Mayfair Hotels & Resorts','Opposite Governer, Darjeeling H O',4.6,54,0);
INSERT INTO Hotel VALUES(508,'Sonar Bangla Hotel','Robertson Road, Darjeeling H O',4.2,54,0);
INSERT INTO Hotel VALUES(509,'Elgin Hotel','D Lama, Darjeeling H O',4.1,54,0);
INSERT INTO Hotel VALUES(510,'Hotel Daichi','Astley Marg, Dehradun GPO',3.7,55,0);
INSERT INTO Hotel VALUES(511,'Softel Plaza Hotel','Road, Subhash Nagar Dehradun',4.0,55,0);
INSERT INTO Hotel VALUES(512,'M J Residency Hotel','Haridwar Road, Dehradun GPO',4.2,55,0);
INSERT INTO Hotel VALUES(513,'Moti Mahal Hotel & Hotel','Rajpur Road, Dehradun City',4.0,55,0);
INSERT INTO Hotel VALUES(514,'The Solitaire Hotel','Bypass Road, Dehradun City',4.1,55,0);
INSERT INTO Hotel VALUES(515,'Manadakini Hotels Pvt Ltd','Haridwar Road, Dehradun City',3.6,55,0);
INSERT INTO Hotel VALUES(516,'Hotel Padmini Palace','Air Port Dehradun., Dehradun City',4.4,55,0);
INSERT INTO Hotel VALUES(517,'Hotel Jsr Inn','Galjwari, Garhi Cantt',5.0,55,0);
INSERT INTO Hotel VALUES(518,'Hotel Grand','Gandhi Road, Dehradun City',2.8,55,0);
INSERT INTO Hotel VALUES(519,'Shivam Residency','Railway Station, Dehradun City',3.9,55,0);
INSERT INTO Hotel VALUES(520,'Hotel Samrat','Gurudwara Road, Gurgaon',3.6,56,0);
INSERT INTO Hotel VALUES(521,'Zo Rooms','Ram Nagar-Paharganj',3.7,56,0);
INSERT INTO Hotel VALUES(522,'Oyo Rooms','Dlf City Phase I Gurgaon',4.0,56,0);
INSERT INTO Hotel VALUES(523,'Oyo Rooms','Bharat Nagar-Friends Colony East',3.8,56,0);
INSERT INTO Hotel VALUES(524,'Casa2inns','Channa Mkt, Karol Bagh',3.5,56,0);
INSERT INTO Hotel VALUES(525,'Clark Heights Hotel','Metro Pillar, West Patel Nagar',3.9,56,0);
INSERT INTO Hotel VALUES(526,'Hotel Formule1','Commercial, Gurgaon Sector 50',3.2,56,0);
INSERT INTO Hotel VALUES(527,'Oyo Rooms','Dnd Road, Noida Sector 22',3.8,56,0);
INSERT INTO Hotel VALUES(528,'Hotel Diplomat Residency','Lajpat Nagar 3-Lajpat Nagar',3.9,56,0);
INSERT INTO Hotel VALUES(529,'JMD Residency','Dlf City Phase I Gurgaon',4.1,56,0);
INSERT INTO Hotel VALUES(530,'Hotel Jyoti','Ratan Bakshi, B Deoghar HO',2.3,57,0);
INSERT INTO Hotel VALUES(531,'Hotel Baidyanath','Castair, B Deoghar Ho',3.6,57,0);
INSERT INTO Hotel VALUES(532,'Amrapali Clarks Inn','R Baxi, B Deoghar Ho',3.6,57,0);
INSERT INTO Hotel VALUES(533,'Hotel Mahadev Palace','Castair Town, B Deoghar Ho',3.8,57,0);
INSERT INTO Hotel VALUES(534,'Hotel Madhumala International','R Bakshi, B Deoghar Ho',0.0,57,0);
INSERT INTO Hotel VALUES(535,'Hotel Yatrik','Tower Chowk, B Deoghar Ho',3.6,57,0);
INSERT INTO Hotel VALUES(536,'Hotel Relax','LAL Chakravorty, B Deoghar Ho',3.5,57,0);
INSERT INTO Hotel VALUES(537,'Hotel Rajkamal','Dham Station, B Deoghar Ho',4.0,57,0);
INSERT INTO Hotel VALUES(538,'Hotel Maharaja','M Jalan, B Deoghar Ho',0.0,57,0);
INSERT INTO Hotel VALUES(539,'Cocoon Luxury Business Hotel','Near Railway Station, Dhanbad HO',4.4,58,0);
INSERT INTO Hotel VALUES(540,'Seventeen Degrees Hotel Co ...','Ashok Nagar, Dhansar',4.2,58,0);
INSERT INTO Hotel VALUES(541,'Sonotel Hotels & Resort Pvt...','Dhanbad Link Road, Saraidhela',4.4,58,0);
INSERT INTO Hotel VALUES(542,'Hotel Kuber','L C Road, Dhanbad Ho',4.1,58,0);
INSERT INTO Hotel VALUES(543,'Hotel Rainbow Regency','Bank More Road, Bank More',4.5,58,0);
INSERT INTO Hotel VALUES(544,'Hotel Bridge View','Main Road, Naya Bazar',4.7,58,0);
INSERT INTO Hotel VALUES(545,'Hotel Black Rock','Jhariya Road, Bank More',4.2,58,0);
INSERT INTO Hotel VALUES(546,'Skylark Hotels Pvt Ltd','Bank More, Shastri Nagar',4.3,58,0);
INSERT INTO Hotel VALUES(547,'Madhulika Hotel','Tiwari Gali, Dhanbad Ho',4.1,58,0);
INSERT INTO Hotel VALUES(548,'Dhanbad Club Limited','Luby Circular Road, Dhanbad HO',3.9,58,0);
INSERT INTO Hotel VALUES(549,'Omni Hotel','Distt. Kangra, Mcleod Ganj',4.3,59,0);
INSERT INTO Hotel VALUES(550,'Greenwoods Inn','Dharamkot Road, Mcleod Ganj',3.8,59,0);
INSERT INTO Hotel VALUES(551,'Hotel Pink White','Bhagsunag, Dharamsala',3.3,59,0);
INSERT INTO Hotel VALUES(552,'Hotel The Oak Valley','Near Wast Warrior, Mcleod Ganj',3.6,59,0);
INSERT INTO Hotel VALUES(553,'HOTEL DEV COTTAGE','Dharamkot Road, Mcleod Ganj',3.5,59,0);
INSERT INTO Hotel VALUES(554,'New Varuni House','Dalai Lama Temple, Mcleod Ganj',5.0,59,0);
INSERT INTO Hotel VALUES(555,'Sahiwa Hotel','Temple Road, Dharamshala Ho',3.0,59,0);
INSERT INTO Hotel VALUES(556,'Pristine Retreat Resort','stawberry hill, Dal Lake',3.5,59,0);
INSERT INTO Hotel VALUES(557,'Grand Hill Hotel','Lama Temple Road, Mcleod Ganj',4.0,59,0);
INSERT INTO Hotel VALUES(558,'THE LODGE','Po Bhagsunag, Mcleod Ganj',3.5,59,0);
INSERT INTO Hotel VALUES(559,'Hotel Park View','Opal Grounder Park, Dharmapuri Ho',4.9,60,0);
INSERT INTO Hotel VALUES(560,'Hotel Sri Rama','Bye Pass Road, Dharmapuri Ho',3.9,60,0);
INSERT INTO Hotel VALUES(561,'Tamilnadu Hotel','Hogenakkal',4.0,60,0);
INSERT INTO Hotel VALUES(562,'Adhiyamaan Palace Hotel','Bye Pass Road, Dharmapuri Ho',4.0,60,0);
INSERT INTO Hotel VALUES(563,'Dnc Lodging House','Goundesr Street, Dharmapuri Ho',4.0,60,0);
INSERT INTO Hotel VALUES(564,'Sri Saravana Inn','By Pass Raod, Dharmapuri Ho',3.7,60,0);
INSERT INTO Hotel VALUES(565,'Dng Residency','Bye Pass Road, Dharmapuri Ho',3.3,60,0);
INSERT INTO Hotel VALUES(566,'M S Lodging','Hogenakkal, Hogenakkal',2.0,60,0);
INSERT INTO Hotel VALUES(567,'DNG Lodging House','Chetty Street, Dharmapuri Ho',3.6,60,0);
INSERT INTO Hotel VALUES(568,'Hotel Rajeet','Holiday Home, Digha New Township',3.7,61,0);
INSERT INTO Hotel VALUES(569,'Amantran Hotel & Resorts','Ghersai Road, Digha',4.2,61,0);
INSERT INTO Hotel VALUES(570,'J P Resort','Digha Picnic, Digha New Township',4.1,61,0);
INSERT INTO Hotel VALUES(571,'Hotel Aamar Digha','Medinipur, Digha New Township',3.4,61,0);
INSERT INTO Hotel VALUES(572,'Hotel Debloke','New Digha Mail Road, Digha',4.0,61,0);
INSERT INTO Hotel VALUES(573,'Hotel Kanchan International','Near Shoni, Digha New Township',3.5,61,0);
INSERT INTO Hotel VALUES(574,'Hotel Sun And Swad Palace','Shibalaya Road, Digha',3.5,61,0);
INSERT INTO Hotel VALUES(575,'Hotel Snehamaya','Shibalaya Road, Digha',5.0,61,0);
INSERT INTO Hotel VALUES(576,'Sea Beach Villa','Kanika, Digha New Township',5.0,61,0);
INSERT INTO Hotel VALUES(577,'Hotel Cosy INN','Barrister Colony Road, Digha',3.5,61,0);
INSERT INTO Hotel VALUES(578,'Hotel Apaar','Government Parking, Diu Ho',3.6,62,0);
INSERT INTO Hotel VALUES(579,'Apana Hotel','Opposite Seashore, Diu Ho',3.6,62,0);
INSERT INTO Hotel VALUES(580,'Hotel Palacio De Diu','Parsiwada, Diu Ho',4.6,62,0);
INSERT INTO Hotel VALUES(581,'Prabhat Beach Resort','Wanakbara Road, Diu Ho',3.0,62,0);
INSERT INTO Hotel VALUES(582,'Hotel Gangeshwar','Main Bazar, Diu',4.2,62,0);
INSERT INTO Hotel VALUES(583,'Hotel Maheshwari Deven Bar ...','Chandwad, Diu Ho',2.5,62,0);
INSERT INTO Hotel VALUES(584,'Hotel Krishna Park Resort Diu','Nagva Beach Road, Diu Ho',3.6,62,0);
INSERT INTO Hotel VALUES(585,'Star Paying Guest House','Main Bazar Road, Diu Ho',3.5,62,0);
INSERT INTO Hotel VALUES(586,'Hotel Khushi International','Bundar Chowk, Diu Ho',3.0,62,0);
INSERT INTO Hotel VALUES(587,'Seaview Beach Resort','Ghogla Beach, Diu Ho',3.7,62,0);
INSERT INTO Hotel VALUES(588,'Vishwas Yatrik Bhavan','Okha Highway, Dwarka Town',4.1,63,0);
INSERT INTO Hotel VALUES(589,'Nova Hotels','Rajputpara Main Road, Dwarka HO',5.0,63,0);
INSERT INTO Hotel VALUES(590,'The Dwarika Hotel','Jamnagar Road, Dwarka Ho',3.8,63,0);
INSERT INTO Hotel VALUES(591,'Hotel Shivam','Railway Station Road, Dwarka Ho',5.0,63,0);
INSERT INTO Hotel VALUES(592,'Hotel Krishna Inn','8e National Highway, Dwarka Ho',3.0,63,0);
INSERT INTO Hotel VALUES(593,'Hotel Dwarka Residency','Near Iskon Gate, Dwarka Ho',4.0,63,0);
INSERT INTO Hotel VALUES(594,'Hotel Rudra Plaza','Aaditya Road, Dwarka Ho',3.8,63,0);
INSERT INTO Hotel VALUES(595,'Hotel Radhe','Okha, Dwarka Ho',5.0,63,0);
INSERT INTO Hotel VALUES(596,'Hotel Sky','Jodha Manek Road, Dwarka Ho',3.5,63,0);
INSERT INTO Hotel VALUES(597,'Dwarkadish Lords Eco Inn','Near Gayatri Temple, Dwarka HO',4.1,63,0);
INSERT INTO Hotel VALUES(598,'Hotel Galaxy Avenue','G M Road, Chembur West',3.4,64,0);
INSERT INTO Hotel VALUES(599,'Oritel Service Apartment','Studio Road, Andheri East',3.6,64,0);
INSERT INTO Hotel VALUES(600,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,64,0);
INSERT INTO Hotel VALUES(601,'Hotel Golden Tulipz','Military Road, Andheri East',3.4,64,0);
INSERT INTO Hotel VALUES(602,'Hotel Orange Inn','Makwana Road, Andheri East',3.4,64,0);
INSERT INTO Hotel VALUES(603,'Oyo Rooms','Ghatkopar Link Road, Andheri East',3.8,64,0);
INSERT INTO Hotel VALUES(604,'Hotel Capitol','Ghodbunder Road, Thane West',3.9,64,0);
INSERT INTO Hotel VALUES(605,'Hotel Hira Palace','Sleater Road, Grant Road',3.1,64,0);
INSERT INTO Hotel VALUES(606,'Hotel City Point','Dr Ambedkar Road, Dadar East',3.7,64,0);
INSERT INTO Hotel VALUES(607,'Landmark Fort Hotel','P D Mello Road, Fort',3.8,64,0);
INSERT INTO Hotel VALUES(608,'The Orbit Retreat','I.M.S. Road, Giridih HO',4.4,65,0);
INSERT INTO Hotel VALUES(609,'Hotel Ashoka International','Gandhi Chowk, Giridih Ho',4.7,65,0);
INSERT INTO Hotel VALUES(610,'Hotel Galy International','Court Road, Giridih Ho',3.9,65,0);
INSERT INTO Hotel VALUES(611,'Hotel Vrindavan Palace','Barmasiya, Giridih Ho',5.0,65,0);
INSERT INTO Hotel VALUES(612,'Hotel Mansarovar','Tundi Road, Giridih Ho',4.3,65,0);
INSERT INTO Hotel VALUES(613,'Sapna Hotel','Near Madhuban, Shikherjee',3.0,65,0);
INSERT INTO Hotel VALUES(614,'Ranjeet Rest House','Court Road, Giridih Ho',0.0,65,0);
INSERT INTO Hotel VALUES(615,'Malda Rest House','Buxidih Road, Giridih Ho',0.0,65,0);
INSERT INTO Hotel VALUES(616,'Ranjit Rest House','Kachehari Road, Giridih Ho',0.0,65,0);
INSERT INTO Hotel VALUES(617,'Swagat Hotel','Kali Mandir Road, Giridih Ho',0.0,65,0);
INSERT INTO Hotel VALUES(618,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,66,0);
INSERT INTO Hotel VALUES(619,'Hotel Golden Tulipz','Military Road, Andheri East',3.4,66,0);
INSERT INTO Hotel VALUES(620,'Hotel Orange Inn','Makwana Road, Andheri East',3.4,66,0);
INSERT INTO Hotel VALUES(621,'Oyo Rooms','Ghatkopar Link Road, Andheri East',3.8,66,0);
INSERT INTO Hotel VALUES(622,'Hotel Hira Palace','Sleater Road, Grant Road',3.1,66,0);
INSERT INTO Hotel VALUES(623,'Hotel Capitol','Ghodbunder Road, Thane West',3.9,66,0);
INSERT INTO Hotel VALUES(624,'Hotel City Point','Dr Ambedkar Road, Dadar East',3.7,66,0);
INSERT INTO Hotel VALUES(625,'Landmark Fort Hotel','P D Mello Road, Fort',3.8,66,0);
INSERT INTO Hotel VALUES(626,'Hotel Mourya Residency Pvt Ltd','Platform No 2, Thane West',3.9,66,0);
INSERT INTO Hotel VALUES(627,'Hotel Nice','Station Road, Goregaon West',3.5,66,0);
INSERT INTO Hotel VALUES(628,'Sanskruti Quality Resort','Om Beach Road, Gokarna',3.5,67,0);
INSERT INTO Hotel VALUES(629,'Namaste Cafe','Near Om Beach, Gokarna',4.1,67,0);
INSERT INTO Hotel VALUES(630,'Swaswara Resort','Doribail, Gokarna',3.9,67,0);
INSERT INTO Hotel VALUES(631,'Shri Jagdish Nivas Guest House','Milenikeri, Gokarna',0.0,67,0);
INSERT INTO Hotel VALUES(632,'Savitri Guest House','Car Street, Gokarna',0.0,67,0);
INSERT INTO Hotel VALUES(633,'Shastri Guest House','Dasan Matt, Gokarna',2.0,67,0);
INSERT INTO Hotel VALUES(634,'Vaibhav Nivas','Off Main St, Gokarna',0.0,67,0);
INSERT INTO Hotel VALUES(635,'Nimmu House','Kumta Taluk, Gokarna',5.0,67,0);
INSERT INTO Hotel VALUES(636,'Jaya Laxmi Guest House','Main Road, Gokarna',0.0,67,0);
INSERT INTO Hotel VALUES(637,'New Prasad Nilaya','Ganjigadde, Gokarna',3.8,67,0);
INSERT INTO Hotel VALUES(638,'Hotel R R Grand','Near LIC Building, Daba Gardens',3.8,68,0);
INSERT INTO Hotel VALUES(639,'Sree Residency','Gantasala Road, Daba Gardens',3.3,68,0);
INSERT INTO Hotel VALUES(640,'Landmark Hotel','Sangeeth Theater, Daba Gardens',5.0,68,0);
INSERT INTO Hotel VALUES(641,'Hotel Seacity Grand','Maddilpalem, Shivajipalem',3.8,68,0);
INSERT INTO Hotel VALUES(642,'NSNR Residency','Rockdale Layout, Ram Nagar',4.8,68,0);
INSERT INTO Hotel VALUES(643,'Poorna Vedika A/C Function ...','Two Town, Poorna Market',3.5,68,0);
INSERT INTO Hotel VALUES(644,'Hotel Jyothi Swaroopa','Dwaraka Nagar Visakhapatnam',4.3,68,0);
INSERT INTO Hotel VALUES(645,'Vijayabhanu Hotel','Junction, Jagadamba Centre',4.0,68,0);
INSERT INTO Hotel VALUES(646,'Hotel Winsar Park','Office Road, Maharanipeta',4.7,68,0);
INSERT INTO Hotel VALUES(647,'Mv Boutique Hotel Ac','Main Road, Gajuwaka',3.8,68,0);
INSERT INTO Hotel VALUES(648,'The Khyber Himalayan Resort & Spa','Gulmarg',4.2,69,0);
INSERT INTO Hotel VALUES(649,'The Vintage','Circular Road, Gulmarg',4.3,69,0);
INSERT INTO Hotel VALUES(650,'Hill Top Hotel','Near Gondola, Gulmarg',3.9,69,0);
INSERT INTO Hotel VALUES(651,'Heevan Retreat Hotel','Heevan Retreats Road, Gulmarg',3.7,69,0);
INSERT INTO Hotel VALUES(652,'Royal Park Hotel','Srinagar Rd, Gulmarg',4.6,69,0);
INSERT INTO Hotel VALUES(653,'Grand Mumtaz Resorts','Near Gondola Ride, Gulmarg',3.7,69,0);
INSERT INTO Hotel VALUES(654,'Hotel Pine Spring','Gulmarg',4.5,69,0);
INSERT INTO Hotel VALUES(655,'The Meadows','Next To Pine Palace, Gulmarg',0.0,69,0);
INSERT INTO Hotel VALUES(656,'Alpine Ridge Hotel','Khelan Mg, Gulmarg',4.0,69,0);
INSERT INTO Hotel VALUES(657,'Gulmarg Resorts','Near Gondola Cable Car, Gulmarg',3.8,69,0);
INSERT INTO Hotel VALUES(658,'Ashwini Hotel','Thakkar Road, Dadar West',3.5,70,0);
INSERT INTO Hotel VALUES(659,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,70,0);
INSERT INTO Hotel VALUES(660,'Ace Residency','Military Road, Andheri East',3.6,70,0);
INSERT INTO Hotel VALUES(661,'Stay In','Sakhi Vhiar Road, Sakinaka',4.3,70,0);
INSERT INTO Hotel VALUES(662,'The Resort','Madh-Marve Road, Malad West',4.0,70,0);
INSERT INTO Hotel VALUES(663,'Hotel Royal Park','Andheri Kurla Road, Andheri East',3.8,70,0);
INSERT INTO Hotel VALUES(664,'Hotel Planet Plaza','Andheri Kurla Road, Andheri East',3.6,70,0);
INSERT INTO Hotel VALUES(665,'The Regenza By Tunga','Sector 30 A, Vashi',4.1,70,0);
INSERT INTO Hotel VALUES(666,'Martins Inn Beach Hotel','Arnala, Virar West',3.7,70,0);
INSERT INTO Hotel VALUES(667,'Oritel Service Apartment','Studio Road, Andheri East',3.6,70,0);
INSERT INTO Hotel VALUES(668,'Hotel Sita Manor','Gandhi Road, Gwalior Ho',3.9,71,0);
INSERT INTO Hotel VALUES(669,'Hotel Silver Oak','Green Garden Road, Gwalior City',3.5,71,0);
INSERT INTO Hotel VALUES(670,'Hotel Mayur','Station Road, Gwalior R S',3.2,71,0);
INSERT INTO Hotel VALUES(671,'The Bellevue','Patel Nagar, City Centre',4.8,71,0);
INSERT INTO Hotel VALUES(672,'Hotel Golden Square','Roxypull Road, Lashkar',3.0,71,0);
INSERT INTO Hotel VALUES(673,'Vaishnodham','Tansen Road, Gwalior R S',5.0,71,0);
INSERT INTO Hotel VALUES(674,'Hotel Regency Square','City Center, Gwalior Ho',3.7,71,0);
INSERT INTO Hotel VALUES(675,'Hotel City Palace','Jayendraganj, Lashkar',3.6,71,0);
INSERT INTO Hotel VALUES(676,'Hotel Gwalior Pride','Hazira Chauraha, Hazira Chowk',2.0,71,0);
INSERT INTO Hotel VALUES(677,'Hotel Ambassador','Zinsi Road No 1, Lashkar',3.2,71,0);
INSERT INTO Hotel VALUES(678,'Hotel Rock Regency','Shankaragudda Colony, Hampi',3.8,72,0);
INSERT INTO Hotel VALUES(679,'Hotel Shanbhag International','College Road, Patel Nagar',3.9,72,0);
INSERT INTO Hotel VALUES(680,'Hotel Hampi International P...','No.175/177, Station Road',3.8,72,0);
INSERT INTO Hotel VALUES(681,'Hotel Hampi Lotus','Sp Road, HOspet HO',2.8,72,0);
INSERT INTO Hotel VALUES(682,'Bilwa Residency','Axis Bank Complex, College Road',2.0,72,0);
INSERT INTO Hotel VALUES(683,'Rainbow Residency','Mallige Cross, Hampi Road',2.0,72,0);
INSERT INTO Hotel VALUES(684,'Sri Sai Lakshmi Residency','Shiva Talkies Road, Hampi',3.5,72,0);
INSERT INTO Hotel VALUES(685,'Rayyan Lodge','No.416, Hospet Ho',4.3,72,0);
INSERT INTO Hotel VALUES(686,'Amrutha Residency','Sri Ramalu Park, Station Road',4.5,72,0);
INSERT INTO Hotel VALUES(687,'Pai Group Of Lodges','Shanbhag Circle, College Road',4.4,72,0);
INSERT INTO Hotel VALUES(688,'Hotel Himalaya','Pull Railway, Haridwar H O',3.7,73,0);
INSERT INTO Hotel VALUES(689,'Hotel Hari Heritage','Haridwar Rishikesh, Haridwar H O',3.9,73,0);
INSERT INTO Hotel VALUES(690,'Hotel Gagandeep','Behind PNB, Haridwar H O',4.5,73,0);
INSERT INTO Hotel VALUES(691,'Hotel Anuradha Palace','Rishikesh Road, Haridwar H O',3.5,73,0);
INSERT INTO Hotel VALUES(692,'Hotel Basera','Jassa Ram, Haridwar H O',3.7,73,0);
INSERT INTO Hotel VALUES(693,'Hotel City Park','Rishikul Bus, Haridwar H O',3.0,73,0);
INSERT INTO Hotel VALUES(694,'Hotel Vikas','Har Ki, Haridwar H O',4.5,73,0);
INSERT INTO Hotel VALUES(695,'Hotel Chitra Heritage','Chitra Cinema, Haridwar H O',3.5,73,0);
INSERT INTO Hotel VALUES(696,'Hotel Raj Deluxe','Bhalla road, Haridwar H O',4.0,73,0);
INSERT INTO Hotel VALUES(697,'Hotel La Casa','Ki Pauri, Haridwar H O',3.7,73,0);
INSERT INTO Hotel VALUES(698,'Mallige Residency','School Feild, Kr Puram Hassan',4.1,74,0);
INSERT INTO Hotel VALUES(699,'Hotel Kadamba Comforts','Opposite Vysya Bank, Bm Road',3.9,74,0);
INSERT INTO Hotel VALUES(700,'Hotel Palika','Race, Race Course Road Hassan',4.1,74,0);
INSERT INTO Hotel VALUES(701,'Pavanputra Resort And Sport...','N Pura Road, Hassan Ho',3.0,74,0);
INSERT INTO Hotel VALUES(702,'Hotel Apoorva Boarding And ...','Maharaja Park Road, Hassan Ho',3.6,74,0);
INSERT INTO Hotel VALUES(703,'Hotel Mayura Internation','B M Road, Bm Road',3.9,74,0);
INSERT INTO Hotel VALUES(704,'HOTEL RAAMA','B M Road, Gandhi Bazaar',4.6,74,0);
INSERT INTO Hotel VALUES(705,'Prakruthi Holidays Pvt Ltd.,','Opp, Race Course Road Hassan',3.5,74,0);
INSERT INTO Hotel VALUES(706,'Hotel Chiranth Lodging And ...','Kasturiba Road, Hassan Ho',3.9,74,0);
INSERT INTO Hotel VALUES(707,'Hulikallu The Malnad Planta...','Nelagahally, Sakleshpur',5.0,74,0);
INSERT INTO Hotel VALUES(708,'Hotel Vanya Vilas Pvt Ltd','33 Ranchi-Patna, Hazaribagh H O',3.8,75,0);
INSERT INTO Hotel VALUES(709,'Hotel Samrat Inn','Kunwar Singh, Hazaribagh H O',4.3,75,0);
INSERT INTO Hotel VALUES(710,'Hotel Shree Vinayak','Matwari Road, Hazaribagh H O',0.0,75,0);
INSERT INTO Hotel VALUES(711,'MAA Ambey Hotel','Hazaribag City, Hazaribagh H O',4.1,75,0);
INSERT INTO Hotel VALUES(712,'Hotel Rahim','Hazaribagh Main, Hazaribagh H O',0.0,75,0);
INSERT INTO Hotel VALUES(713,'Hotel Satkar Rest House','G S, Hazaribagh H O',0.0,75,0);
INSERT INTO Hotel VALUES(714,'Neel Kamal Lodge','Hazaribagh H O',0.0,75,0);
INSERT INTO Hotel VALUES(715,'Hotel Guru Nanak Palace','Old Bus, Hazaribagh H O',2.0,75,0);
INSERT INTO Hotel VALUES(716,'Hotel Peacock','Dhanbad Road, Hazaribagh H O',0.0,75,0);
INSERT INTO Hotel VALUES(717,'Hotel Park View','Opal Grounder Park, Dharmapuri Ho',4.9,76,0);
INSERT INTO Hotel VALUES(718,'Tamilnadu Hotel','Hogenakkal',4.0,76,0);
INSERT INTO Hotel VALUES(719,'M S Lodging','Hogenakkal, Hogenakkal',2.0,76,0);
INSERT INTO Hotel VALUES(720,'C M Hotel','New Bus Stand, Hogenakkal',3.9,76,0);
INSERT INTO Hotel VALUES(721,'K.M. Lodge','Bus Stand, Hogenakkal',2.5,76,0);
INSERT INTO Hotel VALUES(722,'VST Lodge','Opp-Bus Stand, Hogenakkal',0.0,76,0);
INSERT INTO Hotel VALUES(723,'Sri Arul Lodge','Dharmapuri, Hogenakkal',0.0,76,0);
INSERT INTO Hotel VALUES(724,'Green Falls Lodge','Dharmapuri, Hogenakkal',0.0,76,0);
INSERT INTO Hotel VALUES(725,'K.C. Lodge','Dharmapuri, Hogenakkal',0.0,76,0);
INSERT INTO Hotel VALUES(726,'Wanton House','Sector 26/ A, Vashi',3.5,77,0);
INSERT INTO Hotel VALUES(727,'Hotel Jawahar','Cross Hospital, Ulhasnagar No 3',3.9,77,0);
INSERT INTO Hotel VALUES(728,'Krishna Avtar Stay Inn','Palm Beach Road, Cbd Belapur',4.1,77,0);
INSERT INTO Hotel VALUES(729,'Ace Residency','Military Road, Andheri East',3.6,77,0);
INSERT INTO Hotel VALUES(730,'Stay In','Sakhi Vhiar Road, Sakinaka',4.3,77,0);
INSERT INTO Hotel VALUES(731,'The Resort','Madh-Marve Road, Malad West',4.0,77,0);
INSERT INTO Hotel VALUES(732,'Hotel Royal Park','Andheri Kurla Road, Andheri East',3.8,77,0);
INSERT INTO Hotel VALUES(733,'Hotel Planet Plaza','Andheri Kurla Road, Andheri East',3.6,77,0);
INSERT INTO Hotel VALUES(734,'The Regenza By Tunga','Sector 30 A, Vashi',4.1,77,0);
INSERT INTO Hotel VALUES(735,'Martins Inn Beach Hotel','Arnala, Virar West',3.7,77,0);
INSERT INTO Hotel VALUES(736,'Oyo Rooms','Gandhi Nagar, Hyderabad Gpo',3.2,78,0);
INSERT INTO Hotel VALUES(737,'Central Court Hotel','Lakdi Ka Pool-Khairatabad',3.9,78,0);
INSERT INTO Hotel VALUES(738,'Hotel One Place','Kphb Bus Stop, KPHB Colony',3.9,78,0);
INSERT INTO Hotel VALUES(739,'Serenity Inn','Kavuri Hills, Madhapur',3.8,78,0);
INSERT INTO Hotel VALUES(740,'Skyla Serviced Apartments','Avenue 4, Banjara Hills',4.2,78,0);
INSERT INTO Hotel VALUES(741,'Hotel Silver Park','Dharam Karam Road, Ameerpet',3.7,78,0);
INSERT INTO Hotel VALUES(742,'18 Square Lake View Boutique','Nectar Garden Gate, Madhapur',4.3,78,0);
INSERT INTO Hotel VALUES(743,'Horizon Residency','Society Main Road, Madhapur',3.8,78,0);
INSERT INTO Hotel VALUES(744,'Athithi Inn','Monster.Com Building, Ameerpet',3.9,78,0);
INSERT INTO Hotel VALUES(745,'Hotel Central Park','Old Mla Qtrs Road, Hyderguda',3.9,78,0);
INSERT INTO Hotel VALUES(746,'Samdariya Inn Hotel','Chowk, Napier Town Jabalpur',3.9,79,0);
INSERT INTO Hotel VALUES(747,'Hotel Vijan Palace','Karamchand Chowk, Jabalpur City',4.0,79,0);
INSERT INTO Hotel VALUES(748,'The Penthouse','Gwarighat Road, Jabalpur City',3.5,79,0);
INSERT INTO Hotel VALUES(749,'Hotel Rahul','Bridge, Napier Town Jabalpur',3.6,79,0);
INSERT INTO Hotel VALUES(750,'Hotel Maruti Mandapam','Nagpur Road, Jabalpur Garha',3.7,79,0);
INSERT INTO Hotel VALUES(751,'Hotel Suryaa','Beside Bus Stand, Jabalpur Ho',3.7,79,0);
INSERT INTO Hotel VALUES(752,'Hotel Wardhman','Chowk, Napier Town Jabalpur',4.5,79,0);
INSERT INTO Hotel VALUES(753,'Hotel Shubhkamna','Opposite Garrison Ground, Sadar',5.0,79,0);
INSERT INTO Hotel VALUES(754,'Hotel Grace Home','Station Road, Jabalpur City',4.0,79,0);
INSERT INTO Hotel VALUES(755,'White Pearl','Gulathi Petrol Pump, Madan Mahal',3.5,79,0);
INSERT INTO Hotel VALUES(756,'Hotel Devansh Residency','Kasturba Marg, Jagdalpur Ho',4.2,80,0);
INSERT INTO Hotel VALUES(757,'Hotel Laxman Avenue','Murthy Line Road, Jagdalpur Ho',3.8,80,0);
INSERT INTO Hotel VALUES(758,'Hotel Akanksha','Motitalab Para, Jagdalpur HO',3.8,80,0);
INSERT INTO Hotel VALUES(759,'Naman Bastar A Resort','Chitrakote Road, Jagdalpur HO',4.1,80,0);
INSERT INTO Hotel VALUES(760,'Hotel Ashoka','New Bus Stand, Jagdalpur HO',3.3,80,0);
INSERT INTO Hotel VALUES(761,'Rainbow Hotel','Palace Road, Jagdalpur HO',2.0,80,0);
INSERT INTO Hotel VALUES(762,'Hotel Suri International','Geedam Road, Jagdalpur Ho',3.5,80,0);
INSERT INTO Hotel VALUES(763,'Ganpati Resorts','Dhurkoda Road, Jagdalpur HO',3.2,80,0);
INSERT INTO Hotel VALUES(764,'Hotel Pankaj Palace','Main Road, Jagdalpur HO',4.0,80,0);
INSERT INTO Hotel VALUES(765,'Bastar Jungle Resort','Dist - Bastar, Jagdalpur HO',5.0,80,0);
INSERT INTO Hotel VALUES(766,'Oasis Home Stay','Tank Road, Malviya Nagar',4.0,81,0);
INSERT INTO Hotel VALUES(767,'Golden Hotel','Station Road, Jaipur',3.4,81,0);
INSERT INTO Hotel VALUES(768,'Devraj Niwas','Khasa Kothi Crossing, Bani Park',4.3,81,0);
INSERT INTO Hotel VALUES(769,'WelcomHeritage traditional ...','JAI Singh Highway, Bani Park',4.3,81,0);
INSERT INTO Hotel VALUES(770,'Umaid Bhawan Hotel','Behind Collectorate, Bani Park',4.4,81,0);
INSERT INTO Hotel VALUES(771,'Hotel Sarang Palace','Peetal Factory, Subhash Nagar',3.5,81,0);
INSERT INTO Hotel VALUES(772,'Gitanjali Luxury Suites & V...','Pawan Path, Vaishali Nagar',4.7,81,0);
INSERT INTO Hotel VALUES(773,'Golden Hotel','Polovictory, Station Road Jaipur',3.8,81,0);
INSERT INTO Hotel VALUES(774,'Hotel Golden Oak','Near Ahinsa Circle, C Scheme',3.9,81,0);
INSERT INTO Hotel VALUES(775,'Hotel City Home','No  4, Raja Park',4.6,81,0);
INSERT INTO Hotel VALUES(776,'Wild Desert Resort A Unit O...','Ki Haveli Road, Jaisalmer Ho',4.3,82,0);
INSERT INTO Hotel VALUES(777,'Wild Desert Resort A Unit O...','Plaza SAM Desert, Jaisalmer Ho',4.3,82,0);
INSERT INTO Hotel VALUES(778,'Hotel Priya','Collector Office, Jaisalmer Ho',3.7,82,0);
INSERT INTO Hotel VALUES(779,'Hotel Royal Haveli','Air Force Circle, Jaisalmer Ho',4.9,82,0);
INSERT INTO Hotel VALUES(780,'Hotel Vallabh Darshan','Collector Office, Jaisalmer Ho',5.0,82,0);
INSERT INTO Hotel VALUES(781,'Royal Camps Hotel','Dunes  I, Jaisalmer Ho',4.5,82,0);
INSERT INTO Hotel VALUES(782,'Hotel Bharat Villas','Reception Centre, Jaisalmer Ho',4.7,82,0);
INSERT INTO Hotel VALUES(783,'Hotel Akashdeep','Mandir Circle, Jaisalmer Ho',4.4,82,0);
INSERT INTO Hotel VALUES(784,'Hotel Hayyat','Station Road, Jaisalmer Ho',3.5,82,0);
INSERT INTO Hotel VALUES(785,'Hotel Pol Haveli','Dedansar Road, Jaisalmer Ho',3.5,82,0);
INSERT INTO Hotel VALUES(786,'Vishal International Hotel','Khambhaliya Road, Airport Road',4.2,84,0);
INSERT INTO Hotel VALUES(787,'The Hotel','S T, Summair Club Road',4.6,84,0);
INSERT INTO Hotel VALUES(788,'Hotel Jash Palace','And Oswal Center, Airport Road',4.6,84,0);
INSERT INTO Hotel VALUES(789,'7 Seasons Resort & Spa','Dwarka Highway, Lakhabavad',4.5,84,0);
INSERT INTO Hotel VALUES(790,'Hotel Regency','Pandit Nehru Marg, Jamnagar Ho',4.0,84,0);
INSERT INTO Hotel VALUES(791,'Keshwaras Garden Hotel','& Jamnagar Bypass, Jamnagar Ho',4.1,84,0);
INSERT INTO Hotel VALUES(792,'Celebration Hotel','Gurudwara Circle, Indira Marg',4.2,84,0);
INSERT INTO Hotel VALUES(793,'Hotel Express Residency','Reliance Refinery, Moti Khavdi',4.0,84,0);
INSERT INTO Hotel VALUES(794,'Hotel Kalatit International','Teen Batti, Ranjit Road',4.2,84,0);
INSERT INTO Hotel VALUES(795,'Hotel Jash Palace','Road Khodiyar Colony, Jamnagar Ho',3.8,84,0);
INSERT INTO Hotel VALUES(796,'Hotel Jiva','New Planning Area, Sakchi',4.0,85,0);
INSERT INTO Hotel VALUES(797,'The Mahal Inn','Near Chepapul, Mango',4.8,85,0);
INSERT INTO Hotel VALUES(798,'Residency Square','S N P Area, Sakchi',4.4,85,0);
INSERT INTO Hotel VALUES(799,'The Wave International','N H 33, Mango',4.4,85,0);
INSERT INTO Hotel VALUES(800,'Hotel Satguru','A Road, Sonari',3.0,85,0);
INSERT INTO Hotel VALUES(801,'THE WEEKEND RESORT','Shankarda, Potka',3.5,85,0);
INSERT INTO Hotel VALUES(802,'Crystal Guest House','SAKCHI, Sakchi',4.3,85,0);
INSERT INTO Hotel VALUES(803,'Golden Leaf Resort','Nh33, Mango',3.5,85,0);
INSERT INTO Hotel VALUES(804,'Hotel Balajee','Road, Bistupur',3.8,85,0);
INSERT INTO Hotel VALUES(805,'The Citi Inn','NH 33, Mango',4.2,85,0);
INSERT INTO Hotel VALUES(806,'Hotel Ambrosia','Near Railway Station, Sipri Bazar',3.8,86,0);
INSERT INTO Hotel VALUES(807,'Yatrik Hotel','Elite Chowk, Civil Lines',3.4,86,0);
INSERT INTO Hotel VALUES(808,'Shrinath Palace Hotel','Station Raod, Civil Lines',3.9,86,0);
INSERT INTO Hotel VALUES(809,'Jhansi Hotel','Head Post, Jhansi Sadar Bazar',4.3,86,0);
INSERT INTO Hotel VALUES(810,'Samrat Hotel','Lines Chitra Chauraha, Jhansi Ho',3.8,86,0);
INSERT INTO Hotel VALUES(811,'Hotel Apna Guest House','Opposite Nagar Nigam, Civil Lines',3.0,86,0);
INSERT INTO Hotel VALUES(812,'Hotel Tulsi','Chitra Cinema Chowk, Civil Lines',4.1,86,0);
INSERT INTO Hotel VALUES(813,'Hotel Sita','Shivpuri Road, Civil Lines',3.9,86,0);
INSERT INTO Hotel VALUES(814,'Om Residency','- Sipri Road, Civil Lines',4.5,86,0);
INSERT INTO Hotel VALUES(815,'Hotel Bundelkhand Pride','Gwalior Road, Jhansi City',4.1,86,0);
INSERT INTO Hotel VALUES(816,'Shanti Bhawan Heritage Hotel','Railway, Railway Station Road',3.8,87,0);
INSERT INTO Hotel VALUES(817,'Hotel Jain Excellency','Shopping Centre, Shastri Nagar',3.8,87,0);
INSERT INTO Hotel VALUES(818,'The Fern Residency','Near Police Line, Ratanada',3.5,87,0);
INSERT INTO Hotel VALUES(819,'Hotel Shri Ram Excellency','Medical College, Residency Road',4.2,87,0);
INSERT INTO Hotel VALUES(820,'Fun World','Opposite Filter House, Jodhpur HO',3.8,87,0);
INSERT INTO Hotel VALUES(821,'Shagun Resorts','Ratanada, Jodhpur Ho',3.5,87,0);
INSERT INTO Hotel VALUES(822,'Hotel Kissan Legacy','Sanghi Petrol Pump, Jodhpur Ho',4.2,87,0);
INSERT INTO Hotel VALUES(823,'Hotel Jain Excellency','Kalptaru Cinema, Jodhpur Ho',3.5,87,0);
INSERT INTO Hotel VALUES(824,'Hotel Suncity International','Airport  Road, Ratanada Jodhpur',3.8,87,0);
INSERT INTO Hotel VALUES(825,'Hotel Raj Bagh','Jhanwar Road, Jodhpur Ho',5.0,87,0);
INSERT INTO Hotel VALUES(826,'Eco Inn','Nagar Road, Viman Nagar',3.9,88,0);
INSERT INTO Hotel VALUES(827,'Hotel Swasti','Apte Road, Deccan Gymkhana',3.8,88,0);
INSERT INTO Hotel VALUES(828,'Oyo Rooms','pimpri, Pune City',4.0,88,0);
INSERT INTO Hotel VALUES(829,'Ganga Retreat Countryside','Pune Nagar Highway, Wagholi',3.8,88,0);
INSERT INTO Hotel VALUES(830,'Samruddha Jeevan Hotel Orchard','Opposite HDFC Bank, Apte Road',4.0,88,0);
INSERT INTO Hotel VALUES(831,'Hotel Executive Residency','North Main Road, Koregaon Park',3.9,88,0);
INSERT INTO Hotel VALUES(832,'Hotel Sahara','Bapat Road, Chaturshringi',3.8,88,0);
INSERT INTO Hotel VALUES(833,'New White House','Lane No 5, Koregaon Park',3.6,88,0);
INSERT INTO Hotel VALUES(834,'Armaan Hotel','Indian Bank ATM, Rasta Peth',4.7,88,0);
INSERT INTO Hotel VALUES(835,'Aankur Inn','Road Sakore Nagar, Viman Nagar',3.9,88,0);
INSERT INTO Hotel VALUES(836,'Sukhsagar Gir Resort','National Park Road, Sasan Gir',4.1,89,0);
INSERT INTO Hotel VALUES(837,'Girsomnath Farm House','Sasan Amrutwel Road, Sasan Gir',4.2,89,0);
INSERT INTO Hotel VALUES(838,'Hotel Magnum inn','Opp.Sakkar Baug Zoo, Junagadh Ho',5.0,89,0);
INSERT INTO Hotel VALUES(839,'The Gir Kaizer','Near Hawadmata Temple, Sasan Gir',4.6,89,0);
INSERT INTO Hotel VALUES(840,'The Fern Gir Forest Resort','Talala Road, Sasan Gir',4.1,89,0);
INSERT INTO Hotel VALUES(841,'Hotel Indralok','Railway Station Road, Junagadh Ho',4.2,89,0);
INSERT INTO Hotel VALUES(842,'Narsinh Maheta Dham','Near Sudarshan Talav, Junagadh Ho',3.5,89,0);
INSERT INTO Hotel VALUES(843,'Hotel Ashirwad','Junagadh Highway, Junagadh Ho',4.1,89,0);
INSERT INTO Hotel VALUES(844,'Hotel Anil Farm House','Taluka Talala, Sasan Gir',4.1,89,0);
INSERT INTO Hotel VALUES(845,'Summit Hotels & Resorts','Barsana Fatak, Kalimpong Ho',2.5,90,0);
INSERT INTO Hotel VALUES(846,'SHERPA HERITAGE VILLAGE','Delo Road, Kalimpong HO',3.5,90,0);
INSERT INTO Hotel VALUES(847,'Hotel New Sonar Bangla, Ris...','Darjeeling, Kalimpong Ho',3.0,90,0);
INSERT INTO Hotel VALUES(848,'chavi Village Resort','Pedong Rishi Road, Kalimpong Ho',5.0,90,0);
INSERT INTO Hotel VALUES(849,'The Elgin Silver Oaks','King Pong Road, Kalimpong HO',4.5,90,0);
INSERT INTO Hotel VALUES(850,'Kalimpong Park Hotel','Rinkingpong Road, Kalimpong Ho',4.0,90,0);
INSERT INTO Hotel VALUES(851,'Deolo Tourist Lodge','Deolo, Kalimpong HO',4.7,90,0);
INSERT INTO Hotel VALUES(852,'Morgan House Tourist Lodge','Kalimpong HO',4.0,90,0);
INSERT INTO Hotel VALUES(853,'The Soods Garden Retreat','Rishi Road, Kalimpong Ho',3.9,90,0);
INSERT INTO Hotel VALUES(854,'Tres Hotel','Primtam Road, Kalimpong HO',3.0,90,0);
INSERT INTO Hotel VALUES(855,'Sri Hari Residency','West Raja Street, Kanchipuram RS',4.3,91,0);
INSERT INTO Hotel VALUES(856,'Heritage Inn','Nadu Street, Thandalam',3.9,91,0);
INSERT INTO Hotel VALUES(857,'Hotel Milestonnez','Santhavellor, Sunguvarchatram',3.5,91,0);
INSERT INTO Hotel VALUES(858,'Grt Regency','Gandhi Road, Kanchipuram Ho',4.1,91,0);
INSERT INTO Hotel VALUES(859,'Ellamay Resort','Vadapattinam, Kuvathur',3.5,91,0);
INSERT INTO Hotel VALUES(860,'The Naagaa Residency','Balaji Nagar, Enathur',4.2,91,0);
INSERT INTO Hotel VALUES(861,'Priyanga Paradise Inn','Street Thandalam, Sriperumbudur',3.5,91,0);
INSERT INTO Hotel VALUES(862,'Kpa Grand Palace','Car Street, Sriperumbudur',4.6,91,0);
INSERT INTO Hotel VALUES(863,'Amirtha Residency','Theradi Street, Sriperumbudur',3.0,91,0);
INSERT INTO Hotel VALUES(864,'S S Residency And Garden Re...','Nagar Nemili Road, Sriperumbudur',3.5,91,0);
INSERT INTO Hotel VALUES(865,'Oritel Service Apartment','Studio Road, Andheri East',3.6,92,0);
INSERT INTO Hotel VALUES(866,'Hotel Jawahar','Cross Hospital, Ulhasnagar No 3',3.9,92,0);
INSERT INTO Hotel VALUES(867,'Oyo Rooms','Andheri Ghatkopar Link Road, Juhu',2.1,92,0);
INSERT INTO Hotel VALUES(868,'Ace Residency','Military Road, Andheri East',3.6,92,0);
INSERT INTO Hotel VALUES(869,'The Resort','Madh-Marve Road, Malad West',4.0,92,0);
INSERT INTO Hotel VALUES(870,'Stay In','Sakhi Vhiar Road, Sakinaka',4.3,92,0);
INSERT INTO Hotel VALUES(871,'Hotel Royal Park','Andheri Kurla Road, Andheri East',3.8,92,0);
INSERT INTO Hotel VALUES(872,'Hotel Planet Plaza','Andheri Kurla Road, Andheri East',3.6,92,0);
INSERT INTO Hotel VALUES(873,'The Regenza By Tunga','Sector 30 A, Vashi',4.1,92,0);
INSERT INTO Hotel VALUES(874,'Martins Inn Beach Hotel','Arnala, Virar West',3.7,92,0);
INSERT INTO Hotel VALUES(875,'New Cape Hotel','Cape Road, Kanyakumari',3.9,94,0);
INSERT INTO Hotel VALUES(876,'The Seashore Hotel','East Car Street, Kanyakumari',4.3,94,0);
INSERT INTO Hotel VALUES(877,'Hotel Chithra','North Street, Kanyakumari',3.9,94,0);
INSERT INTO Hotel VALUES(878,'Hotel Sun World','Kovalam Road, Kanyakumari',3.9,94,0);
INSERT INTO Hotel VALUES(879,'Hotel Kanya','Main Road, Vivekanandapuram',3.5,94,0);
INSERT INTO Hotel VALUES(880,'Hotel Sunview','Office And Beach, Kanyakumari',4.1,94,0);
INSERT INTO Hotel VALUES(881,'V R Happy Homes','Murugan Kundrum Hill, Kanyakumari',3.5,94,0);
INSERT INTO Hotel VALUES(882,'Hotel Pushpam','Hospital Road, Kanyakumari',4.7,94,0);
INSERT INTO Hotel VALUES(883,'Iyslin Cars And Hotels','Kottaram, Kanyakumari',5.0,94,0);
INSERT INTO Hotel VALUES(884,'Hotel Vishnu Ram','North Street, Kanyakumari',3.5,94,0);
INSERT INTO Hotel VALUES(885,'D Zojila Hotel','Biamathang, Kargil Ho',4.0,95,0);
INSERT INTO Hotel VALUES(886,'Hotel Siachen','Main Bazar, Kargil Ho',3.0,95,0);
INSERT INTO Hotel VALUES(887,'Carvan Sarai Hotel','BSNL Office, Kargil HO',3.5,95,0);
INSERT INTO Hotel VALUES(888,'Hotel Greenland','Old Taxi Stand, Kargil Ho',5.0,95,0);
INSERT INTO Hotel VALUES(889,'P C Palace','Near Main Market, Kargil Ho',4.0,95,0);
INSERT INTO Hotel VALUES(890,'Hotel Sunrise Cottage','Kasauli Chowk, Dharampur',3.5,96,0);
INSERT INTO Hotel VALUES(891,'Sanawar View','Kimu Ghat, Kasauli',3.7,96,0);
INSERT INTO Hotel VALUES(892,'UNA Comfort Kasauli Exotica','2km Before Bus Stand, Kasauli',3.8,96,0);
INSERT INTO Hotel VALUES(893,'Sukhmani Homestay Kasauli','P.O  .-Jubber, Kasauli',4.2,96,0);
INSERT INTO Hotel VALUES(894,'Captains Nest','Kasauli, Kasauli',3.5,96,0);
INSERT INTO Hotel VALUES(895,'Stella Dream Land Home Stay...','Near SAI Mandir, Kasauli',5.0,96,0);
INSERT INTO Hotel VALUES(896,'Omkara','Near SAI Baba Mandir, Kasauli',4.0,96,0);
INSERT INTO Hotel VALUES(897,'Blossom Resorts','Jagjit Nagar Road, Kasauli',3.5,96,0);
INSERT INTO Hotel VALUES(898,'Birds View Resort','Old Kasauli Road, Kasauli',4.0,96,0);
INSERT INTO Hotel VALUES(899,'Chander Mukhi Resorts Pvt Ltd','Kalka Shimla Highway, Kasauli',3.6,96,0);
INSERT INTO Hotel VALUES(900,'Hotel Sunita','Kausani Road, Almora HO',3.0,97,0);
INSERT INTO Hotel VALUES(901,'Krishna Mountview Mountain Resort','Kausani',4.5,97,0);
INSERT INTO Hotel VALUES(902,'Chevron ECO Lodge','Estate Guest House Road, Kausani',5.0,97,0);
INSERT INTO Hotel VALUES(903,'Suman Royal Resort','VIP Road, Kausani',4.0,97,0);
INSERT INTO Hotel VALUES(904,'Himalaya Darshan Resort','Kausani Bhatariya Road, Kausani',5.0,97,0);
INSERT INTO Hotel VALUES(905,'Sun N Snow Inn','Near Ana Shakti Ashram, Kausani',4.0,97,0);
INSERT INTO Hotel VALUES(906,'Heritage Kausani','Vaidhnath Road, Kausani',5.0,97,0);
INSERT INTO Hotel VALUES(907,'Himalayan Village Resort','Baijnath Road, Kausani',0.0,97,0);
INSERT INTO Hotel VALUES(908,'Hotel Uttarakhand','New Road Kausani, Kausani',4.0,97,0);
INSERT INTO Hotel VALUES(909,'Pratiksha Himalayan Retreat','Baijnath Road, Kausani',3.0,97,0);
INSERT INTO Hotel VALUES(910,'Hotel India','Gandhi Chowk, Hatadihi',0.0,98,0);
INSERT INTO Hotel VALUES(911,'Hotel The Sangam Palace','Barbil Barajamda Road, Joda',0.0,98,0);
INSERT INTO Hotel VALUES(912,'Circuit House','Keonjhar Bazar',0.0,98,0);
INSERT INTO Hotel VALUES(913,'Hotel Shankar Palace','Dhangarpada, Keonjhar Bazar',0.0,98,0);
INSERT INTO Hotel VALUES(914,'Shree Krishna Hotel','Madhapur,',0.0,98,0);
INSERT INTO Hotel VALUES(915,'Gayatri Guest House','Keonjhar, Joda',0.0,98,0);
INSERT INTO Hotel VALUES(916,'Valley Hotel','Joda',0.0,98,0);
INSERT INTO Hotel VALUES(917,'Baidyanath Hotel','Joda',4.0,98,0);
INSERT INTO Hotel VALUES(918,'Pooja Lodge','Joda',0.0,98,0);
INSERT INTO Hotel VALUES(919,'Hotel Bikash','Gandhi Chowk, Keonjhargarh Ho',0.0,98,0);
INSERT INTO Hotel VALUES(920,'Gupta Inn','Motor Petrol Pump, Varuna Bridge',3.5,99,0);
INSERT INTO Hotel VALUES(921,'Atithi Satkaar Hotel','Luxa Road, Godowlia',3.6,99,0);
INSERT INTO Hotel VALUES(922,'Hotel Sarin Inn','Radison Hotel, Varanasi Cantt',3.9,99,0);
INSERT INTO Hotel VALUES(923,'Hotel The Sapphire Grand','The Mall Road, Cantonment',4.4,99,0);
INSERT INTO Hotel VALUES(924,'Marco Guest House','Laxman Bhawan, Lahurabir',4.7,99,0);
INSERT INTO Hotel VALUES(925,'Hotel Kiran Palace','Cantonment Area, Mall Road',2.6,99,0);
INSERT INTO Hotel VALUES(926,'Hkj Palace','Jangambadi, Godowlia',3.5,99,0);
INSERT INTO Hotel VALUES(927,'The Swastik Guest House','Dashaswamedh Godowlia, Godowlia',4.6,99,0);
INSERT INTO Hotel VALUES(928,'Alka Hotel','D- 3/23, Meerghat',2.8,99,0);
INSERT INTO Hotel VALUES(929,'Hotel Divine Inn','Near Anandmaya Hospital, Shivala',4.0,99,0);
INSERT INTO Hotel VALUES(930,'The Lalit Temple View','Circuit House, Khajuraho Ho',4.3,100,0);
INSERT INTO Hotel VALUES(931,'Radisson Jass Hotel','By Pass Road, Khajuraho Ho',4.1,100,0);
INSERT INTO Hotel VALUES(932,'Hotel Chandela','Airport Road, Khajuraho Ho',4.1,100,0);
INSERT INTO Hotel VALUES(933,'Hotel Ramada','Airport Road, Khajuraho Ho',4.2,100,0);
INSERT INTO Hotel VALUES(934,'Hotel Clarks','Airport Road, Khajuraho Ho',3.8,100,0);
INSERT INTO Hotel VALUES(935,'Hotel Surya','Jain Temple Road, Khajuraho Ho',4.5,100,0);
INSERT INTO Hotel VALUES(936,'Hotel Usha Bundela','Bundela Temple Road, Khajuraho Ho',3.9,100,0);
INSERT INTO Hotel VALUES(937,'GW Greenwood Art Hotel','Khajuraho Airport, Khajuraho Ho',3.0,100,0);
INSERT INTO Hotel VALUES(938,'Hotel Payal','Group Of Temple, Khajuraho Ho',3.5,100,0);
INSERT INTO Hotel VALUES(939,'Hotel Harmony','Jain Temple Road, Khajuraho Ho',3.3,100,0);
INSERT INTO Hotel VALUES(940,'Hotel Hindusthan International Hotel','Janak Vihar Complex',5.0,1,5);
INSERT INTO Hotel VALUES(941,'The Lalit','Trunk Road',5.0,1,7);
INSERT INTO Hotel VALUES(942,'Maurya Sheraton','Sapphire Crossroads',5.0,1,9);
INSERT INTO Hotel VALUES(943,'ITC Hotel','West Sang',5.0,2,2);
INSERT INTO Hotel VALUES(944,'Ginger Hotel','Asaf Ali Road',5.0,2,13);
INSERT INTO Hotel VALUES(945,'The Leela Palace','SG Bypass Highway',5.0,2,3);
INSERT INTO Hotel VALUES(946,'ITC Hotel','Satellite Plaza',5.0,3,2);
INSERT INTO Hotel VALUES(947,'Hotel Ramada Plaza','Cerebrum IT Park',5.0,3,14);
INSERT INTO Hotel VALUES(948,'Royal Orchid Hotel','DLF Park',5.0,3,16);
INSERT INTO Hotel VALUES(949,'Ginger Hotel','Race Course Road',5.0,9,13);
INSERT INTO Hotel VALUES(950,'Hotel Ramada Plaza','Sunrise Park Road Corner',5.0,9,14);
INSERT INTO Hotel VALUES(951,'Laxmi Vilas Hotel','Hazratganj Market, Hazratganj',5.0,9,4);
INSERT INTO Hotel VALUES(952,'Laxmi Vilas Hotel','Remazin Complex',5.0,11,4);
INSERT INTO Hotel VALUES(953,'ITC Hotel','Challengers Road',5.0,11,2);
INSERT INTO Hotel VALUES(954,'The Residency Hotel','Ferdinand Cross, MG Road',5.0,20,12);
INSERT INTO Hotel VALUES(955,'Hotel Ramada Plaza','Near R Mall, Vishwakarma’',5.0,20,14);
INSERT INTO Hotel VALUES(956,'Hotel Radisson','Next to Bavaria Motors, Cantonment Area',5.0,20,8);
INSERT INTO Hotel VALUES(957,'The Leela Palace','Next to Tendulkars, Mazagaon',5.0,21,3);
INSERT INTO Hotel VALUES(958,'Maurya Sheraton','Next to Benz Showroom,Viman Nagar Plaza',5.0,21,9);
INSERT INTO Hotel VALUES(959,'Ginger Hotel','Next to Sheraton, Cooper Place',5.0,21,13);
INSERT INTO Hotel VALUES(960,'Hotel Hindusthan International Hotel','Near Food Plaza, Reliance Mart, Fatima Nagar',5.0,21,5); 
INSERT INTO Hotel VALUES(961,'Royal Orchid Hotel','Next to St. Felix Church, Ladkatwadi Marg',5.0,21,16);
INSERT INTO Hotel VALUES(962,'Hotel Hindusthan International Hotel','Near HDFC Bank H.O, Boat Club Road',5.0,24,5);
INSERT INTO Hotel VALUES(963,'Laxmi Vilas Hotel','Near PVR Cinemas, Wakdewadi',5.0,24,4);
INSERT INTO Hotel VALUES(964,'Royal Orchid Hotel','Near Dastur Inamdar Girls School, Camp',5.0,25,16);
INSERT INTO Hotel VALUES(965,'Le Meridian','Next to Sophia Girls School, Matt Road',5.0,31,20);
INSERT INTO Hotel VALUES(966,'Ginger Hotel','Near Foodies Market, Pushpani Road',5.0,31,13);
INSERT INTO Hotel VALUES(967,'Hotel Radisson','Next to Air Force Jubilee Theatre, Viman Nagar',5.0,36,8);
INSERT INTO Hotel VALUES(968,'The Park','Near Police Gymkhana, Cryform Street',5.0,36,15);
INSERT INTO Hotel VALUES(969,'JW Mariott','Near Connaught Plaza, Camp Area',5.0,36,1);
INSERT INTO Hotel VALUES(970,'LemonTree Hotel','Next to Honda Showroom, Wanowrie',5.0,36,11);
INSERT INTO Hotel VALUES(971,'Royal Orchid Hotel','Near FC College of Arts and Commerce, FC Road',5.0,36,16);
INSERT INTO Hotel VALUES(972,'Hotel Ramada Plaza','Next to Geetanjali, HSBC Bank, Nagpurchawl',5.0,37,14);
INSERT INTO Hotel VALUES(973,'The Leela Palace','S.No.32, North Main Road',5.0,37,3);
INSERT INTO Hotel VALUES(974,'The Residency Hotel','Gentlemen Street,Next to KPP Plaza, Kalyani Nagar',5.0,37,12);
INSERT INTO Hotel VALUES(975,'Ashok Hotel','Three Roadcross,Near Passport Seva Kendra, Military School Road',5.0,37,19);
INSERT INTO Hotel VALUES(976,'Laxmi Vilas Hotel','Kendra Bridge Road',5.0,37,4);
INSERT INTO Hotel VALUES(977,'Ashok Hotel','Near Renaissance Builders H.O., Koregaon Park',5.0,40,19);
INSERT INTO Hotel VALUES(978,'ITC Hotel','Next to Big Cinemas, Koregaon Park',5.0,40,2);
INSERT INTO Hotel VALUES(979,'Hotel Ramada Plaza','Ramada Plaza, Kalyani Nagar',5.0,56,14);
INSERT INTO Hotel VALUES(980,'JW Mariott','S.No.74, MG Road',5.0,56,1);
INSERT INTO Hotel VALUES(981,'Ginger Hotel','Plot No.34/35/36, NS Road',5.0,56,13);
INSERT INTO Hotel VALUES(982,'Howard Park Plaza','Oppo. Police Grounds, JK Chowk',5.0,56,10);
INSERT INTO Hotel VALUES(983,'LemonTree Hotel','Near Sai’s Ice Skating Rink,NS Chowk',5.0,56,11);
INSERT INTO Hotel VALUES(984,'The Leela Palace','Next to Starbucks Coffee Shop, NS Road',5.0,68,3);
INSERT INTO Hotel VALUES(985,'JW Mariott','Next to Ramada Coffee Shop, Redent Multi-speciality Hospital',5.0,78,1);
INSERT INTO Hotel VALUES(986,'Laxmi Vilas Hotel','Near Police Commisioner’s H.Q., Central City',5.0,78,4);
INSERT INTO Hotel VALUES(987,'Ginger Hotel','NH-10 Entry Point Chowk, NH-10',5.0,78,13);
INSERT INTO Hotel VALUES(988,'Taj Hotel','Near Taj Regency,Outer Ring Road',5.0,78,6);
INSERT INTO Hotel VALUES(989,'Maurya Sheraton','S.No.81/82/83, Park Plaza',5.0,81,9);
INSERT INTO Hotel VALUES(990,'Hotel Radisson','Opposite Govt Circuit House Area',5.0,81,8);
INSERT INTO Hotel VALUES(991,'LemonTree Hotel','Near LakeView Residency Club,',5.0,81,11);
INSERT INTO Hotel VALUES(992,'Hotel Ramada Plaza','Next to Hotel Maurya Sheraton, Park Plaza',5.0,81,14);
INSERT INTO Hotel VALUES(993,'Hotel Radisson','Next to Apollo Hospitals,CNR Avenue',5.0,87,8);
INSERT INTO Hotel VALUES(994,'Oberoi Hotel & Resort','Near ICICI Main Branch, M.G Road',5.0,93,18);
INSERT INTO Hotel VALUES(995,'Ashok Hotel','Birhana Road',5.0,93,19);
INSERT INTO Hotel VALUES(996,'Hotel Hindusthan International Hotel','19, Ring Road',5.0,93,5);
INSERT INTO Hotel VALUES(997,'Lemon Tree Hotel','Udyog Vihar',5.0,93,11);
INSERT INTO Hotel VALUES(998,'The Leela Palace','19, Sindhu Nagar Colony,Sigra',5.0,99,3);
INSERT INTO Hotel VALUES(999,'Hotel Radisson','The Mall Cantonment, Mall Road',5.0,99,8);
INSERT INTO Hotel VALUES(1000,'Ginger Hotel','Near Naria Chowk, NHDA H.Q',5.0,99,13);

