INSERT INTO Hub VALUES(1,'Agra City Bus Station / ISBT','Agra',1);
INSERT INTO Hub VALUES(2,'Agra Railway Station','Agra',1);
INSERT INTO Hub VALUES(3,'Ahmedabad Sardar Vallabhbhai Patel International Airport','Ahmedabad',2);
INSERT INTO Hub VALUES(4,'Ahmedabad City Bus Station / ISBT','Ahmedabad',2);
INSERT INTO Hub VALUES(5,'Ahmedabad Railway Station','Ahmedabad',2);
INSERT INTO Hub VALUES(6,'Ajmer City Bus Station / ISBT','Ajmer',3);
INSERT INTO Hub VALUES(7,'Ajmer Railway Station','Ajmer',3);
INSERT INTO Hub VALUES(8,'Alappuzha City Bus Station / ISBT','Alappuzha',4);
INSERT INTO Hub VALUES(9,'Alappuzha Railway Station','Alappuzha',4);
INSERT INTO Hub VALUES(10,'Alibag City Bus Station / ISBT','Alibag',5);
INSERT INTO Hub VALUES(11,'Alibag Railway Station','Alibag',5);
INSERT INTO Hub VALUES(12,'Allahabad City Bus Station / ISBT','Allahabad',6);
INSERT INTO Hub VALUES(13,'Allahabad Railway Station','Allahabad',6);
INSERT INTO Hub VALUES(14,'Almora City Bus Station / ISBT','Almora',7);
INSERT INTO Hub VALUES(15,'Almora Railway Station','Almora',7);
INSERT INTO Hub VALUES(16,'Amarnath City Bus Station / ISBT','Amarnath',8);
INSERT INTO Hub VALUES(17,'Amarnath Railway Station','Amarnath',8);
INSERT INTO Hub VALUES(18,'Amritsar International Airport','Amritsar',9);
INSERT INTO Hub VALUES(19,'Amritsar City Bus Station / ISBT','Amritsar',9);
INSERT INTO Hub VALUES(20,'Amritsar Railway Station','Amritsar',9);
INSERT INTO Hub VALUES(21,'Andaman & Nicobar City Bus Station / ISBT','Andaman & Nicobar',10);
INSERT INTO Hub VALUES(22,'Andaman & Nicobar Railway Station','Andaman & Nicobar',10);
INSERT INTO Hub VALUES(23,'Patna Jay Prakash Narayan International Airport','Patna',11);
INSERT INTO Hub VALUES(24,'Patna City Bus Station / ISBT','Patna',11);
INSERT INTO Hub VALUES(25,'Patna Railway Station','Patna',11);
INSERT INTO Hub VALUES(26,'wasehpur City Bus Station / ISBT','wasehpur',12);
INSERT INTO Hub VALUES(27,'wasehpur Railway Station','wasehpur',12);
INSERT INTO Hub VALUES(28,'simhachalam City Bus Station / ISBT','simhachalam',13);
INSERT INTO Hub VALUES(29,'simhachalam Railway Station','simhachalam',13);
INSERT INTO Hub VALUES(30,'Tirupati City Bus Station / ISBT','Tirupati',14);
INSERT INTO Hub VALUES(31,'Tirupati Railway Station','Tirupati',14);
INSERT INTO Hub VALUES(32,'Warangal City Bus Station / ISBT','Warangal',15);
INSERT INTO Hub VALUES(33,'Warangal Railway Station','Warangal',15);
INSERT INTO Hub VALUES(34,'Ayodhya City Bus Station / ISBT','Ayodhya',16);
INSERT INTO Hub VALUES(35,'Ayodhya Railway Station','Ayodhya',16);
INSERT INTO Hub VALUES(36,'Badami City Bus Station / ISBT','Badami',17);
INSERT INTO Hub VALUES(37,'Badami Railway Station','Badami',17);
INSERT INTO Hub VALUES(38,'Balasore City Bus Station / ISBT','Balasore',18);
INSERT INTO Hub VALUES(39,'Balasore Railway Station','Balasore',18);
INSERT INTO Hub VALUES(40,'Bandhavgarh City Bus Station / ISBT','Bandhavgarh',19);
INSERT INTO Hub VALUES(41,'Bandhavgarh Railway Station','Bandhavgarh',19);
INSERT INTO Hub VALUES(42,'Mysore City Bus Station / ISBT','Mysore',20);
INSERT INTO Hub VALUES(43,'Mysore Railway Station','Mysore',20);
INSERT INTO Hub VALUES(44,'Ooty City Bus Station / ISBT','Ooty',21);
INSERT INTO Hub VALUES(45,'Ooty Railway Station','Ooty',21);
INSERT INTO Hub VALUES(46,'Belgaum City Bus Station / ISBT','Belgaum',22);
INSERT INTO Hub VALUES(47,'Belgaum Railway Station','Belgaum',22);
INSERT INTO Hub VALUES(48,'Matheran City Bus Station / ISBT','Matheran',23);
INSERT INTO Hub VALUES(49,'Matheran Railway Station','Matheran',23);
INSERT INTO Hub VALUES(50,'Bengaluru City Bus Station / ISBT','Bengaluru',24);
INSERT INTO Hub VALUES(51,'Bengaluru Railway Station','Bengaluru',24);
INSERT INTO Hub VALUES(52,'Lucknow Chaudhary Charan Singh Airport','Lucknow',25);
INSERT INTO Hub VALUES(53,'Lucknow City Bus Station / ISBT','Lucknow',25);
INSERT INTO Hub VALUES(54,'Lucknow Railway Station','Lucknow',25);
INSERT INTO Hub VALUES(55,'Muzaffarpur City Bus Station / ISBT','Muzaffarpur',26);
INSERT INTO Hub VALUES(56,'Muzaffarpur Railway Station','Muzaffarpur',26);
INSERT INTO Hub VALUES(57,'Madurai Airport','Madurai',27);
INSERT INTO Hub VALUES(58,'Madurai City Bus Station / ISBT','Madurai',27);
INSERT INTO Hub VALUES(59,'Madurai Railway Station','Madurai',27);
INSERT INTO Hub VALUES(60,'Bhubaneswar Biju Patnaik International Airport','Bhubaneswar',28);
INSERT INTO Hub VALUES(61,'Bhubaneswar City Bus Station / ISBT','Bhubaneswar',28);
INSERT INTO Hub VALUES(62,'Bhubaneswar Railway Station','Bhubaneswar',28);
INSERT INTO Hub VALUES(63,'Bidar City Bus Station / ISBT','Bidar',29);
INSERT INTO Hub VALUES(64,'Bidar Railway Station','Bidar',29);
INSERT INTO Hub VALUES(65,'Bijapur City Bus Station / ISBT','Bijapur',30);
INSERT INTO Hub VALUES(66,'Bijapur Railway Station','Bijapur',30);
INSERT INTO Hub VALUES(67,'Bikaner City Bus Station / ISBT','Bikaner',31);
INSERT INTO Hub VALUES(68,'Bikaner Railway Station','Bikaner',31);
INSERT INTO Hub VALUES(69,'Bodhgaya City Bus Station / ISBT','Bodhgaya',32);
INSERT INTO Hub VALUES(70,'Bodhgaya Railway Station','Bodhgaya',32);
INSERT INTO Hub VALUES(71,'Bolangir City Bus Station / ISBT','Bolangir',33);
INSERT INTO Hub VALUES(72,'Bolangir Railway Station','Bolangir',33);
INSERT INTO Hub VALUES(73,'Bundi-Kota-Jhalawar City Bus Station / ISBT','Bundi-Kota-Jhalawar',34);
INSERT INTO Hub VALUES(74,'Bundi-Kota-Jhalawar Railway Station','Bundi-Kota-Jhalawar',34);
INSERT INTO Hub VALUES(75,'Chamba City Bus Station / ISBT','Chamba',35);
INSERT INTO Hub VALUES(76,'Chamba Railway Station','Chamba',35);
INSERT INTO Hub VALUES(77,'Kolkata International Airport','Kolkata',36);
INSERT INTO Hub VALUES(78,'Kolkata City Bus Station / ISBT','Kolkata',36);
INSERT INTO Hub VALUES(79,'Kolkata Railway Station','Kolkata',36);
INSERT INTO Hub VALUES(80,'Chandigarh Airport','Chandigarh',37);
INSERT INTO Hub VALUES(81,'Chandigarh City Bus Station / ISBT','Chandigarh',37);
INSERT INTO Hub VALUES(82,'Chandigarh Railway Station','Chandigarh',37);
INSERT INTO Hub VALUES(83,'Chandipur City Bus Station / ISBT','Chandipur',38);
INSERT INTO Hub VALUES(84,'Chandipur Railway Station','Chandipur',38);
INSERT INTO Hub VALUES(85,'Chardham City Bus Station / ISBT','Chardham',39);
INSERT INTO Hub VALUES(86,'Chardham Railway Station','Chardham',39);
INSERT INTO Hub VALUES(87,'Chennai International Airport','Chennai',40);
INSERT INTO Hub VALUES(88,'Chennai City Bus Station / ISBT','Chennai',40);
INSERT INTO Hub VALUES(89,'Chennai Railway Station','Chennai',40);
INSERT INTO Hub VALUES(90,'Chidambaram City Bus Station / ISBT','Chidambaram',41);
INSERT INTO Hub VALUES(91,'Chidambaram Railway Station','Chidambaram',41);
INSERT INTO Hub VALUES(92,'Salem City Bus Station / ISBT','Salem',42);
INSERT INTO Hub VALUES(93,'Salem Railway Station','Salem',42);
INSERT INTO Hub VALUES(94,'Coimbatore International Airport','Coimbatore',43);
INSERT INTO Hub VALUES(95,'Coimbatore City Bus Station / ISBT','Coimbatore',43);
INSERT INTO Hub VALUES(96,'Coimbatore Railway Station','Coimbatore',43);
INSERT INTO Hub VALUES(97,'Coonoor City Bus Station / ISBT','Coonoor',44);
INSERT INTO Hub VALUES(98,'Coonoor Railway Station','Coonoor',44);
INSERT INTO Hub VALUES(99,'Tiruchirappalli International Airport','Tiruchirapalli',45);
INSERT INTO Hub VALUES(100,'Tiruchirapalli City Bus Station / ISBT','Tiruchirapalli',45);
INSERT INTO Hub VALUES(101,'Tiruchirapalli Railway Station','Tiruchirapalli',45);
INSERT INTO Hub VALUES(102,'Kochi City Bus Station / ISBT','Kochi',46);
INSERT INTO Hub VALUES(103,'Kochi Railway Station','Kochi',46);
INSERT INTO Hub VALUES(104,'Cuttack City Bus Station / ISBT','Cuttack',47);
INSERT INTO Hub VALUES(105,'Cuttack Railway Station','Cuttack',47);
INSERT INTO Hub VALUES(106,'Dadra and Nagar Haveli City Bus Station / ISBT','Dadra and Nagar Haveli',48);
INSERT INTO Hub VALUES(107,'Dadra and Nagar Haveli Railway Station','Dadra and Nagar Haveli',48);
INSERT INTO Hub VALUES(108,'Dalhousie City Bus Station / ISBT','Dalhousie',49);
INSERT INTO Hub VALUES(109,'Dalhousie Railway Station','Dalhousie',49);
INSERT INTO Hub VALUES(110,'Konark City Bus Station / ISBT','Konark',50);
INSERT INTO Hub VALUES(111,'Konark Railway Station','Konark',50);
INSERT INTO Hub VALUES(112,'Daman City Bus Station / ISBT','Daman',51);
INSERT INTO Hub VALUES(113,'Daman Railway Station','Daman',51);
INSERT INTO Hub VALUES(114,'Darbhanga City Bus Station / ISBT','Darbhanga',52);
INSERT INTO Hub VALUES(115,'Darbhanga Railway Station','Darbhanga',52);
INSERT INTO Hub VALUES(116,'Kullu City Bus Station / ISBT','Kullu',53);
INSERT INTO Hub VALUES(117,'Kullu Railway Station','Kullu',53);
INSERT INTO Hub VALUES(118,'Darjeeling City Bus Station / ISBT','Darjeeling',54);
INSERT INTO Hub VALUES(119,'Darjeeling Railway Station','Darjeeling',54);
INSERT INTO Hub VALUES(120,'Dehradun City Bus Station / ISBT','Dehradun',55);
INSERT INTO Hub VALUES(121,'Dehradun Railway Station','Dehradun',55);
INSERT INTO Hub VALUES(122,'Delhi Indira Gandhi International Airport','New Delhi',56);
INSERT INTO Hub VALUES(123,'New Delhi City Bus Station / ISBT','New Delhi',56);
INSERT INTO Hub VALUES(124,'New Delhi Railway Station','New Delhi',56);
INSERT INTO Hub VALUES(125,'Deoghar City Bus Station / ISBT','Deoghar',57);
INSERT INTO Hub VALUES(126,'Deoghar Railway Station','Deoghar',57);
INSERT INTO Hub VALUES(127,'Dhanbad City Bus Station / ISBT','Dhanbad',58);
INSERT INTO Hub VALUES(128,'Dhanbad Railway Station','Dhanbad',58);
INSERT INTO Hub VALUES(129,'Dharamshala City Bus Station / ISBT','Dharamshala',59);
INSERT INTO Hub VALUES(130,'Dharamshala Railway Station','Dharamshala',59);
INSERT INTO Hub VALUES(131,'Dharmapuri City Bus Station / ISBT','Dharmapuri',60);
INSERT INTO Hub VALUES(132,'Dharmapuri Railway Station','Dharmapuri',60);
INSERT INTO Hub VALUES(133,'Digha City Bus Station / ISBT','Digha',61);
INSERT INTO Hub VALUES(134,'Digha Railway Station','Digha',61);
INSERT INTO Hub VALUES(135,'Diu City Bus Station / ISBT','Diu',62);
INSERT INTO Hub VALUES(136,'Diu Railway Station','Diu',62);
INSERT INTO Hub VALUES(137,'Dwarka City Bus Station / ISBT','Dwarka',63);
INSERT INTO Hub VALUES(138,'Dwarka Railway Station','Dwarka',63);
INSERT INTO Hub VALUES(139,'Ghrishneshwar City Bus Station / ISBT','Ghrishneshwar',64);
INSERT INTO Hub VALUES(140,'Ghrishneshwar Railway Station','Ghrishneshwar',64);
INSERT INTO Hub VALUES(141,'Giridih City Bus Station / ISBT','Giridih',65);
INSERT INTO Hub VALUES(142,'Giridih Railway Station','Giridih',65);
INSERT INTO Hub VALUES(143,'Gokarna City Bus Station / ISBT','Gokarna',67);
INSERT INTO Hub VALUES(144,'Gokarna Railway Station','Gokarna',67);
INSERT INTO Hub VALUES(145,'Visakhapatnam Airport','Visakhapatnam',68);
INSERT INTO Hub VALUES(146,'Visakhapatnam City Bus Station / ISBT','Visakhapatnam',68);
INSERT INTO Hub VALUES(147,'Visakhapatnam Railway Station','Visakhapatnam',68);
INSERT INTO Hub VALUES(148,'Gulmarg City Bus Station / ISBT','Gulmarg',69);
INSERT INTO Hub VALUES(149,'Gulmarg Railway Station','Gulmarg',69);
INSERT INTO Hub VALUES(150,'Guruvayoor City Bus Station / ISBT','Guruvayoor',70);
INSERT INTO Hub VALUES(151,'Guruvayoor Railway Station','Guruvayoor',70);
INSERT INTO Hub VALUES(152,'Gwalior City Bus Station / ISBT','Gwalior',71);
INSERT INTO Hub VALUES(153,'Gwalior Railway Station','Gwalior',71);
INSERT INTO Hub VALUES(154,'Hampi City Bus Station / ISBT','Hampi',72);
INSERT INTO Hub VALUES(155,'Hampi Railway Station','Hampi',72);
INSERT INTO Hub VALUES(156,'Haridwar City Bus Station / ISBT','Haridwar',73);
INSERT INTO Hub VALUES(157,'Haridwar Railway Station','Haridwar',73);
INSERT INTO Hub VALUES(158,'Hassan City Bus Station / ISBT','Hassan',74);
INSERT INTO Hub VALUES(159,'Hassan Railway Station','Hassan',74);
INSERT INTO Hub VALUES(160,'Hazaribagh City Bus Station / ISBT','Hazaribagh',75);
INSERT INTO Hub VALUES(161,'Hazaribagh Railway Station','Hazaribagh',75);
INSERT INTO Hub VALUES(162,'Hogenakkal City Bus Station / ISBT','Hogenakkal',76);
INSERT INTO Hub VALUES(163,'Hogenakkal Railway Station','Hogenakkal',76);
INSERT INTO Hub VALUES(164,'Horsley Hills City Bus Station / ISBT','Horsley Hills',77);
INSERT INTO Hub VALUES(165,'Horsley Hills Railway Station','Horsley Hills',77);
INSERT INTO Hub VALUES(166,'Hyderabad Rajiv Gandhi International Airport','Hyderabad',78);
INSERT INTO Hub VALUES(167,'Hyderabad City Bus Station / ISBT','Hyderabad',78);
INSERT INTO Hub VALUES(168,'Hyderabad Railway Station','Hyderabad',78);
INSERT INTO Hub VALUES(169,'Jabalpur City Bus Station / ISBT','Jabalpur',79);
INSERT INTO Hub VALUES(170,'Jabalpur Railway Station','Jabalpur',79);
INSERT INTO Hub VALUES(171,'Jagdalpur City Bus Station / ISBT','Jagdalpur',80);
INSERT INTO Hub VALUES(172,'Jagdalpur Railway Station','Jagdalpur',80);
INSERT INTO Hub VALUES(173,'Jaipur Airport','Jaipur',81);
INSERT INTO Hub VALUES(174,'Jaipur City Bus Station / ISBT','Jaipur',81);
INSERT INTO Hub VALUES(175,'Jaipur Railway Station','Jaipur',81);
INSERT INTO Hub VALUES(176,'Jaisalmer City Bus Station / ISBT','Jaisalmer',82);
INSERT INTO Hub VALUES(177,'Jaisalmer Railway Station','Jaisalmer',82);
INSERT INTO Hub VALUES(178,'Jammu Airport','Jammu',83);
INSERT INTO Hub VALUES(179,'Jammu City Bus Station / ISBT','Jammu',83);
INSERT INTO Hub VALUES(180,'Jammu Railway Station','Jammu',83);
INSERT INTO Hub VALUES(181,'Jamnagar City Bus Station / ISBT','Jamnagar',84);
INSERT INTO Hub VALUES(182,'Jamnagar Railway Station','Jamnagar',84);
INSERT INTO Hub VALUES(183,'Jamshedpur City Bus Station / ISBT','Jamshedpur',85);
INSERT INTO Hub VALUES(184,'Jamshedpur Railway Station','Jamshedpur',85);
INSERT INTO Hub VALUES(185,'Jhansi City Bus Station / ISBT','Jhansi',86);
INSERT INTO Hub VALUES(186,'Jhansi Railway Station','Jhansi',86);
INSERT INTO Hub VALUES(187,'Jodhpur City Bus Station / ISBT','Jodhpur',87);
INSERT INTO Hub VALUES(188,'Jodhpur Railway Station','Jodhpur',87);
INSERT INTO Hub VALUES(189,'Junagadh City Bus Station / ISBT','Junagadh',89);
INSERT INTO Hub VALUES(190,'Junagadh Railway Station','Junagadh',89);
INSERT INTO Hub VALUES(191,'Kalimpong City Bus Station / ISBT','Kalimpong',90);
INSERT INTO Hub VALUES(192,'Kalimpong Railway Station','Kalimpong',90);
INSERT INTO Hub VALUES(193,'Kanchipuram City Bus Station / ISBT','Kanchipuram',91);
INSERT INTO Hub VALUES(194,'Kanchipuram Railway Station','Kanchipuram',91);
INSERT INTO Hub VALUES(195,'Kanha National Park City Bus Station / ISBT','Kanha National Park',92);
INSERT INTO Hub VALUES(196,'Kanha National Park Railway Station','Kanha National Park',92);
INSERT INTO Hub VALUES(197,'Kanpur City Bus Station / ISBT','Kanpur',93);
INSERT INTO Hub VALUES(198,'Kanpur Railway Station','Kanpur',93);
INSERT INTO Hub VALUES(199,'Kanyakumari City Bus Station / ISBT','Kanyakumari',94);
INSERT INTO Hub VALUES(200,'Kanyakumari Railway Station','Kanyakumari',94);
INSERT INTO Hub VALUES(201,'Kargil City Bus Station / ISBT','Kargil',95);
INSERT INTO Hub VALUES(202,'Kargil Railway Station','Kargil',95);
INSERT INTO Hub VALUES(203,'Kasauli City Bus Station / ISBT','Kasauli',96);
INSERT INTO Hub VALUES(204,'Kasauli Railway Station','Kasauli',96);
INSERT INTO Hub VALUES(205,'Kausani City Bus Station / ISBT','Kausani',97);
INSERT INTO Hub VALUES(206,'Kausani Railway Station','Kausani',97);
INSERT INTO Hub VALUES(207,'Keonjhar City Bus Station / ISBT','Keonjhar',98);
INSERT INTO Hub VALUES(208,'Keonjhar Railway Station','Keonjhar',98);
INSERT INTO Hub VALUES(209,'Varanasi International Airport','Varanasi',99);
INSERT INTO Hub VALUES(210,'Varanasi City Bus Station / ISBT','Varanasi',99);
INSERT INTO Hub VALUES(211,'Varanasi Railway Station','Varanasi',99);
INSERT INTO Hub VALUES(212,'Khajuraho City Bus Station / ISBT','Khajuraho',100);
INSERT INTO Hub VALUES(213,'Khajuraho Railway Station','Khajuraho',100);
INSERT INTO Hub VALUES(214,'Vibhav Nagar','Vibhav Nagar Chowk',1);
INSERT INTO Hub VALUES(215,'Anram Chowk','Agra',1);
INSERT INTO Hub VALUES(216,'Bhagwan Talkies','Bhagwan Cinema',1);
INSERT INTO Hub VALUES(217,'Ram Bagh Hero Showroom','Ram Bagh',1);
INSERT INTO Hub VALUES(218,'Clarks Inn Hotel','Sikandra',1);
INSERT INTO Hub VALUES(219,'Nari Niketan','Ram Bagh',1);
INSERT INTO Hub VALUES(220,'Suraj Vihar','Agra',1);
INSERT INTO Hub VALUES(221,'Suvidha Centre','Paldi',2);
INSERT INTO Hub VALUES(222,'Habaitpur Road','Thaltej',2);
INSERT INTO Hub VALUES(223,'Sanjivani Hospital','Vastrapur',2);
INSERT INTO Hub VALUES(224,'Ioc Road','Chandkheda',2);
INSERT INTO Hub VALUES(225,'Hatkeshwar Circle','Hatkeshwar',2);
INSERT INTO Hub VALUES(226,'India Colony Road','Bapu Nagar',2);
INSERT INTO Hub VALUES(227,'Amrapali Shopping Mall','Bopal',2);
INSERT INTO Hub VALUES(228,'Sagar Circular Road','Ajmer',3);
INSERT INTO Hub VALUES(229,'Makarwali Road','Vaishali Nagar',3);
INSERT INTO Hub VALUES(230,'Pushkar Road','Ajmer',3);
INSERT INTO Hub VALUES(231,'Nasirabad Road','Adarsh Nagar',3);
INSERT INTO Hub VALUES(232,'Kutchery Road','Ajmer',3);
INSERT INTO Hub VALUES(233,'Pushkar Road','Ajmer',3);
INSERT INTO Hub VALUES(234,'Pushkar Road','Ajmer',3);
INSERT INTO Hub VALUES(235,'Alappuzha District Hospital',' Alappuzzha Municipal Corporation',4);
INSERT INTO Hub VALUES(236,'Maj. Matthews Chowk','Cherthala',4);
INSERT INTO Hub VALUES(237,'Thondankulangara','Thathampally',4);
INSERT INTO Hub VALUES(238,'Mathilakom','Cherthala',4);
INSERT INTO Hub VALUES(239,'Chengannur','Mulakuzha',4);
INSERT INTO Hub VALUES(240,'Agra Road','Bhiwandi',5);
INSERT INTO Hub VALUES(241,'Evershine Main Gate','Vasai East',5);
INSERT INTO Hub VALUES(242,'Goregaon Link Road','Mulund West',5);
INSERT INTO Hub VALUES(243,'L Mehta Rd.','Vile Parle West',5);
INSERT INTO Hub VALUES(244,'Sheetal Nagar','Mira Road',5);
INSERT INTO Hub VALUES(245,'Naupada','Thane West',5);
INSERT INTO Hub VALUES(246,'SJ Mehta Colony','Chembur West',5);
INSERT INTO Hub VALUES(247,'Taskant Marg','Allahabad',6);
INSERT INTO Hub VALUES(248,'Strachey Roadd','Civil Lines',6);
INSERT INTO Hub VALUES(249,'Strachey Road','Civil Lines',6);
INSERT INTO Hub VALUES(250,'Mandir Civil Lines','Elgin Road',6);
INSERT INTO Hub VALUES(251,'Panna LAL Road','Allahabad City',6);
INSERT INTO Hub VALUES(252,'Tagore town','Tagore Town',6);
INSERT INTO Hub VALUES(253,'Orbit Mall, Next to City Police Chowki','Muri Road',6);
INSERT INTO Hub VALUES(254,'Almora City Place','Almora Uttranchal',7);
INSERT INTO Hub VALUES(255,'Almora Tourism H.O.','Almora Uttranchal',7);
INSERT INTO Hub VALUES(256,'Almora Archaeological Bldg.','263601, Almora',7);
INSERT INTO Hub VALUES(257,'Ranikhet Tourism','Almora',7);
INSERT INTO Hub VALUES(258,'Raniketh Lodge','Almora',7);
INSERT INTO Hub VALUES(259,'Almora Medicines','Almora Uttranchal',7);
INSERT INTO Hub VALUES(260,'Verseran Pahalgam','Dhawtoo',8);
INSERT INTO Hub VALUES(261,'Sarnul','Anantnag City',8);
INSERT INTO Hub VALUES(262,'Main Market','Anantnag',8);
INSERT INTO Hub VALUES(263,'Main Chowk','Achabal',8);
INSERT INTO Hub VALUES(264,'A Block Market','Ranjit Avenue',9);
INSERT INTO Hub VALUES(265,'Circular Road','Amritsar Bus Stand',9);
INSERT INTO Hub VALUES(266,'Ranjit Avenue','Amritsar',9);
INSERT INTO Hub VALUES(267,'Trilium Mall','Amritsar',9);
INSERT INTO Hub VALUES(268,'Maqbool Road','Amritsar Gpo',9);
INSERT INTO Hub VALUES(269,'Batala Road','Amritsar',9);
INSERT INTO Hub VALUES(270,'Bank Of Amristar (Main Branch)','Rani Ka Bagh',9);
INSERT INTO Hub VALUES(271,'Goregaon Link Road','Mulund West',10);
INSERT INTO Hub VALUES(272,'L Mehta Rd','Vile Parle West',10);
INSERT INTO Hub VALUES(273,'Sheetal Nagar','Mira Road',10);
INSERT INTO Hub VALUES(274,'Naupada','Thane West',10);
INSERT INTO Hub VALUES(275,'SJ Mehta Colony','Chembur West',10);
INSERT INTO Hub VALUES(276,'Mini Seashore Road','Vashi',10);
INSERT INTO Hub VALUES(277,'Manpada','Thane West',10);
INSERT INTO Hub VALUES(278,'P. C. Colony','Kankarbagh',11);
INSERT INTO Hub VALUES(279,'New Bypass Road','Kankarbagh',11);
INSERT INTO Hub VALUES(280,'Kankarbagh','Kankarbagh',11);
INSERT INTO Hub VALUES(281,'Shantikunj','Phulwarisharif',11);
INSERT INTO Hub VALUES(282,'Ioc Road Sipara','Patna',11);
INSERT INTO Hub VALUES(283,'P Verma','Dak Bunglow Road',11);
INSERT INTO Hub VALUES(284,'Gandhi Setu','Malahi Pakdi Chowk',11);
INSERT INTO Hub VALUES(285,'Agra Road','Bhiwandi',12);
INSERT INTO Hub VALUES(286,'Goregaon Link Road','Mulund West',12);
INSERT INTO Hub VALUES(287,'L Mehta Rd','Vile Parle West',12);
INSERT INTO Hub VALUES(288,'Sheetal Nagar','Mira Road',12);
INSERT INTO Hub VALUES(289,'Naupada','Thane West',12);
INSERT INTO Hub VALUES(290,'SJ Mehta colony','Chembur West',12);
INSERT INTO Hub VALUES(291,'Sector No 01','New Panvel',12);
INSERT INTO Hub VALUES(292,'Mini Seashore Road','Vashi',13);
INSERT INTO Hub VALUES(293,'Mandpeshwar','Borivali West',13);
INSERT INTO Hub VALUES(294,'L Mehta Rd','Vile Parle West',13);
INSERT INTO Hub VALUES(295,'Sector 17','Vashi',13);
INSERT INTO Hub VALUES(296,'Sheetal Nagar','Mira Road',13);
INSERT INTO Hub VALUES(297,'Panch Pakhadi','Thane West',13);
INSERT INTO Hub VALUES(298,'Naupada','Thane West',13);
INSERT INTO Hub VALUES(299,'Korlagunta Bypass','Korlagunta',14);
INSERT INTO Hub VALUES(300,'Devendra Talkies','Bhavani Nagar',14);
INSERT INTO Hub VALUES(301,'K T Road','Tirupati',14);
INSERT INTO Hub VALUES(302,'Bhavani Nagar','Bhavani Nagar',14);
INSERT INTO Hub VALUES(303,'Vodafone Head Office','Tilak Road',14);
INSERT INTO Hub VALUES(304,'And Reddy Colony','Tirupati',14);
INSERT INTO Hub VALUES(305,'Bank Street','Reddy&Reddy Colony',14);
INSERT INTO Hub VALUES(306,'Kakaji Colony','Hanamkonda',15);
INSERT INTO Hub VALUES(307,'Pinjarala Street','Hanamkonda',15);
INSERT INTO Hub VALUES(308,'Kancharakunta','Hanamkonda',15);
INSERT INTO Hub VALUES(309,'Hanamkonda','Hanamkonda',15);
INSERT INTO Hub VALUES(310,'Deshaipet Road','Pochamma Maidan',15);
INSERT INTO Hub VALUES(311,'Kishanpura','Hanamkonda',15);
INSERT INTO Hub VALUES(312,'Road No 1','Desaipet',15);
INSERT INTO Hub VALUES(313,'Parikrama Mg','Nayaghat',16);
INSERT INTO Hub VALUES(314,'Sal Peth','Ilkal',17);
INSERT INTO Hub VALUES(315,'Extension Area','Bagalkot',17);
INSERT INTO Hub VALUES(316,'Kalyan Mantap','Badami',17);
INSERT INTO Hub VALUES(317,'General Post Office','Guledgud Bagalkot',17);
INSERT INTO Hub VALUES(318,' MJ Museum','Navanagar Bagalkot',17);
INSERT INTO Hub VALUES(319,'Balasore Town','Balia',18);
INSERT INTO Hub VALUES(320,'Suelpur','Balasore',18);
INSERT INTO Hub VALUES(321,'Balasore','Balasore',18);
INSERT INTO Hub VALUES(322,'Stadium Complex','Balasore',18);
INSERT INTO Hub VALUES(323,'Umariya Main Road','Umariya',19);
INSERT INTO Hub VALUES(324,'Shahpura Road','Umariya',19);
INSERT INTO Hub VALUES(325,'Pali','Umariya',19);
INSERT INTO Hub VALUES(326,'Main Road','Manpur Umariya',19);
INSERT INTO Hub VALUES(327,'Ring Road','Rajivnagar',20);
INSERT INTO Hub VALUES(328,'Pramathi School','Kuvempunagar',20);
INSERT INTO Hub VALUES(329,'Siddiqui Nagar','Banni Mantap',20);
INSERT INTO Hub VALUES(330,'Mahathma Gandhi','M G Road',20);
INSERT INTO Hub VALUES(331,'3rd Cross St','Jayalakshmipuram',20);
INSERT INTO Hub VALUES(332,'Chunchanagiri Road','Kuvempunagar',20);
INSERT INTO Hub VALUES(333,'Vivekananda Road','Yadavagiri',20);
INSERT INTO Hub VALUES(334,'Coonoor Road','Ooty',21);
INSERT INTO Hub VALUES(335,'Ettis Road','Ooty',21);
INSERT INTO Hub VALUES(336,'Mountain School Road','Ooty',21);
INSERT INTO Hub VALUES(337,'Main Road','Finger Post',21);
INSERT INTO Hub VALUES(338,'Coonoor Road','Nilgiris',21);
INSERT INTO Hub VALUES(339,'Galli Chowk','Basavanagalli Belgaum',22);
INSERT INTO Hub VALUES(340,'Angol Main Road','Angol Belgaum',22);
INSERT INTO Hub VALUES(341,'Galli Chowk','Gondhali Galli Belgaum',22);
INSERT INTO Hub VALUES(342,'Masoom Medicals','Khade Bazaar',22);
INSERT INTO Hub VALUES(343,'Civil Hospital Road','Belgaum',22);
INSERT INTO Hub VALUES(344,'Mahadwar Road','Belgaum',22);
INSERT INTO Hub VALUES(345,'Main Road','Belgaum Nehru Nagar',22);
INSERT INTO Hub VALUES(346,' Municipal Council','Matheran',23);
INSERT INTO Hub VALUES(347,'Khb Colony','Basaveshwara Nagar',24);
INSERT INTO Hub VALUES(348,'Bangalore Tourism H.Q.','Bannerghatta Road',24);
INSERT INTO Hub VALUES(349,'Block Hrbr Layout','Kalyan Nagar',24);
INSERT INTO Hub VALUES(350,'Outer Ring Road Police Chowki','Old Airport Road',24);
INSERT INTO Hub VALUES(351,'Bellary Road','Hebbal',24);
INSERT INTO Hub VALUES(352,'Sector No.5','Hsr Layout',24);
INSERT INTO Hub VALUES(353,'Varthur Road','Marathahalli',24);
INSERT INTO Hub VALUES(354,'Kapoorthala Crossing','Mahanagar',25);
INSERT INTO Hub VALUES(355,'Rana Pratap Marg','Hazratganj',25);
INSERT INTO Hub VALUES(356,'Nabibullah Road','Daliganj',25);
INSERT INTO Hub VALUES(357,'Safdarjung Railway Crossing','Rajaji Puram',25);
INSERT INTO Hub VALUES(358,'ICICI Bank (Main Branch)','Gomti Nagar',25);
INSERT INTO Hub VALUES(359,'Baldi Khera Chouraha','Kanpur Road',25);
INSERT INTO Hub VALUES(360,'Townhall Public School','Aliganj',25);
INSERT INTO Hub VALUES(361,'Chapra Main Road','Muzaffarpur',26);
INSERT INTO Hub VALUES(362,'Juran Chapra Road','Muzaffarpur',26);
INSERT INTO Hub VALUES(363,'Muzaffarpur Police HQ','Muzaffarpur',26);
INSERT INTO Hub VALUES(364,'Muzaffarpur Minorities Research Institute','Muzaffarpur',26);
INSERT INTO Hub VALUES(365,'Railway Police H.Q.','Muzaffarpur',26);
INSERT INTO Hub VALUES(366,'Kanholi','Muzaffarpur',26);
INSERT INTO Hub VALUES(367,'Cross 3rd St.','Anna Nagar Madurai',27);
INSERT INTO Hub VALUES(368,'Anna Nagar','Madurai',27);
INSERT INTO Hub VALUES(369,'Post Office Road','Tallakulam',27);
INSERT INTO Hub VALUES(370,'T.Road Chowk','Chinna Chokkikulam',27);
INSERT INTO Hub VALUES(371,'West 1st St.','K K Nagar',27);
INSERT INTO Hub VALUES(372,'Salai','Madurai Collector',27);
INSERT INTO Hub VALUES(373,'Anna Nagar','Madurai',27);
INSERT INTO Hub VALUES(374,'Mini Seashore Road','Vashi',28);
INSERT INTO Hub VALUES(375,'Mandpeshwar','Borivali West',28);
INSERT INTO Hub VALUES(376,'Jungle Mangal Road','Bhandup West',28);
INSERT INTO Hub VALUES(377,'Sector 17','Vashi',28);
INSERT INTO Hub VALUES(378,'Jijabai Road','Andheri East',28);
INSERT INTO Hub VALUES(379,'Panch Pakhadi','Thane West',28);
INSERT INTO Hub VALUES(380,'Birla College Road','Kalyan City',28);
INSERT INTO Hub VALUES(381,'Station Road','Bhalki',29);
INSERT INTO Hub VALUES(382,'Ganesh Maidan','Fort Road Bidar',29);
INSERT INTO Hub VALUES(383,'Naubad','Bidar Bazar',29);
INSERT INTO Hub VALUES(384,'Nr Bus Stop','Humnabad Bazar Bidar',29);
INSERT INTO Hub VALUES(385,'BJ Road','Railway Station Bidar',29);
INSERT INTO Hub VALUES(386,'Ganesh Maidan','Bidar',29);
INSERT INTO Hub VALUES(387,'Janawada Road','Udgir Road Bidar',29);
INSERT INTO Hub VALUES(388,'Mini Seashore Road','Vashi',30);
INSERT INTO Hub VALUES(389,'Mandpeshwar','Borivali West',30);
INSERT INTO Hub VALUES(390,'Sector 17','Vashi',30);
INSERT INTO Hub VALUES(391,'Jungle Mangal Road','Bhandup West',30);
INSERT INTO Hub VALUES(392,'Panch Pakhadi','Thane West',30);
INSERT INTO Hub VALUES(393,'Jijabai Road','Andheri East',30);
INSERT INTO Hub VALUES(394,'Birla College Road','Kalyan City',30);
INSERT INTO Hub VALUES(395,'Sector No 01','New Panvel',31);
INSERT INTO Hub VALUES(396,'Mini Seashore Road','Vashi',31);
INSERT INTO Hub VALUES(397,'Mandpeshwar','Borivali West',31);
INSERT INTO Hub VALUES(398,'Jungle Mangal Road','Bhandup West',31);
INSERT INTO Hub VALUES(399,'Sector 17','Vashi',31);
INSERT INTO Hub VALUES(400,'Jijabai Road','Andheri East',31);
INSERT INTO Hub VALUES(401,'Panch Pakhadi','Thane West',31);
INSERT INTO Hub VALUES(402,'Kendriya Vidyalay','Kankarbagh',32);
INSERT INTO Hub VALUES(403,'Panchahtti Road','Bodhgaya',32);
INSERT INTO Hub VALUES(404,'Hospital Chowk','Balangir',33);
INSERT INTO Hub VALUES(405,'Kandpali','',33);
INSERT INTO Hub VALUES(406,'Panch Pakhadi','Thane West',34);
INSERT INTO Hub VALUES(407,'Goregaon Link Road','Mulund West',34);
INSERT INTO Hub VALUES(408,'L Mehta','Vile Parle West',34);
INSERT INTO Hub VALUES(409,'Sheetal Nagar','Mira Road',34);
INSERT INTO Hub VALUES(410,'Naupada','Thane West',34);
INSERT INTO Hub VALUES(411,'MG Road','Chembur West',34);
INSERT INTO Hub VALUES(412,'Sector No 01','New Panvel',34);
INSERT INTO Hub VALUES(413,'Chamba','Chamba',35);
INSERT INTO Hub VALUES(414,'Main Rd','Sultanpur',35);
INSERT INTO Hub VALUES(415,'Dalhousie Road','Chamba',35);
INSERT INTO Hub VALUES(416,'Power Station','2 Karian, Chamba',35);
INSERT INTO Hub VALUES(417,'P.O Bakloh','Kakira',35);
INSERT INTO Hub VALUES(418,'Diamond Harbour Rd','Joka, Kolkata',36);
INSERT INTO Hub VALUES(419,'Bhupen Bose Avenue','Kolkata',36);
INSERT INTO Hub VALUES(420,'Bypass Mukundapur Road','Bidhan Sarani, Kolkata',36);
INSERT INTO Hub VALUES(421,'Barrackpore Trunk Road','Kolkata',36);
INSERT INTO Hub VALUES(422,'Andul Road','Howrah, Kolkata',36);
INSERT INTO Hub VALUES(423,'Park Street',' Park Circus, Kolkata',36);
INSERT INTO Hub VALUES(424,'Salt Lake City','Next to Keshtopur, Kolkata',36);
INSERT INTO Hub VALUES(425,'NH Adminstrative Site','Panchkula Sector 25',37);
INSERT INTO Hub VALUES(426,'Puda Mohali','Sector 55, Chandigarh',37);
INSERT INTO Hub VALUES(427,'Kake da Dhaba','Panchkula Sector 20, Chandigarh',37);
INSERT INTO Hub VALUES(428,'Indian Archaeological Survey H.Q.','Panchkula Sector 11, Chandigarh',37);
INSERT INTO Hub VALUES(429,'Canara Bank Head Office','Chandigarh Sector 34a',37);
INSERT INTO Hub VALUES(430,'Mehndi Road','Zirakpur',37);
INSERT INTO Hub VALUES(431,'Mehul Singh Akhada','Chandigarh Sector 16',37);
INSERT INTO Hub VALUES(432,'Mini Seashore Road','Vashi',38);
INSERT INTO Hub VALUES(433,'L Mehta Rd.','Vile Parle West',38);
INSERT INTO Hub VALUES(434,'Mandpeshwar','Borivali West',38);
INSERT INTO Hub VALUES(435,'Sheetal Nagar','Mira Road',38);
INSERT INTO Hub VALUES(436,'Goregaon Link Road','Mulund West',38);
INSERT INTO Hub VALUES(437,'Marys Church','Vashi',38);
INSERT INTO Hub VALUES(438,'Naupada','Thane West',38);
INSERT INTO Hub VALUES(439,'Panch Pakhadi','Thane West',39);
INSERT INTO Hub VALUES(440,'Mini Seashore Road','Vashi',39);
INSERT INTO Hub VALUES(441,'Mandpeshwar','Borivali West',39);
INSERT INTO Hub VALUES(442,'Jungle Mangal Road','Bhandup West',39);
INSERT INTO Hub VALUES(443,'Marys Church','Vashi',39);
INSERT INTO Hub VALUES(444,'Jijabai Road','Andheri East',39);
INSERT INTO Hub VALUES(445,'Birla College Road','Kalyan City',39);
INSERT INTO Hub VALUES(446,'Big Street','Triplicane',40);
INSERT INTO Hub VALUES(447,'Taramani Link Road','Velacheri',40);
INSERT INTO Hub VALUES(448,'Tambaram West','Tambaram West',40);
INSERT INTO Hub VALUES(449,'Lakshmipathy Salai','Egmore',40);
INSERT INTO Hub VALUES(450,'Main Road','Okkiyam Thuraipakkam',40);
INSERT INTO Hub VALUES(451,'Lawyer Jaganathan Street','Guindy',40);
INSERT INTO Hub VALUES(452,'Nagar 2nd Street','Kovilambakkam',40);
INSERT INTO Hub VALUES(453,'East Car Street','Chidambaram',41);
INSERT INTO Hub VALUES(454,'P Koil Street','Chidambaram',41);
INSERT INTO Hub VALUES(455,'Malai Katti','Chidambaram',41);
INSERT INTO Hub VALUES(456,'Kanagasabai Nagar','Chidambaram',41);
INSERT INTO Hub VALUES(457,'Theradi Street','Chidambaram',41);
INSERT INTO Hub VALUES(458,'Annamalai Nagar','Chidambaram',41);
INSERT INTO Hub VALUES(459,'Road Three Roads','Palapatti Salem',42);
INSERT INTO Hub VALUES(460,'Vidyalaya Road','Salem North',42);
INSERT INTO Hub VALUES(461,'Shastri Nagar','Annadanapatti',42);
INSERT INTO Hub VALUES(462,'T.V.K. Road','Ammapettai',42);
INSERT INTO Hub VALUES(463,'2nd Agragaram','Salem',42);
INSERT INTO Hub VALUES(464,'Cherry Road','Salem',42);
INSERT INTO Hub VALUES(465,'Thirumagal Bye Pass','Suramangalam',42);
INSERT INTO Hub VALUES(466,'Avarampalayam Road','Sidhapudur',43);
INSERT INTO Hub VALUES(467,'Trichy Road','Singanallur',43);
INSERT INTO Hub VALUES(468,'Cowley Brown','R S Puram',43);
INSERT INTO Hub VALUES(469,'Nanjappa Nagar','Singanallur',43);
INSERT INTO Hub VALUES(470,'Kovai Road','Annur',43);
INSERT INTO Hub VALUES(471,'Sathy Road','Saravanampatti',43);
INSERT INTO Hub VALUES(472,'Saibaba Colony','Kuppakonanpudur',43);
INSERT INTO Hub VALUES(473,'Edfort Rajaji Nagar','Coonoor',44);
INSERT INTO Hub VALUES(474,'Mount Road','Coonoor',44);
INSERT INTO Hub VALUES(475,'Mountbatten Road','Coonoor',44);
INSERT INTO Hub VALUES(476,'Balaclava Hill','Coonoor',44);
INSERT INTO Hub VALUES(477,'Woodcote Road','Coonoor RS',44);
INSERT INTO Hub VALUES(478,'Wellington','Coonoor',44);
INSERT INTO Hub VALUES(479,'Kambisholai Road','Coonoor RS',44);
INSERT INTO Hub VALUES(480,'Mini Seashore Road','Vashi',45);
INSERT INTO Hub VALUES(481,'Mandpeshwar','Borivali West',45);
INSERT INTO Hub VALUES(482,'Jungle Mangal Road','Bhandup West',45);
INSERT INTO Hub VALUES(483,'Marys Church','Vashi',45);
INSERT INTO Hub VALUES(484,'Jijabai Road','Andheri East',45);
INSERT INTO Hub VALUES(485,'Panch Pakhadi','Thane West',45);
INSERT INTO Hub VALUES(486,'Behind Axis','Kharghar Sector 4',45);
INSERT INTO Hub VALUES(487,'K P Vallon Road','Kadavanthara',46);
INSERT INTO Hub VALUES(488,'Airpot Junction','Athani Ernakulam',46);
INSERT INTO Hub VALUES(489,'Aims Ponekkara','Kochi',46);
INSERT INTO Hub VALUES(490,'Aims Ponekkara','Kochi',46);
INSERT INTO Hub VALUES(491,'Panayappally','Kochi',46);
INSERT INTO Hub VALUES(492,'H Byepass Chakaraparambu','Vennala',46);
INSERT INTO Hub VALUES(493,'Bye Pass Junction','Aluva',46);
INSERT INTO Hub VALUES(494,'Kathagola Road','Manglabag',47);
INSERT INTO Hub VALUES(495,'Medical Road','Medical College',47);
INSERT INTO Hub VALUES(496,'Niladri Vihar','Nayabazar',47);
INSERT INTO Hub VALUES(497,'Om Suvam Hospital','College Square',47);
INSERT INTO Hub VALUES(498,'Bidanasi','Cuttack',47);
INSERT INTO Hub VALUES(499,'Link Road Square','Madhupatna',47);
INSERT INTO Hub VALUES(500,'Mini Seashore Road','Vashi',48);
INSERT INTO Hub VALUES(501,'Mandpeshwar','Borivali West',48);
INSERT INTO Hub VALUES(502,'Marys Church','Vashi',48);
INSERT INTO Hub VALUES(503,'Jungle Mangal Road','Bhandup West',48);
INSERT INTO Hub VALUES(504,'Panch Pakhadi','Thane West',48);
INSERT INTO Hub VALUES(505,'Jijabai Road','Andheri East',48);
INSERT INTO Hub VALUES(506,'Birla College Road','Kalyan City',48);
INSERT INTO Hub VALUES(507,'Court Rd','Dalhousie Cantt',49);
INSERT INTO Hub VALUES(508,'Memun','Dalhousie Cantt',49);
INSERT INTO Hub VALUES(509,'Khajjar Road','Dalhousie',49);
INSERT INTO Hub VALUES(510,'Devka Road','Daman',51);
INSERT INTO Hub VALUES(511,'Dunetha Road','Dunetha',51);
INSERT INTO Hub VALUES(512,'Daman','Daman',51);
INSERT INTO Hub VALUES(513,'Tin Bati','Daman',51);
INSERT INTO Hub VALUES(514,'M G Road','Daman',51);
INSERT INTO Hub VALUES(515,'Kachigam','Daman',51);
INSERT INTO Hub VALUES(516,'Kuntha Road','Dunetha',51);
INSERT INTO Hub VALUES(517,'Mishra Tola','Darbhanga',52);
INSERT INTO Hub VALUES(518,'Darbhanga','Darbhanga',52);
INSERT INTO Hub VALUES(519,'Donar Road','D M C',52);
INSERT INTO Hub VALUES(520,'G. M. Road','Darbhanga',52);
INSERT INTO Hub VALUES(521,'Naka No.6','Darbhanga',52);
INSERT INTO Hub VALUES(522,'Shastri Nagar','Garsa',53);
INSERT INTO Hub VALUES(523,'Govt Circuit House','Kullu',53);
INSERT INTO Hub VALUES(524,'Dhalpur','Kullu',53);
INSERT INTO Hub VALUES(525,'Village Kalhely','Bajahara',53);
INSERT INTO Hub VALUES(526,'Hathithan','Bhuntar',53);
INSERT INTO Hub VALUES(527,'Hilcard Road','Darjeeling',54);
INSERT INTO Hub VALUES(528,'Sadar Thana','Darjeeling Bazar',54);
INSERT INTO Hub VALUES(529,'NH 55 Police Chowki','Tindharia',54);
INSERT INTO Hub VALUES(530,'Canal Road','Dehradun City',55);
INSERT INTO Hub VALUES(531,'High School','Dehradun City',55);
INSERT INTO Hub VALUES(532,'Green Hostel','Prem Nagar',55);
INSERT INTO Hub VALUES(533,'Chakrata Road','Dehradun City',55);
INSERT INTO Hub VALUES(534,'Haridwar Road','Dehradun City',55);
INSERT INTO Hub VALUES(535,'Chakrata Road','Dehradun Gpo',55);
INSERT INTO Hub VALUES(536,'Mussorie Diversion Road','Rajpur',55);
INSERT INTO Hub VALUES(537,'17 Kiran Garden','Uttam Nagar',56);
INSERT INTO Hub VALUES(538,'Marg','Vasundhara Enclave',56);
INSERT INTO Hub VALUES(539,'Kalkaji Police Station','Kalkaji',56);
INSERT INTO Hub VALUES(540,'Lok Puri',', Gurgaon Sector 56',56);
INSERT INTO Hub VALUES(541,'Main Najafgarh Road','Uttam Nagar',56);
INSERT INTO Hub VALUES(542,'Faridabad Police Chowki','Faridabad',56);
INSERT INTO Hub VALUES(543,'Anand Vihar ISBT','Kaushambi',56);
INSERT INTO Hub VALUES(544,'Bawan Bigha','Deoghar',57);
INSERT INTO Hub VALUES(545,'ICC Tower','Deoghar',57);
INSERT INTO Hub VALUES(546,'K.K Stadium','Deoghar',57);
INSERT INTO Hub VALUES(547,'Jalsar Road','Deoghar',57);
INSERT INTO Hub VALUES(548,'Kunda Deoghar','Kunda',57);
INSERT INTO Hub VALUES(549,'Srikant Road','Deoghar',57);
INSERT INTO Hub VALUES(550,'Jora Fatak Road','Dhanbad',58);
INSERT INTO Hub VALUES(551,'Katas Road','Bank Rd, Dhanbad',58);
INSERT INTO Hub VALUES(552,'Polytechnic Road','Dhanbad',58);
INSERT INTO Hub VALUES(553,'Bartand Road','Shastri Nagar',58);
INSERT INTO Hub VALUES(554,'Main Road','Saraidhela',58);
INSERT INTO Hub VALUES(555,'Court More','Dhanbad',58);
INSERT INTO Hub VALUES(556,'Ram Nagar','Dharamshala',59);
INSERT INTO Hub VALUES(557,'Lalehar Road','Dharamsala',59);
INSERT INTO Hub VALUES(558,'Bypass Road','Dharmapuri',60);
INSERT INTO Hub VALUES(559,'R Sundaram Street','Dharmapuri',60);
INSERT INTO Hub VALUES(560,'By Pass Road','Dharmapuri',60);
INSERT INTO Hub VALUES(561,'Chetty Street','Dharmapuri',60);
INSERT INTO Hub VALUES(562,'SH-57 Main.Office','Digha',61);
INSERT INTO Hub VALUES(563,'Fort Road','Diu',62);
INSERT INTO Hub VALUES(564,'State Highway','Dwarka',63);
INSERT INTO Hub VALUES(565,'Rukshmani Mandir Road','Dwarka',63);
INSERT INTO Hub VALUES(566,'Side Circuit House','Dwarka',63);
INSERT INTO Hub VALUES(567,'Giridih Chowk','Giridih',65);
INSERT INTO Hub VALUES(568,'Road Gandhi Chowk','Giridih',65);
INSERT INTO Hub VALUES(569,'Giridih Chowk','Giridih',65);
INSERT INTO Hub VALUES(570,'Gaddi Mohalla','Giridih',65);
INSERT INTO Hub VALUES(571,'Main Road Boro Pachamba','Pachamba',65);
INSERT INTO Hub VALUES(572,'Bishanpur Pachamba Road','Pachamba',65);
INSERT INTO Hub VALUES(580,'College Road Ankola','Karwar',67);
INSERT INTO Hub VALUES(581,'Kajubag Colony','Kajubag',67);
INSERT INTO Hub VALUES(582,'Bunder Road Bhatkal','Karwar',67);
INSERT INTO Hub VALUES(583,'Shifa Colony Bhatkal','Karwar',67);
INSERT INTO Hub VALUES(584,'M.g Road','Karwar',67);
INSERT INTO Hub VALUES(585,'Mg Rd Police Chowki','Karwar',67);
INSERT INTO Hub VALUES(586,'Karwar Colony','Karwar',67);
INSERT INTO Hub VALUES(587,'Gokhale Road','Maharanipeta',68);
INSERT INTO Hub VALUES(588,'Kgh Down Rd','Maharanipeta',68);
INSERT INTO Hub VALUES(589,'Mens Hostel Road','Maharanipeta',68);
INSERT INTO Hub VALUES(590,'Lake View Rd.','Dwaraka Nagar Visakhapatnam',68);
INSERT INTO Hub VALUES(591,'Kgh Out Gate','Maharanipeta',68);
INSERT INTO Hub VALUES(592,'Marripalem Main Road','Marripalem',68);
INSERT INTO Hub VALUES(593,'Annamma Complex','Sriharipuram',68);
INSERT INTO Hub VALUES(594,'Baramulla Dist, Gulmarg Road','Gulmarg',69);
INSERT INTO Hub VALUES(595,'New Colony Road','Baramulla Dist, Gulmarg',69);
INSERT INTO Hub VALUES(596,'Mazbugh Road','Baramulla Dist, Gulmarg',69);
INSERT INTO Hub VALUES(597,'J & K Tourism','Baramulla Dist, Gulmarg',69);
INSERT INTO Hub VALUES(598,'Fruit Mandi','Baramulla Dist, Gulmarg',69);
INSERT INTO Hub VALUES(599,'Main Chowk','Baramulla Dist, Gulmarg',69);
INSERT INTO Hub VALUES(600,'Sector 20','Kopar Khairane',70);
INSERT INTO Hub VALUES(601,'Mini Seashore Road','Vashi',70);
INSERT INTO Hub VALUES(602,'Mandpeshwar','Borivali West',70);
INSERT INTO Hub VALUES(603,'Sector 17','Vashi',70);
INSERT INTO Hub VALUES(604,'Jungle Mangal Road','Bhandup West',70);
INSERT INTO Hub VALUES(605,'Panch Pakhadi','Thane West',70);
INSERT INTO Hub VALUES(606,'Jijabai Road','Andheri East',70);
INSERT INTO Hub VALUES(607,'Baradari Crossing','Morar',71);
INSERT INTO Hub VALUES(608,'Railway Police H.Q.','Gwalior',71);
INSERT INTO Hub VALUES(609,'Raghvendra Nagar','Gwalior City',71);
INSERT INTO Hub VALUES(610,'Sindh Petrol Pump','Thatipur',71);
INSERT INTO Hub VALUES(611,'Sindhi Colony Road','Lashkar',71);
INSERT INTO Hub VALUES(612,'Nagar Main Road','Gandhi Nagar',71);
INSERT INTO Hub VALUES(613,'Jah Hospital','Lashkar',71);
INSERT INTO Hub VALUES(614,'LIC H.O.','Tb Dam Road',72);
INSERT INTO Hub VALUES(615,'Shanbhag Circle','Patel Nagar',72);
INSERT INTO Hub VALUES(616,'J P Nagar','Hospet',72);
INSERT INTO Hub VALUES(617,'B Dam Road','Hospet',72);
INSERT INTO Hub VALUES(618,'ICICI Bank H.Q.','Hospet',72);
INSERT INTO Hub VALUES(619,'Raithabhavan Hu','Neharu Colony',72);
INSERT INTO Hub VALUES(620,'Main Road','Hospet',72);
INSERT INTO Hub VALUES(621,'Main Crossing','Shivalik Nagar',73);
INSERT INTO Hub VALUES(622,'Phase-3 Shivaliks','Shivalik Nagar',73);
INSERT INTO Hub VALUES(623,'Sidcul Nagar','Haridwar',73);
INSERT INTO Hub VALUES(624,'Ranipur More','Haridwar',73);
INSERT INTO Hub VALUES(625,'Main Roorkee','Haridwar',73);
INSERT INTO Hub VALUES(626,'Saptrishi Link','Haridwar',73);
INSERT INTO Hub VALUES(627,'Shankar Mutt','Kr Puram Hassan',74);
INSERT INTO Hub VALUES(628,'KR Sweets','Sampige Road Hassan',74);
INSERT INTO Hub VALUES(629,'Govt College Road','Hassan',74);
INSERT INTO Hub VALUES(630,'Kuvempunagar','Hassan',74);
INSERT INTO Hub VALUES(631,'Gandhi Road Mysore','Hassan',74);
INSERT INTO Hub VALUES(632,'Sampige Road','Kr Puram Hassan',74);
INSERT INTO Hub VALUES(633,'R C Road','Hassan',74);
INSERT INTO Hub VALUES(634,'NH-100 Police Chowki','Hazaribagh',75);
INSERT INTO Hub VALUES(635,'New Forest','Hazaribagh',75);
INSERT INTO Hub VALUES(636,'Dharmapuri','Pennagaram',76);
INSERT INTO Hub VALUES(637,'Dharmapuri Collectorate Road','Dharmapuri',76);
INSERT INTO Hub VALUES(638,'Main Road','Dharmapuri',76);
INSERT INTO Hub VALUES(639,'Main Road','Paupparapatti',76);
INSERT INTO Hub VALUES(640,'Palacode Main Road','Paupparapatti',76);
INSERT INTO Hub VALUES(641,'M.g.road','Palacode',76);
INSERT INTO Hub VALUES(642,'Street','Dharmapuri',76);
INSERT INTO Hub VALUES(643,'Mini Seashore Road','Vashi',77);
INSERT INTO Hub VALUES(644,'Mandpeshwar','Borivali West',77);
INSERT INTO Hub VALUES(645,'Jungle Mangal Road','Bhandup West',77);
INSERT INTO Hub VALUES(646,'Sector 17','Vashi',77);
INSERT INTO Hub VALUES(647,'Jijabai Road','Andheri East',77);
INSERT INTO Hub VALUES(648,'Panch Pakhadi','Thane West',77);
INSERT INTO Hub VALUES(649,'Birla College Road','Kalyan City',77);
INSERT INTO Hub VALUES(650,'Chettinad Restaurant','New Bowenpally',78);
INSERT INTO Hub VALUES(651,'Tech. Village','Serilingampally',78);
INSERT INTO Hub VALUES(652,'IT Road','Banjara Hills',78);
INSERT INTO Hub VALUES(653,'Hyder Nagar','Kukatpally',78);
INSERT INTO Hub VALUES(654,'Shanthi Nagar','Uppal',78);
INSERT INTO Hub VALUES(655,'IDA Nacharam','Nacharam',78);
INSERT INTO Hub VALUES(656,'Saraswathi Nagar','Saidabad',78);
INSERT INTO Hub VALUES(657,'Mlb School','Napier Town Jabalpur',79);
INSERT INTO Hub VALUES(658,'Keshrwani College','Jabalpur City',79);
INSERT INTO Hub VALUES(659,'Prem Mandir','Wright Town',79);
INSERT INTO Hub VALUES(660,'Station Road','Wright Town',79);
INSERT INTO Hub VALUES(661,'Hospital','Napier Town Jabalpur',79);
INSERT INTO Hub VALUES(662,'Crossing','Napier Town Jabalpur',79);
INSERT INTO Hub VALUES(663,'Garden','Napier Town Jabalpur',79);
INSERT INTO Hub VALUES(664,'Chandni Chowk','Jagdalpur',80);
INSERT INTO Hub VALUES(665,'Gandhi Stadium','Jagdalpur',80);
INSERT INTO Hub VALUES(666,'Dharampura','Jagdalpur',80);
INSERT INTO Hub VALUES(667,'Main Road','Jagdalpur',80);
INSERT INTO Hub VALUES(668,'Sanganer','Pratap Nagar',81);
INSERT INTO Hub VALUES(669,'Bihari Marg','Bani Park',81);
INSERT INTO Hub VALUES(670,'Cross Road Mall','Vidhyadhar Nagar',81);
INSERT INTO Hub VALUES(671,'Sindhi colony','Bani Park',81);
INSERT INTO Hub VALUES(672,'Chouradiya Petrol Pump','Sanganer',81);
INSERT INTO Hub VALUES(673,'Mansarovar Road','Gopalpura Bypass',81);
INSERT INTO Hub VALUES(674,'Calgary Road','Malviya Nagar',81);
INSERT INTO Hub VALUES(675,'Jaisalmer','Jaisalmer',82);
INSERT INTO Hub VALUES(676,'Gandhi Colony','Jaisalmer',82);
INSERT INTO Hub VALUES(677,'District Police H.Q.','Jaisalmer, Pokaran',82);
INSERT INTO Hub VALUES(678,'Hanuman Chauraha','Jaisalmer',82);
INSERT INTO Hub VALUES(679,'Barmer Rd','Jaisalmer',82);
INSERT INTO Hub VALUES(680,'Bahta Road','Nachana',82);
INSERT INTO Hub VALUES(681,'NHDA H.Q.','By Pass Sidhra, Jammu',83);
INSERT INTO Hub VALUES(682,'Bakshi Nagar','Jammu',83);
INSERT INTO Hub VALUES(683,'Talab Jung Road','Jammu',83);
INSERT INTO Hub VALUES(684,'Jammu Railway Station','Jammu',83);
INSERT INTO Hub VALUES(685,'Gandhi Nagar','Jammu',83);
INSERT INTO Hub VALUES(686,'Bank Of India','Jammu Tawi',83);
INSERT INTO Hub VALUES(687,'Amphalla','Jammu Tawi',83);
INSERT INTO Hub VALUES(688,'T Bus Stop','Summair Club Road',84);
INSERT INTO Hub VALUES(689,'Dwarka Highway','Airport Road',84);
INSERT INTO Hub VALUES(690,'Indira Marg','Indira Marg',84);
INSERT INTO Hub VALUES(691,'Opp Police Chowki','Digvijay Plot',84);
INSERT INTO Hub VALUES(692,'Town Hall Road','Jamnagar',84);
INSERT INTO Hub VALUES(693,'Virani Medical','Summair Club Road',84);
INSERT INTO Hub VALUES(694,'NH 33 Police','Mango',85);
INSERT INTO Hub VALUES(695,'Ramni Nagar Road','New Baridih',85);
INSERT INTO Hub VALUES(696,'Central Public School','Adityapur',85);
INSERT INTO Hub VALUES(697,'United Club','Bistupur',85);
INSERT INTO Hub VALUES(698,'Outer Circle Road','Bistupur',85);
INSERT INTO Hub VALUES(699,'Ram Mandir Area','Bistupur',85);
INSERT INTO Hub VALUES(700,'New Baradwari','Sakchi',85);
INSERT INTO Hub VALUES(701,'Road','Bundelkhand University',86);
INSERT INTO Hub VALUES(702,'Allahabad Bank Road','Civil Lines',86);
INSERT INTO Hub VALUES(703,'Gate No.1 Medical College Road','Near Police Chowki',86);
INSERT INTO Hub VALUES(704,'Alahbad Bank Rd','Jhansi',86);
INSERT INTO Hub VALUES(705,'Sipri Bzr','Sipri Bazar',86);
INSERT INTO Hub VALUES(706,'Gate No 2','Kanpur Road',86);
INSERT INTO Hub VALUES(707,'Medical College Road','Near Police Grounds',86);
INSERT INTO Hub VALUES(708,'Ummaid Hospital Road','Sardarpura',87);
INSERT INTO Hub VALUES(709,'Nandanwan','Chopasni Road',87);
INSERT INTO Hub VALUES(710,'Ravan Ka Chabutra','Residency Road',87);
INSERT INTO Hub VALUES(711,'A-322 Chowk','Shastri Nagar',87);
INSERT INTO Hub VALUES(712,'D Road','Sardarpura',87);
INSERT INTO Hub VALUES(713,'Nehar Road','Pal Road',87);
INSERT INTO Hub VALUES(714,'Lab Road','Ratanada Jodhpur',87);
INSERT INTO Hub VALUES(721,'Chitakhana Chowk','Junagadh',89);
INSERT INTO Hub VALUES(722,'Sardarbag Road','Junagadh',89);
INSERT INTO Hub VALUES(723,'College Road','Junagadh',89);
INSERT INTO Hub VALUES(724,'St Road','Junagadh',89);
INSERT INTO Hub VALUES(725,'Sardar Baug','Junagadh',89);
INSERT INTO Hub VALUES(726,'Bus Station Road','Junagadh',89);
INSERT INTO Hub VALUES(727,'Jundagadh Bus Stand','Junagadh',89);
INSERT INTO Hub VALUES(728,'Tripaai Road','Kalimpong',90);
INSERT INTO Hub VALUES(729,'Lower Bridle Road','Kalimpong',90);
INSERT INTO Hub VALUES(730,'10th Mile Road','Kalimpong',90);
INSERT INTO Hub VALUES(731,'Railway Road','Kanchipuram',91);
INSERT INTO Hub VALUES(732,'Highway Dev. Authority H.Q.','Kanchipuram',91);
INSERT INTO Hub VALUES(733,'Kamarajar Street','Kanchipuram',91);
INSERT INTO Hub VALUES(734,'Gst Road','Kattankolathur',91);
INSERT INTO Hub VALUES(735,'Market Street','Kanchipuram',91);
INSERT INTO Hub VALUES(736,'Railway Road','Kanchipuram',91);
INSERT INTO Hub VALUES(737,'Car Street','Sriperumbudur',91);
INSERT INTO Hub VALUES(738,'Panch Pakhadi','Thane West',92);
INSERT INTO Hub VALUES(739,'Goregaon Link Road','Mulund West',92);
INSERT INTO Hub VALUES(740,'L Mehta Rd','Vile Parle West',92);
INSERT INTO Hub VALUES(741,'Sheetal Nagar','Mira Road',92);
INSERT INTO Hub VALUES(742,'Naupada','Thane West',92);
INSERT INTO Hub VALUES(743,'Queen Chowk','Chembur West',92);
INSERT INTO Hub VALUES(744,'Sector No 01','New Panvel',92);
INSERT INTO Hub VALUES(745,'Lakhanpur','Lakhanpur',93);
INSERT INTO Hub VALUES(746,'Arya Nagar Dhramshala','Arya Nagar',93);
INSERT INTO Hub VALUES(747,'Rawatpur','Gutaiya Swaroop Nagar',93);
INSERT INTO Hub VALUES(748,'Canal Express Road','Canal Road',93);
INSERT INTO Hub VALUES(749,'Swaroop Nagar','Near IIT Campus, Kanpur',93);
INSERT INTO Hub VALUES(750,'Lajpat Nagar Market','Near HBTI, Kanpur',93);
INSERT INTO Hub VALUES(751,'Chunni Ganj','Kanpur Cantt. Area',93);
INSERT INTO Hub VALUES(752,'Kottaram','Kanyakumari',94);
INSERT INTO Hub VALUES(753,'Ramavarmapuram','Kanyakumari',94);
INSERT INTO Hub VALUES(754,'Udayar Villai','Colachal Port',94);
INSERT INTO Hub VALUES(755,'West Coast Road','Eathamozhi',94);
INSERT INTO Hub VALUES(756,'Asaripallam','Asaripallam',94);
INSERT INTO Hub VALUES(757,'Marthandam Road','Kuzhithura',94);
INSERT INTO Hub VALUES(758,'T V M Road','Kuzhithura',94);
INSERT INTO Hub VALUES(759,'District Tb Centre','Kargil',95);
INSERT INTO Hub VALUES(760,'Nr Unichem Lab','Solan',96);
INSERT INTO Hub VALUES(761,'ITI Gate','Solan',96);
INSERT INTO Hub VALUES(762,'Solan','Solan',96);
INSERT INTO Hub VALUES(763,'Manufacturing Workers Rd','Baddi',96);
INSERT INTO Hub VALUES(764,'Mahabir Spinning Mill','Baddi',96);
INSERT INTO Hub VALUES(765,'SAI Rd','Baddi',96);
INSERT INTO Hub VALUES(766,'Solan','Solan HP',96);
INSERT INTO Hub VALUES(767,'Almora Police H.Q.','Almora Uttranchal',97);
INSERT INTO Hub VALUES(768,'Almora Mall','Almora,Uttranchal',97);
INSERT INTO Hub VALUES(769,'Almora Market','Almora',97);
INSERT INTO Hub VALUES(770,'Ranikhet Hotel','Almora',97);
INSERT INTO Hub VALUES(771,'Almora Medicines','Almora',97);
INSERT INTO Hub VALUES(772,'Raniketh Tourism H.O','Almora',97);
INSERT INTO Hub VALUES(773,'Baneikala','Joda',98);
INSERT INTO Hub VALUES(774,'Joda Tourism Office','Joda',98);
INSERT INTO Hub VALUES(775,'Joda Police H.Q.','Joda',98);
INSERT INTO Hub VALUES(776,'Puri Extension','Durgakund',99);
INSERT INTO Hub VALUES(777,'dafi by pass','Varanasi Cantt. Area',99);
INSERT INTO Hub VALUES(778,'Ramakant Nagar','Maldahiya',99);
INSERT INTO Hub VALUES(779,'Smith Memorial School','Sigra Area',99);
INSERT INTO Hub VALUES(780,'Hydil Road','Dlw',99);
INSERT INTO Hub VALUES(781,'Univ. Main Gate','Varanasi Cantt. Area',99);
INSERT INTO Hub VALUES(782,'Udyan Tahsil','Varanasi Cantt',99);
INSERT INTO Hub VALUES(783,'Raj Nagar','Khajuraho',100);
INSERT INTO Hub VALUES(784,'Dulha Temple Road','Khajuraho',100);
INSERT INTO Hub VALUES(785,'Collectorate Road','Dharmapuri',60);
INSERT INTO Hub VALUES(786,'Main Road','Dharmapuri',60);
