INSERT INTO Restaurant VALUES(1,'Pankhuri Restaurant','Dhakran Crossing, M G Road',1,0);
INSERT INTO Restaurant VALUES(2,'Vedic Fine Dinning Veg Rest...','Yamuna View Hotel, Balu Ganj',1,0);
INSERT INTO Restaurant VALUES(3,'Rush Restaurant Pub & Disco','Level -3, Fatehabad Road',1,0);
INSERT INTO Restaurant VALUES(4,'Sheroes Hangout','The Gateway Hotel, Fatehabad Road',1,0);
INSERT INTO Restaurant VALUES(5,'Time 2 Eat Mama Chicken Mam...','Main Market, Sadar Bazaar',1,0);
INSERT INTO Restaurant VALUES(6,'Qaisar Bagh Restaurant','Fatehabad Road, Fatehabad Road',1,0);
INSERT INTO Restaurant VALUES(7,'Indiana Restaurant','Hotel Ratan Deep, Fatehabad Road',1,0);
INSERT INTO Restaurant VALUES(8,'The Green Pearl Restaurant','Sardar Patel Ring Road, Bodakdev',2,0);
INSERT INTO Restaurant VALUES(9,'Barbeque Nation Restaurant','Mile Stone, Drive In Road',2,4);
INSERT INTO Restaurant VALUES(10,'Queens Restaurant','New C G Road-Chandkheda',2,0);
INSERT INTO Restaurant VALUES(11,'Jay Girnar Kathiyawadi Rest...','Vastral Circle, Vastral',2,0);
INSERT INTO Restaurant VALUES(12,'New Mehfil Restaurant','Shahibaug Road, Delhi Darwaja',2,0);
INSERT INTO Restaurant VALUES(13,'Mehmaan Gujarati Cuisine An...','132 Feet Ring Road, Naranpura',2,0);
INSERT INTO Restaurant VALUES(14,'Shakti The Sandwich Shop','Ashopalav Shop, Relief Road',2,0);
INSERT INTO Restaurant VALUES(15,'Rasoi Restaurant','Swami Complex, Ajmer Ho',3,0);
INSERT INTO Restaurant VALUES(16,'Tadka Restaurant','Nasirabad Road, Ajmer Ho',3,0);
INSERT INTO Restaurant VALUES(17,'Fragrance Of India','Pushkar Road, Ajmer Ho',3,0);
INSERT INTO Restaurant VALUES(18,'Lve Kush Garden Restaurant','R K Link Road, Kishangarh',3,0);
INSERT INTO Restaurant VALUES(19,'Suhana Garden Restaurant','Jaipur Road, Ajmer Ho',3,0);
INSERT INTO Restaurant VALUES(20,'Olive Kitchen The Restra','Vaishali Nagar, Ajmer Ho',3,0);
INSERT INTO Restaurant VALUES(21,'Simran Food Corner','Sarswati Nagar, Dhola Bhata',3,0);
INSERT INTO Restaurant VALUES(22,'Avees Puttu House','A C Road, Pulinkunnu',4,0);
INSERT INTO Restaurant VALUES(23,'Thaff Family Restaurant','Court Bridge, Alappuzha Ho',4,0);
INSERT INTO Restaurant VALUES(24,'Kalpakavadi Highway Motels','Thottappally',4,0);
INSERT INTO Restaurant VALUES(25,'Mushroom Restaurant','Junction, Alappuzha Iron Bridge',4,0);
INSERT INTO Restaurant VALUES(26,'Hotel Brothers','Vellakinar Jn, Alapuzha',4,0);
INSERT INTO Restaurant VALUES(27,'Indian Coffee House','Beach Road, Alappuzha Ho',4,27);
INSERT INTO Restaurant VALUES(28,'Thaff Family Restaurant','Hospital Junction, Alappuzha Ho',4,0);
INSERT INTO Restaurant VALUES(29,'Royal Garden','Kalyan Murbad Road, Kalyan',5,0);
INSERT INTO Restaurant VALUES(30,'Matoshree Resort And River ...','Badlapur Gaon Road, Badlapur',5,0);
INSERT INTO Restaurant VALUES(31,'Mainland China Restaurant','New Link Road, Andheri West',5,26);
INSERT INTO Restaurant VALUES(32,'Hotel Capitol','Ghodbunder Road, Thane West',5,0);
INSERT INTO Restaurant VALUES(33,'Svenska Design Hotels Resta...','SAB TV Road, Andheri West',5,0);
INSERT INTO Restaurant VALUES(34,'UFO Revolving Restaurant','Asha Nagar-Kandivali East',5,0);
INSERT INTO Restaurant VALUES(35,'Baraesti Grill Bar & Beyond','Tagore Road, Tardeo',5,0);
INSERT INTO Restaurant VALUES(36,'Kamdhenu Sweets Confectiona...','Elgin Road, Civil Lines',6,0);
INSERT INTO Restaurant VALUES(37,'Dewsis Restaurant','M G Marg, Civil Lines',6,0);
INSERT INTO Restaurant VALUES(38,'Sapphire Blue Restaurant','Sardar Patel Marg, Civil Lines',6,0);
INSERT INTO Restaurant VALUES(39,'Kwality Restaurant','Near Palace Cinema, Allahabad Ho',6,0);
INSERT INTO Restaurant VALUES(40,'Reservseats','Mufordganj, Katra',6,0);
INSERT INTO Restaurant VALUES(41,'Sagar Ratna Restaurant','Hashimpur Road, Balson',6,0);
INSERT INTO Restaurant VALUES(42,'GayTime Family Restauran','Elgin Road, Civil Lines',6,0);
INSERT INTO Restaurant VALUES(43,'Glory Restaurant','R Shah Rd, Almora Ho',7,0);
INSERT INTO Restaurant VALUES(44,'Silver Oak Restaurant','Almora Bageshwar Road, Almora Ho',7,0);
INSERT INTO Restaurant VALUES(45,'New Tourist Restaurant','Shah Road, Almora Ho',7,0);
INSERT INTO Restaurant VALUES(46,'Bhumika Restaurant','Almora, Almora Ho',7,0);
INSERT INTO Restaurant VALUES(47,'Joshjus Restaurant','Mall Road, Almora Ho',7,0);
INSERT INTO Restaurant VALUES(48,'Pine Spring Restaurant','C/O Hotel Pine Spring, Pahalgam',8,0);
INSERT INTO Restaurant VALUES(49,'Abshaar','Near Amusement Park, Pahalgam',8,0);
INSERT INTO Restaurant VALUES(50,'Paradise Restaurant','Main Market, Pahalgam',8,0);
INSERT INTO Restaurant VALUES(51,'Summer Kand Resturant','Amuzement Park Pahalgam, Pahalgam',8,0);
INSERT INTO Restaurant VALUES(52,'Himalaya House Restaurant','Laripora, Pahalgam',8,0);
INSERT INTO Restaurant VALUES(53,'Kesar Da Dhaba','Chowk Passian, Amritsar Gpo',9,0);
INSERT INTO Restaurant VALUES(54,'The Yellow Chilli','B-Block, Amritsar Gpo',9,0);
INSERT INTO Restaurant VALUES(55,'Temptation Restaurant','Circular Road, Amritsar Gpo',9,0);
INSERT INTO Restaurant VALUES(56,'Cafe Oz','B-Block, Amritsar',9,0);
INSERT INTO Restaurant VALUES(57,'Radhe Radhe Traditional Ras...','Hall Bazaar, Amritsar',9,0);
INSERT INTO Restaurant VALUES(58,'Zyka Multicuisine Restaurant','Above Subway, Golden Temple',9,0);
INSERT INTO Restaurant VALUES(59,'Moti Mahal Delux','Ranjit Avenue, Amritsar Gpo',9,0);
INSERT INTO Restaurant VALUES(60,'Vishnuji Ki Rasoi','G B Road, Thane West',10,0);
INSERT INTO Restaurant VALUES(61,'Mainland China Restaurant','New Link Road, Andheri West',10,26);
INSERT INTO Restaurant VALUES(62,'Hotel Capitol','Ghodbunder Road, Thane West',10,0);
INSERT INTO Restaurant VALUES(63,'Svenska Design Hotels Resta...','SAB TV Road, Andheri West',10,0);
INSERT INTO Restaurant VALUES(64,'UFO Revolving Restaurant','Asha Nagar-Kandivali East',10,0);
INSERT INTO Restaurant VALUES(65,'Baraesti Grill Bar & Beyond','Tagore Road, Tardeo',10,0);
INSERT INTO Restaurant VALUES(66,'Flamboyante Restaurant','Cuffe Parade-Colaba',10,0);
INSERT INTO Restaurant VALUES(67,'THE BIRYANI MALL','& Patna Central, Frazer Road',11,0);
INSERT INTO Restaurant VALUES(68,'Madhuri Restaurant And  Bar','Frazer Road, Frazer Road',11,0);
INSERT INTO Restaurant VALUES(69,'Curry Culture','Bata Showroom, Exhibition Road',11,0);
INSERT INTO Restaurant VALUES(70,'Roshis  Lunch Box','Nayatola Kadamkuan, Nayatola',11,0);
INSERT INTO Restaurant VALUES(71,'Biryani House','Exhibition Road, Exhibition Road',11,0);
INSERT INTO Restaurant VALUES(72,'Pal Hotel','Station Road, Patna Gpo',11,0);
INSERT INTO Restaurant VALUES(73,'Raj Darbar Family Restaurant','Exhibition Road, Exhibition Road',11,0);
INSERT INTO Restaurant VALUES(74,'Hotel Capitol','Ghodbunder Road, Thane West',12,0);
INSERT INTO Restaurant VALUES(75,'Mainland China Restaurant','New Link Road, Andheri West',12,26);
INSERT INTO Restaurant VALUES(76,'UFO Revolving Restaurant','Asha Nagar-Kandivali East',12,0);
INSERT INTO Restaurant VALUES(77,'Svenska Design Hotels Resta...','SAB TV Road, Andheri West',12,0);
INSERT INTO Restaurant VALUES(78,'Flamboyante Restaurant','Cuffe Parade-Colaba',12,0);
INSERT INTO Restaurant VALUES(79,'Baraesti Grill Bar & Beyond','Tagore Road, Tardeo',12,0);
INSERT INTO Restaurant VALUES(80,'Shiv Sagar Restaurant','Juju Tara Road, Juhu',12,0);
INSERT INTO Restaurant VALUES(81,'Hotel Capitol','Ghodbunder Road, Thane West',13,0);
INSERT INTO Restaurant VALUES(82,'Mainland China Restaurant','New Link Road, Andheri West',13,26);
INSERT INTO Restaurant VALUES(83,'UFO Revolving Restaurant','Asha Nagar-Kandivali East',13,0);
INSERT INTO Restaurant VALUES(84,'Svenska Design Hotels Resta...','SAB TV Road, Andheri West',13,0);
INSERT INTO Restaurant VALUES(85,'Flamboyante Restaurant','Cuffe Parade-Colaba',13,0);
INSERT INTO Restaurant VALUES(86,'Baraesti Grill Bar & Beyond','Tagore Road, Tardeo',13,0);
INSERT INTO Restaurant VALUES(87,'Shiv Sagar Restaurant','Juju Tara Road, Juhu',13,0);
INSERT INTO Restaurant VALUES(88,'Apple Lounge','star plaza, KT Road',14,0);
INSERT INTO Restaurant VALUES(89,'Chillies Food Paradise','Air Bypass Road, Tirupati Ho',14,0);
INSERT INTO Restaurant VALUES(90,'The Hangout Restaurant','New Balaji, Air Bypass Road',14,0);
INSERT INTO Restaurant VALUES(91,'Deforest Theme Restaurant','Talent School, Tirupati Ho',14,0);
INSERT INTO Restaurant VALUES(92,'Saarangi Fine Dine Restaurant','Narayamgiri Area, Tirumala',14,0);
INSERT INTO Restaurant VALUES(93,'Hotel Grand Gayathri','Station Road, Station Road',15,0);
INSERT INTO Restaurant VALUES(94,'Kohinoor Family Restaurant','Hanmakonda, Hanamkonda',15,0);
INSERT INTO Restaurant VALUES(95,'Silver Leaf Hotel','Gutta Knmr Road, Hanamkonda',15,0);
INSERT INTO Restaurant VALUES(96,'Surabhi s Food Court','Nakkalagutta, Hanamkonda',15,0);
INSERT INTO Restaurant VALUES(97,'Manu Family Restaurant','Jpn Road, JPN Road',15,0);
INSERT INTO Restaurant VALUES(98,'Rang Restaurant & Bar','Naim Nagar, Hanamkonda',15,0);
INSERT INTO Restaurant VALUES(99,'Kalinga Dhaba','Darga 100 Feet Road, Kazipet',15,0);
INSERT INTO Restaurant VALUES(100,'Shri Kanak Sarkar Rasoyi','Kanak Bhavan, Ayodhya Ho',16,0);
INSERT INTO Restaurant VALUES(101,'Shri Ram Rasoyi','Purana Bus Stand, Ayodhya Ho',16,0);
INSERT INTO Restaurant VALUES(102,'Makan Malai Restaurant','Nh-27, Ayodhya Ho',16,0);
INSERT INTO Restaurant VALUES(103,'Shyam Restaurant','Near Hanuman Garhi, Ayodhya Ho',16,0);
INSERT INTO Restaurant VALUES(104,'Aayush Chandra Bhojnalay','Shringarhat, Ayodhya Ho',16,0);
INSERT INTO Restaurant VALUES(105,'Ram Chandra Bhojnalay','Shringarhat, Ayodhya Ho',16,0);
INSERT INTO Restaurant VALUES(106,'Shri Narayan Bhojnalay','Shringarhat, Ayodhya Ho',16,0);
INSERT INTO Restaurant VALUES(107,'Star Biryani Hotel','Kabbalgeri Cross, Badami',17,0);
INSERT INTO Restaurant VALUES(108,'Shubhashri Bar & Restaurant','Station Road, Badami',17,0);
INSERT INTO Restaurant VALUES(109,'Sanman Restaurant','Station Road, Badami',17,0);
INSERT INTO Restaurant VALUES(110,'Lemon Tree Restaurant','Station Road, Badami',17,0);
INSERT INTO Restaurant VALUES(111,'Pulikeshi Dining Room','Station Road, Badami',17,0);
INSERT INTO Restaurant VALUES(112,'Shri Ragavendra Milk And ICE C...','Badami, Badami',17,0);
INSERT INTO Restaurant VALUES(113,'Banashree Hotel','Badami, Badami',17,0);
INSERT INTO Restaurant VALUES(114,'Bhojan Restaurant','O T Road, Balasore HO',18,0);
INSERT INTO Restaurant VALUES(115,'Pizza Shop','Vivekananda Road, Balasore Ho',18,0);
INSERT INTO Restaurant VALUES(116,'Lucky Restaurant','Jaleswar Road, Jaleswar',18,0);
INSERT INTO Restaurant VALUES(117,'MAA Hotel','Balasore Road, Jaleswar',18,0);
INSERT INTO Restaurant VALUES(118,'MAA Kalika Hotel','Station Road, Nayabazar Balasore',18,0);
INSERT INTO Restaurant VALUES(119,'Hotel Omm SAI','Station Road, Nayabazar Balasore',18,0);
INSERT INTO Restaurant VALUES(120,'Keshav Restaurant','Ot Road, Balasore Ho',18,0);
INSERT INTO Restaurant VALUES(121,'Jungle Restaurant (Syna Tiger ...','Tala, Bandhavgarh National Park',19,0);
INSERT INTO Restaurant VALUES(122,'Sheroo Restaurant','Road, Bandhavgarh National Park',19,0);
INSERT INTO Restaurant VALUES(123,'Tigers Pride Restaurant','P O, Bandhavgarh National Park',19,0);
INSERT INTO Restaurant VALUES(124,'Tiger Heaven Restaurant','P O, Bandhavgarh National Park',19,0);
INSERT INTO Restaurant VALUES(125,'The Baithak Restaurant','Tiger, Bandhavgarh National Park',19,0);
INSERT INTO Restaurant VALUES(126,'Orchid Restaurant','Road, Bandhavgarh National Park',19,0);
INSERT INTO Restaurant VALUES(127,'Cats Restaurant','Umaria, Bandhavgarh National Park',19,0);
INSERT INTO Restaurant VALUES(128,'Hotel Crystal Paark Inn','Nazarabad Main Road, Nazarbad',20,0);
INSERT INTO Restaurant VALUES(129,'Mahendra Hotels','B N, B N Road',20,0);
INSERT INTO Restaurant VALUES(130,'Pakva International Veg Lounge','Temple Road, V V Mohalla',20,0);
INSERT INTO Restaurant VALUES(131,'Mysore Nandhini Andhra Styl...','Irwin Road, Irwin Road',20,0);
INSERT INTO Restaurant VALUES(132,'Pelican Pub And Grub House ...','Hunsur Road, Jayalakshmipuram',20,0);
INSERT INTO Restaurant VALUES(133,'Us Pizza','Rama Vilas, K R Mohalla',20,0);
INSERT INTO Restaurant VALUES(134,'By The Way','Ring Road, Hebbal',20,0);
INSERT INTO Restaurant VALUES(135,'Shinkows Restaurant','Commissioners Road, Ooty Ho',21,0);
INSERT INTO Restaurant VALUES(136,'Quality Restaurants','Church Hill, Church Hill Road',21,0);
INSERT INTO Restaurant VALUES(137,'Ammas Kitchen','Mysore Road, Ooty',21,0);
INSERT INTO Restaurant VALUES(138,'Malabar Hotel','Bus Stand, Ooty Ho',21,0);
INSERT INTO Restaurant VALUES(139,'Dominos Pizza','Commercial Road, Ooty',21,22);
INSERT INTO Restaurant VALUES(140,'Lakeview Multicuisine Restaurant','West Lake Road, Ooty HO',21,0);
INSERT INTO Restaurant VALUES(141,'Chicking Fried Chicken','Coonoor Road, Nilgiri',21,0);
INSERT INTO Restaurant VALUES(142,'Zaika The Finest Multicuisi...','Church Street Camp, Belgaum Camp',22,0);
INSERT INTO Restaurant VALUES(143,'Cibo Kitchen And Lounge Bar','Ramling Khind Galli Belgaum',22,0);
INSERT INTO Restaurant VALUES(144,'Gacchi Family Restaurant An...','Khanapur Road, Udyambag Belgaum',22,0);
INSERT INTO Restaurant VALUES(145,'S Boss Family Restaurant','Khade Bazar, Shahapur Belgaum',22,0);
INSERT INTO Restaurant VALUES(146,'Hotel Pride','Congress Road, Tilakwadi Belgaum',22,0);
INSERT INTO Restaurant VALUES(147,'Charminar Family Restaurant','Shivanand Lodge, Khade Bazaar',22,0);
INSERT INTO Restaurant VALUES(148,'Priya Bar And Restaurant','Hutatma, Kirloskar Road Belgaum',22,0);
INSERT INTO Restaurant VALUES(149,'Anandaritz Restaurant','Police Station, Matheran Ho',23,0);
INSERT INTO Restaurant VALUES(150,'The Byke Restaurants','M G Road, Matheran Ho',23,0);
INSERT INTO Restaurant VALUES(151,'Divadkar Restaurant & Bar','M G Road, Matheran Ho',23,0);
INSERT INTO Restaurant VALUES(152,'Alexander Pure Veg Restaurant','To Forest Office, Matheran Ho',23,0);
INSERT INTO Restaurant VALUES(153,'Greenhill Restaurant','District Raigad, Matheran Ho',23,0);
INSERT INTO Restaurant VALUES(154,'Spice Garden','Opposite Lord Nawroji Garden',23,0);
INSERT INTO Restaurant VALUES(155,'The Nawab Speciality Restau...','Madhavnagar, Kumara Krupa Road',24,0);
INSERT INTO Restaurant VALUES(156,'Dum Pukht Jolly Nabobs (ITC...','Golf Course Road, Sankey Road',24,0);
INSERT INTO Restaurant VALUES(157,'Anjappar Chettinad Restaurant','4th B Block, Koramangala',24,0);
INSERT INTO Restaurant VALUES(158,'Pai Viceroy Hotel','9th, Jayanagar 3rd Block',24,0);
INSERT INTO Restaurant VALUES(159,'Retro The Lounge Bar','Cambridge Road, Ulsoor',24,0);
INSERT INTO Restaurant VALUES(160,'Sampoorna The Multicuisine ...','24th, Jp Nagar 5th Phase',24,0);
INSERT INTO Restaurant VALUES(161,'Kuttanadu Restaurant','14th Main, Hsr Layout',24,0);
INSERT INTO Restaurant VALUES(162,'Aryan Restaurant A Unit of ...','Mg Marg, Hazratganj',25,0);
INSERT INTO Restaurant VALUES(163,'Royal Sky A Unit Of Jagtiya...','Mg Marg, Hazratganj',25,0);
INSERT INTO Restaurant VALUES(164,'Saffron Kitchen','Gomti Nagar Thana, Gomti Nagar',25,0);
INSERT INTO Restaurant VALUES(165,'Aadab','Srs City Mall, Gomti Nagar',25,0);
INSERT INTO Restaurant VALUES(166,'Babian Inn & Babian Restaur...','Road, Indira Nagar Lucknow',25,0);
INSERT INTO Restaurant VALUES(167,'New Chik Chik Chicken Corner','Alambagh, Alambagh',25,0);
INSERT INTO Restaurant VALUES(168,'Wah Ji Wah','Chauraha, Gomti Nagar',25,0);
INSERT INTO Restaurant VALUES(169,'Hotel Atithi','Ashtan Mandir, Muzaffarpur Ho',26,0);
INSERT INTO Restaurant VALUES(170,'Bharat Biryani','Motijheel Main Road, Motijheel',26,0);
INSERT INTO Restaurant VALUES(171,'Milan Restaurant &Conference Hall','Kalambagh Chowk, Muzaffarpur HO',26,0);
INSERT INTO Restaurant VALUES(172,'Chandra Palace Restaurant','Main Road Maripur, Muzaffarpur HO',26,0);
INSERT INTO Restaurant VALUES(173,'Kaveri Restaurant','Tilak Maidan Road, Muzaffarpur Ho',26,0);
INSERT INTO Restaurant VALUES(174,'Swarg Family Restaurant','Muzaffapur, Muzaffarpur Ho',26,0);
INSERT INTO Restaurant VALUES(175,'Grand Ayyanar','Surveyor Colony Road, Madurai Ho',27,0);
INSERT INTO Restaurant VALUES(176,'Heavens Park','120 Feet Road, Madurai Ho',27,0);
INSERT INTO Restaurant VALUES(177,'Hotel Milagu','North Masi Street, Simmakkal',27,0);
INSERT INTO Restaurant VALUES(178,'Sarathy Fried Chicken','Road Ellis Nagar, Madurai Ho',27,0);
INSERT INTO Restaurant VALUES(179,'US Pizza','Next To Arch, Pasumalai Madurai',27,0);
INSERT INTO Restaurant VALUES(180,'Hotel Impala','Gst Road, Thirunagar',27,0);
INSERT INTO Restaurant VALUES(181,'Big Chick Foods','Nadar Road, Madurai Bibikulam',27,0);
INSERT INTO Restaurant VALUES(182,'Vishnuji Ki Rasoi','G B Road, Thane West',28,0);
INSERT INTO Restaurant VALUES(183,'Daras Dhaba/ Zest','Mumbai Nasik Highway, Bhiwandi',28,0);
INSERT INTO Restaurant VALUES(184,'Rude Lounge','Hill Road, Bandra West',28,0);
INSERT INTO Restaurant VALUES(185,'Rude Lounge','Lbs Marg, Mulund West',28,0);
INSERT INTO Restaurant VALUES(186,'High Point Veg Restaurant','Lokhandwala Complex-Andheri West',28,0);
INSERT INTO Restaurant VALUES(187,'Rude Lounge','Hanuman Mandir, Malad West',28,0);
INSERT INTO Restaurant VALUES(188,'Spices And Flavours','Hamam Street, Fort',28,0);
INSERT INTO Restaurant VALUES(189,'Rohit  Resturant','Guru Nagar, Bidar Ho',29,0);
INSERT INTO Restaurant VALUES(190,'Mahek Multi Cuisine Family Res...','Beside Gujrati Timber, Janwada',29,0);
INSERT INTO Restaurant VALUES(191,'Hotel Royal Heritage Bar & Res...','Bustand Road, Naubad',29,0);
INSERT INTO Restaurant VALUES(192,'ABC Restaurant','Faeddin, Udgir Road Bidar',29,0);
INSERT INTO Restaurant VALUES(193,'Dhami Punjabi Family Dhaba','Mumbai Road, Basavakalyan',29,0);
INSERT INTO Restaurant VALUES(194,'New Almas Bawarchi','Maion Road, Bidar Ho',29,0);
INSERT INTO Restaurant VALUES(195,'Green Land','Bhalki Road, Naubad',29,0);
INSERT INTO Restaurant VALUES(196,'Royale Master Chef Fine Dine','Next To Mc Donalds, Dahisar',30,0);
INSERT INTO Restaurant VALUES(197,'ZENZIBU MULTICUISINE','Near Anik Depot, Wadala East',30,0);
INSERT INTO Restaurant VALUES(198,'Rude Lounge','Hill Road, Bandra West',30,0);
INSERT INTO Restaurant VALUES(199,'High Point Veg Restaurant','Lokhandwala Complex-Andheri West',30,0);
INSERT INTO Restaurant VALUES(200,'Rude Lounge','Hanuman Mandir, Malad West',30,0);
INSERT INTO Restaurant VALUES(201,'Rude Lounge','Lbs Marg, Mulund West',30,0);
INSERT INTO Restaurant VALUES(202,'Spices And Flavours','Hamam Street, Fort',30,0);
INSERT INTO Restaurant VALUES(203,'Hotel Capitol','Ghodbunder Road, Thane West',31,0);
INSERT INTO Restaurant VALUES(204,'Mainland China Restaurant','New Link Road, Andheri West',31,26);
INSERT INTO Restaurant VALUES(205,'Svenska Design Hotels Resta...','SAB TV Road, Andheri West',31,0);
INSERT INTO Restaurant VALUES(206,'UFO Revolving Restaurant','Asha Nagar-Kandivali East',31,0);
INSERT INTO Restaurant VALUES(207,'Baraesti Grill Bar & Beyond','Tagore Road, Tardeo',31,0);
INSERT INTO Restaurant VALUES(208,'Flamboyante Restaurant','Cuffe Parade-Colaba',31,0);
INSERT INTO Restaurant VALUES(209,'Food Inn','Lokhandwala Complex-Andheri West',31,0);
INSERT INTO Restaurant VALUES(210,'Taj Darbar Restaurants','Near Coria Temple, Bodhgaya HO',32,0);
INSERT INTO Restaurant VALUES(211,'Mahamaya Restaurant','Mahabodhi Temple, Bodhgaya Ho',32,0);
INSERT INTO Restaurant VALUES(212,'Pithasin Restaurants','Hathyar, Bodhgaya Ho',32,0);
INSERT INTO Restaurant VALUES(213,'Amrapali Restaurant','Dumuhan Road, Bodhgaya Ho',32,0);
INSERT INTO Restaurant VALUES(214,'Siddhartha Restaurants','Bank Of India, Bodhgaya Ho',32,0);
INSERT INTO Restaurant VALUES(215,'King Restaurants','C/O Prince Hotel, Bodhgaya HO',32,0);
INSERT INTO Restaurant VALUES(216,'Om Restaurant','Main Road, Bodhgaya Ho',32,0);
INSERT INTO Restaurant VALUES(217,'Janata Hotel','Ramai Talkies Road, Balangir Ho',33,0);
INSERT INTO Restaurant VALUES(218,'Hotel Rajmahal','Ramai Talkies Road, Balangir Ho',33,0);
INSERT INTO Restaurant VALUES(219,'Shree Ganesh Sweets Centre','Kalamandal Road, Balangir Ho',33,0);
INSERT INTO Restaurant VALUES(220,'Mainland China Restaurant','New Link Road, Andheri West',34,26);
INSERT INTO Restaurant VALUES(221,'Hotel Capitol','Ghodbunder Road, Thane West',34,0);
INSERT INTO Restaurant VALUES(222,'Svenska Design Hotels Resta...','SAB TV Road, Andheri West',34,0);
INSERT INTO Restaurant VALUES(223,'UFO Revolving Restaurant','Asha Nagar-Kandivali East',34,0);
INSERT INTO Restaurant VALUES(224,'Baraesti Grill Bar & Beyond','Tagore Road, Tardeo',34,0);
INSERT INTO Restaurant VALUES(225,'Flamboyante Restaurant','Cuffe Parade-Colaba',34,0);
INSERT INTO Restaurant VALUES(226,'Food Inn','Lokhandwala Complex-Andheri West',34,0);
INSERT INTO Restaurant VALUES(227,'Jagan Restaurant & Bar','Museum Road, Chamba Ho',35,0);
INSERT INTO Restaurant VALUES(228,'MANMAHESH RASOI','Panchpula Road, Chamba Ho',35,0);
INSERT INTO Restaurant VALUES(229,'Zaika','Upper Julahkari, Chamba Ho',35,0);
INSERT INTO Restaurant VALUES(230,'Bhumija Restaurant','Khajjiar',35,0);
INSERT INTO Restaurant VALUES(231,'Shelly Restaurant','Link Rd, Samote',35,0);
INSERT INTO Restaurant VALUES(232,'Fuel.Inn','Saltlake City,',36,0);
INSERT INTO Restaurant VALUES(233,'Lake Lite Fine Dine & Bar','Salt Lake City,',36,0);
INSERT INTO Restaurant VALUES(234,'Tinny Da Dhaba','Ballygunge Gardens,',36,0);
INSERT INTO Restaurant VALUES(235,'Asia In Box','Rajahat,',36,0);
INSERT INTO Restaurant VALUES(236,'Gammas Restaurants','Near Chinner Park,',36,0);
INSERT INTO Restaurant VALUES(237,'Ol Yourz','Near Baisakhi Island,',36,0);
INSERT INTO Restaurant VALUES(238,'Rang De Basanti Dhaba','Jessore Road,',36,0);
INSERT INTO Restaurant VALUES(239,'Swagath Restaurant','Madhya Marg, Chandigarh Sector 26',37,0);
INSERT INTO Restaurant VALUES(240,'Dil Desi','Subway, Chandigarh Sector 32d',37,0);
INSERT INTO Restaurant VALUES(241,'Food Flavour Restaurant','Phase 5, Mohali',37,0);
INSERT INTO Restaurant VALUES(242,'Chawlas 2','Local Bus, Chandigarh Sector 40c',37,0);
INSERT INTO Restaurant VALUES(243,'Karan Dhaba','Boot no, Chandigarh Sector 7c',37,0);
INSERT INTO Restaurant VALUES(244,'Garlic And Greens','Phase -1, Chandigarh Gpo',37,0);
INSERT INTO Restaurant VALUES(245,'Mahavir Sweets & Dhaba','area phase 1, Panchkula',37,0);
INSERT INTO Restaurant VALUES(246,'Moti Mahal Itihaas Restaurant','Opposite Railway Station, Vashi',38,0);
INSERT INTO Restaurant VALUES(247,'Hotel Capitol','Ghodbunder Road, Thane West',38,0);
INSERT INTO Restaurant VALUES(248,'Mainland China Restaurant','New Link Road, Andheri West',38,26);
INSERT INTO Restaurant VALUES(249,'Svenska Design Hotels Resta...','SAB TV Road, Andheri West',38,0);
INSERT INTO Restaurant VALUES(250,'UFO Revolving Restaurant','Asha Nagar-Kandivali East',38,0);
INSERT INTO Restaurant VALUES(251,'Baraesti Grill Bar & Beyond','Tagore Road, Tardeo',38,0);
INSERT INTO Restaurant VALUES(252,'Flamboyante Restaurant','Cuffe Parade-Colaba',38,0);
INSERT INTO Restaurant VALUES(253,'Hotel Saizad Bawarchi','Boisar Palghar Road, Boisar',39,0);
INSERT INTO Restaurant VALUES(254,'Koyla Ethnic Cuisine','Cake Factory Lane, Andheri West',39,0);
INSERT INTO Restaurant VALUES(255,'Rude Lounge','Lbs Marg, Mulund West',39,0);
INSERT INTO Restaurant VALUES(256,'Rude Lounge','Hill Road, Bandra West',39,0);
INSERT INTO Restaurant VALUES(257,'Hotel Capitol','Ghodbunder Road, Thane West',39,0);
INSERT INTO Restaurant VALUES(258,'Gold Coins Restaurant & Ban...','Tardeo Rd, Tardeo',39,0);
INSERT INTO Restaurant VALUES(259,'Rude Lounge','Hanuman Mandir, Malad West',39,0);
INSERT INTO Restaurant VALUES(260,'Al Barack Hotel','Gst Road, Tambaram',40,0);
INSERT INTO Restaurant VALUES(261,'Sigree Global Grill','Road, Okkiyam Thuraipakkam',40,23);
INSERT INTO Restaurant VALUES(262,'Aasife And Brothers Biryani...','L B Road, Thiruvanmiyur',40,0);
INSERT INTO Restaurant VALUES(263,'Aasife And Brothers Biryani...','Woods Road, Mount Road',40,0);
INSERT INTO Restaurant VALUES(264,'Kattumaram Multi Cuisine Re...','Arcot Road, Porur',40,0);
INSERT INTO Restaurant VALUES(265,'Glm Meridian','South Boag Road, T Nagar',40,0);
INSERT INTO Restaurant VALUES(266,'New Andhra Meals Hotel','Arcot Road, Valasaravakkam',40,0);
INSERT INTO Restaurant VALUES(267,'Hotel Grand Park','East car street, Chidambaram Ho',41,0);
INSERT INTO Restaurant VALUES(268,'Marrybrown Family Restaurant','P Koil Street, Chidambaram Ho',41,0);
INSERT INTO Restaurant VALUES(269,'Mangrove Restaurant','O P Main Road, Annamalainagar',41,0);
INSERT INTO Restaurant VALUES(270,'New Murthy Cafe','Street, Chidambaram Ho',41,0);
INSERT INTO Restaurant VALUES(271,'Anupallavi Restaurant','VGP Street, Chidambaram Ho',41,0);
INSERT INTO Restaurant VALUES(272,'Chick Punch','Pillai Street, Chidambaram Ho',41,0);
INSERT INTO Restaurant VALUES(273,'Jamal & Brothers Food Mall','P Koil Street, Chidambaram HO',41,0);
INSERT INTO Restaurant VALUES(274,'HOTEL AMR EVVERGREEN RESTAU...','Road Four Road, Leigh Bazaar',42,0);
INSERT INTO Restaurant VALUES(275,'Baar B Queen Halal Restaurants','Junction Main Road, Meyyanur',42,0);
INSERT INTO Restaurant VALUES(276,'Dindigul Ponram Biryani Hotel','Four Road, Salem Ho',42,0);
INSERT INTO Restaurant VALUES(277,'Selvi Mess','Arthanari Nagar, Swarnapuri',42,0);
INSERT INTO Restaurant VALUES(278,'Hotel Junior Kuppanna','Greenways Road, Fair Lands',42,0);
INSERT INTO Restaurant VALUES(279,'Magala Vilas Non Veg Hotel Ac','Arthanari Nagar, Fair Lands',42,0);
INSERT INTO Restaurant VALUES(280,'Kovai Biryani Hotel','Cross Brindhavan Road, Salem Ho',42,0);
INSERT INTO Restaurant VALUES(281,'The Cascade Restaurant','Avinashi Road, Peelamedu',43,0);
INSERT INTO Restaurant VALUES(282,'LFC Restaurant','College Road, Coimbatore Central',43,0);
INSERT INTO Restaurant VALUES(283,'Geethanjali','Samy Road, R S Puram',43,0);
INSERT INTO Restaurant VALUES(284,'The Cascade Restaurant','D B, R S Puram',43,0);
INSERT INTO Restaurant VALUES(285,'Mother Travels','Near Allahabad Bank, Kalapatti',43,0);
INSERT INTO Restaurant VALUES(286,'Five Star Chicken','D B, R S Puram',43,0);
INSERT INTO Restaurant VALUES(287,'Kurrinji Gaardenn Multicuis...','L&T Byepass Road, Ondipudur',43,0);
INSERT INTO Restaurant VALUES(288,'De Rock Restaurant','Lambs Rock Road, Coonoor Ho',44,0);
INSERT INTO Restaurant VALUES(289,'Dragon Chinese Restaurant','Opposite Indian Bank, Bed Ford',44,0);
INSERT INTO Restaurant VALUES(290,'Cafe Coffee Day','Simspark Road, Coonoor RS',44,0);
INSERT INTO Restaurant VALUES(291,'Mirchi Restaurant','Bedford Circle, Coonoor HO',44,0);
INSERT INTO Restaurant VALUES(292,'Madurai Appu Restaurant','Mount Road, Coonoor HO',44,0);
INSERT INTO Restaurant VALUES(293,'Quality Restaurant','Bedfore, Coonoor RS',44,0);
INSERT INTO Restaurant VALUES(294,'Sri Ramachandra Lunch Home','Coonoor RS',44,0);
INSERT INTO Restaurant VALUES(295,'Mainland China Restaurant','New Link Road, Andheri West',45,26);
INSERT INTO Restaurant VALUES(296,'Hotel Capitol','Ghodbunder Road, Thane West',45,0);
INSERT INTO Restaurant VALUES(297,'Svenska Design Hotels Resta...','SAB TV Road, Andheri West',45,0);
INSERT INTO Restaurant VALUES(298,'UFO Revolving Restaurant','Asha Nagar-Kandivali East',45,0);
INSERT INTO Restaurant VALUES(299,'Baraesti Grill Bar & Beyond','Tagore Road, Tardeo',45,0);
INSERT INTO Restaurant VALUES(300,'Flamboyante Restaurant','Cuffe Parade-Colaba',45,0);
INSERT INTO Restaurant VALUES(301,'Food Inn','Lokhandwala Complex-Andheri West',45,0);
INSERT INTO Restaurant VALUES(302,'WOW MOMO','N H 47, Edapally',46,0);
INSERT INTO Restaurant VALUES(303,'Fawaz Broasted Restaurant','Palativattom, Padivattom',46,0);
INSERT INTO Restaurant VALUES(304,'Abaam Hotel (Tangerine Rest...','Kaniampuzha Road, Vyttila',46,0);
INSERT INTO Restaurant VALUES(305,'The Senate Hotel','Providence Road, Ernakulam',46,0);
INSERT INTO Restaurant VALUES(306,'Dal Roti Restaurant','Lilly Street, Kochi Fort',46,0);
INSERT INTO Restaurant VALUES(307,'Taj Mahal Restaurant & Home Stay','K B Jacob Road, Kochi',46,0);
INSERT INTO Restaurant VALUES(308,'Pizza 10','Ernakulam, Kochi',46,0);
INSERT INTO Restaurant VALUES(309,'Dominos Pizza','Near Bombay Hotel, College Square',47,22);
INSERT INTO Restaurant VALUES(310,'Barabati Restaurant','Jail Road, Dargha Bazar',47,0);
INSERT INTO Restaurant VALUES(311,'Cafe Coffee Day','Chandra Road, Dargha Bazar',47,0);
INSERT INTO Restaurant VALUES(312,'Seasons','Ranihat, Medical College',47,0);
INSERT INTO Restaurant VALUES(313,'Manisha Fine Dining & Banqu...','Sector No 15, Cbd Belapur',48,0);
INSERT INTO Restaurant VALUES(314,'Vishnuji Ki Rasoi','G B Road, Thane West',48,0);
INSERT INTO Restaurant VALUES(315,'Rude Lounge','Hill Road, Bandra West',48,0);
INSERT INTO Restaurant VALUES(316,'Rude Lounge','Lbs Marg, Mulund West',48,0);
INSERT INTO Restaurant VALUES(317,'Rude Lounge','Hanuman Mandir, Malad West',48,0);
INSERT INTO Restaurant VALUES(318,'High Point Veg Restaurant','Lokhandwala Complex-Andheri West',48,0);
INSERT INTO Restaurant VALUES(319,'Gold Coins Restaurant & Ban...','Tardeo Rd, Tardeo',48,0);
INSERT INTO Restaurant VALUES(320,'Lovely Restaurant','Satdhara Road, Dalhousie Ho',49,0);
INSERT INTO Restaurant VALUES(321,'Kwality Restaurants','Gandhi Chowk, Dalhousie Cantt',49,0);
INSERT INTO Restaurant VALUES(322,'Old Sher E Punjab Dhaba','Subhash Chowk, Dalhousie Cantt',49,0);
INSERT INTO Restaurant VALUES(323,'Original Sher e Punjab','Subhash Chowk, Dalhousie Ho',49,0);
INSERT INTO Restaurant VALUES(324,'Manmahesh Rasoi','Punchpulla Road, Dalhousie HO',49,0);
INSERT INTO Restaurant VALUES(325,'MONGAS COFFEE SHOP','Gpo Lane, Dalhousie Ho',49,0);
INSERT INTO Restaurant VALUES(326,'Yatrinivas Restaurants','Yatrinivas Hotel, Konark HO',50,0);
INSERT INTO Restaurant VALUES(327,'Meridien Guzzlers & Sizzlers','Jampor Beach, Moti Daman',51,0);
INSERT INTO Restaurant VALUES(328,'Pind Punjab Da','Daman Main Road, Daman Ho',51,0);
INSERT INTO Restaurant VALUES(329,'Veera Da Dhaba','Daman Vapi Main Road, Varkund',51,0);
INSERT INTO Restaurant VALUES(330,'Hotel Hany Garden','Dabhel, Daman Ho',51,0);
INSERT INTO Restaurant VALUES(331,'Hotel Ocean Inn','Near Devka Beach, Daman Ho',51,0);
INSERT INTO Restaurant VALUES(332,'Legacy Bar & Restaurant (Ho...','Masal Chowk, Nani Daman',51,0);
INSERT INTO Restaurant VALUES(333,'Sai Sarovar Restaurant and Bar','Talao Road, Daman Ho',51,0);
INSERT INTO Restaurant VALUES(334,'Hotel Ganga Recidency','Darbanga, Darbhanga Ho',52,0);
INSERT INTO Restaurant VALUES(335,'Radhe Radhe Restaurant','Darbhanga, Darbhanga Ho',52,0);
INSERT INTO Restaurant VALUES(336,'Tandoor Plaza','Rahamganj, D M C',52,0);
INSERT INTO Restaurant VALUES(337,'Ritu Raj Family Restaurant','Bhagat Singh Chowk, Darbhanga Ho',52,0);
INSERT INTO Restaurant VALUES(338,'Swadisht Restaurant','Darbhanga Ho',52,0);
INSERT INTO Restaurant VALUES(339,'Caffeteria','Donar Road, Darbhanga Ho',52,0);
INSERT INTO Restaurant VALUES(340,'Mithila Foods','Hasan Chok, Darbhanga Ho',52,0);
INSERT INTO Restaurant VALUES(341,'Sanjha Sulha Restaurant','Parvati Valley, Kullu H O',53,0);
INSERT INTO Restaurant VALUES(342,'Annapurna Hotel And Bhojnalaya','Manali Road, Kullu H O',53,0);
INSERT INTO Restaurant VALUES(343,'Shiva Paradise Cafe','Manu Temple, Kullu H O',53,0);
INSERT INTO Restaurant VALUES(344,'Dev Dham Restaurant','Kullu Manali, Kullu H O',53,0);
INSERT INTO Restaurant VALUES(345,'Sandhya Restaurant','Near Airport Bhuntar, Shamshi',53,0);
INSERT INTO Restaurant VALUES(346,'City Choice Restaurant','Shastri Nagar, Kullu H O',53,0);
INSERT INTO Restaurant VALUES(347,'Khushi Restaurant','Circuit House, Kullu H O',53,0);
INSERT INTO Restaurant VALUES(348,'Dominos Pizza','La Denla, Darjeeling H O',54,22);
INSERT INTO Restaurant VALUES(349,'Pizza Hut','Mall Road, Darjeeling H O',54,25);
INSERT INTO Restaurant VALUES(350,'KFC Restaurant','Nehru Road, Darjeeling H O',54,30);
INSERT INTO Restaurant VALUES(351,'Hotel 717','West Bengal, Darjeeling H O',54,0);
INSERT INTO Restaurant VALUES(352,'Cafe Coffee Day','Landenla Road, Darjeeling H O',54,0);
INSERT INTO Restaurant VALUES(353,'Rodeo CAFE & RESTAURANT','Rajpur, Dehradun City',55,0);
INSERT INTO Restaurant VALUES(354,'What A Place','GMS Road, Dehradun City',55,0);
INSERT INTO Restaurant VALUES(355,'Anandam Restaurant','Rajpur Road, Rajpur Road',55,0);
INSERT INTO Restaurant VALUES(356,'Kabila Authentic Rajasthani...','Hotel Great Value, Dehradun City',55,0);
INSERT INTO Restaurant VALUES(357,'Just Mughlai','Chakrata Road, Dehradun City',55,0);
INSERT INTO Restaurant VALUES(358,'Kathi Junction Resturant','Area University, Clement Town',55,0);
INSERT INTO Restaurant VALUES(359,'Nazar Restaurant','Ec Road, Dehradun City',55,0);
INSERT INTO Restaurant VALUES(360,'Purple Circle Hookah Lounge','Gt Road, Model Town Ghaziabad',56,0);
INSERT INTO Restaurant VALUES(361,'Made In Punjab','Dlf Cyber, Dlf Cyber City',56,0);
INSERT INTO Restaurant VALUES(362,'Moti Mahal Deluxe Tandoori ...','Netaji Subhash Place Complex-Pitampura',56,0);
INSERT INTO Restaurant VALUES(363,'New Vishals Kitchen','Ganga Shopping, Noida Sector 29',56,0);
INSERT INTO Restaurant VALUES(364,'Priviledge Punjab','Vishal Enclave-Rajouri Garden',56,0);
INSERT INTO Restaurant VALUES(365,'Uforia Kitchen & Lounge Bar','Mg Road, Mg Road',56,0);
INSERT INTO Restaurant VALUES(366,'Aashiana Restaurant','Punjab National Bank, Ram Puri',56,0);
INSERT INTO Restaurant VALUES(367,'Shri SAI Hotel & Restaurant','Sardar Panda, B Deoghar HO',57,0);
INSERT INTO Restaurant VALUES(368,'FOODCOURT','Netaji Subhash, B Deoghar HO',57,0);
INSERT INTO Restaurant VALUES(369,'Shri Ram Bhojnalaya','B RAI, B Deoghar Ho',57,0);
INSERT INTO Restaurant VALUES(370,'Vineet Restaurant','Main Road, B Deoghar Ho',57,0);
INSERT INTO Restaurant VALUES(371,'Pandit Bhojanalaya','B Roy, B Deoghar Ho',57,0);
INSERT INTO Restaurant VALUES(372,'Ram Puja Bhandar','B Roy, B Deoghar Ho',57,0);
INSERT INTO Restaurant VALUES(373,'Khana Khazana Restaurant','Hotel Raj, B Deoghar Ho',57,22);
INSERT INTO Restaurant VALUES(374,'Dominos Pizza','Main Road, Dhanbad Ho',58,22);
INSERT INTO Restaurant VALUES(375,'Dominos Pizza','Govindpur Main Road, Saraidhela',58,22);
INSERT INTO Restaurant VALUES(376,'KFC Restaurant','Ground Floor, Shastri Nagar',58,30);
INSERT INTO Restaurant VALUES(377,'Comesum Food Plaza','Dhanbad Ho',58,31);
INSERT INTO Restaurant VALUES(378,'Seventeen Degrees Restaurant','Ashok Nagar, Dhanbad Ho',58,0);
INSERT INTO Restaurant VALUES(379,'Seventh Heaven Restaurant','Main Road, Jharia',58,0);
INSERT INTO Restaurant VALUES(380,'Mcllo Restaurant','Main Square, Mcleod Ganj',59,0);
INSERT INTO Restaurant VALUES(381,'Dominos Pizza','Kautwali Bazar, Dharamshala Ho',59,22);
INSERT INTO Restaurant VALUES(382,'PIZZA HUT','Dharamkot road, Mcleod Ganj',59,25);
INSERT INTO Restaurant VALUES(383,'BLACK MAGIC RESTURENT AND BAR','Jogiwara road, Mcleod Ganj',59,0);
INSERT INTO Restaurant VALUES(384,'Bobs The Family Restaurant','Post Office Dal Lake, Naddi',59,0);
INSERT INTO Restaurant VALUES(385,'Namgyal Cafe','Temple Road, Dharamshala Ho',59,0);
INSERT INTO Restaurant VALUES(386,'Big Chick Fried Chicken','By Pass Road, Dharmapuri Ho',60,0);
INSERT INTO Restaurant VALUES(387,'Akshaya Multicuisine Family Re...','Bye Pass Road, Dharmapuri Ho',60,0);
INSERT INTO Restaurant VALUES(388,'Dng Bar','Bye Pass Road, Dharmapuri Ho',60,0);
INSERT INTO Restaurant VALUES(389,'Sri Rama Vilas Hotel','Salem Main Road, Dharmapuri Ho',60,0);
INSERT INTO Restaurant VALUES(390,'A2b Veg Restaurant','National Highway, Nallampalli',60,0);
INSERT INTO Restaurant VALUES(391,'Hotel Anandha Bhavan','Dharmapuri Main Road, Pennagaram',60,0);
INSERT INTO Restaurant VALUES(392,'Global Century Chickens City','Salem High Road, Dharmapuri Ho',60,0);
INSERT INTO Restaurant VALUES(393,'Hotel Rajeet','New Digha, Digha New Township',61,0);
INSERT INTO Restaurant VALUES(394,'Antara Restaurants','New Digha, Digha New Township',61,0);
INSERT INTO Restaurant VALUES(395,'Purbasha Hotel And Resraurant','Digha Road, Digha',61,0);
INSERT INTO Restaurant VALUES(396,'New Purbasha Hotel & Restaurants','Digha Road, Digha',61,0);
INSERT INTO Restaurant VALUES(397,'New Sagar Saikat Hotel & Resta...','Pani Sweet Shope, Digha',61,0);
INSERT INTO Restaurant VALUES(398,'Tirupati Hotel & Restaurant','Near Sani, Digha New Township',61,0);
INSERT INTO Restaurant VALUES(399,'Parijat Hotel And Restaurant','Digha Road, Digha',61,0);
INSERT INTO Restaurant VALUES(400,'Hotel Apaar','Goverment Parking, Diu Ho',62,0);
INSERT INTO Restaurant VALUES(401,'Apana Hotel','Fort Road, Diu Ho',62,0);
INSERT INTO Restaurant VALUES(402,'Hotel Ashiyana','Luharwada, Diu Ho',62,0);
INSERT INTO Restaurant VALUES(403,'Gangasagar hotel','Nagva road, Diu HO',62,0);
INSERT INTO Restaurant VALUES(404,'Apaar Restaurant','Opposite Government Parking, Diu',62,0);
INSERT INTO Restaurant VALUES(405,'Palacio De Diu Restaurant & Bar','Parsiwada, Diu',62,0);
INSERT INTO Restaurant VALUES(406,'Mozambique Bar','Main Vegetable Market, Diu',62,0);
INSERT INTO Restaurant VALUES(407,'Dwarkesh Restaurant','Swaminarayan Temple, Dwarka HO',63,0);
INSERT INTO Restaurant VALUES(408,'Aarti Restaurant','Shivrajsinh Road, Dwarka Ho',63,0);
INSERT INTO Restaurant VALUES(409,'Maruti Restaurant','Dhirubhai Ambani Road, Dwarka HO',63,0);
INSERT INTO Restaurant VALUES(410,'PRASAD RESTAURANT','kandas bapu ashram, Dwarka HO',63,0);
INSERT INTO Restaurant VALUES(411,'Purushottam Parotha House & Pu...','Bhadrakali Road, Dwarka HO',63,0);
INSERT INTO Restaurant VALUES(412,'Blue Coriander Restaurant','Near Gayatri Temple, Dwarka HO',63,0);
INSERT INTO Restaurant VALUES(413,'Farm House Garden Family Re...','Mulgaon, Vasai West',64,0);
INSERT INTO Restaurant VALUES(414,'Daras Dhaba/ Zest','Mumbai Nasik Highway, Bhiwandi',64,0);
INSERT INTO Restaurant VALUES(415,'Rude Lounge','Hill Road, Bandra West',64,0);
INSERT INTO Restaurant VALUES(416,'High Point Veg Restaurant','Lokhandwala Complex-Andheri West',64,0);
INSERT INTO Restaurant VALUES(417,'Rude Lounge','Lbs Marg, Mulund West',64,0);
INSERT INTO Restaurant VALUES(418,'Rude Lounge','Hanuman Mandir, Malad West',64,0);
INSERT INTO Restaurant VALUES(419,'Spices And Flavours','Hamam Street, Fort',64,0);
INSERT INTO Restaurant VALUES(420,'Hotel Garden View Residency & ...','Shiv Mohalla, Giridih Ho',65,0);
INSERT INTO Restaurant VALUES(421,'Shree Ashoka Hotel','Court Road, Giridih Ho',65,0);
INSERT INTO Restaurant VALUES(422,'Bewakoof Hotel','Kachehari Road, Giridih Ho',65,0);
INSERT INTO Restaurant VALUES(423,'Bewakoof Restaurant','Bus Stand Road, Giridih Ho',65,0);
INSERT INTO Restaurant VALUES(424,'Hotel Bewakoof No .-1','Kachehari Road, Giridih Ho',65,0);
INSERT INTO Restaurant VALUES(425,'Brindaban Sweets & Snacks','Barganda Road, Giridih Ho',65,0);
INSERT INTO Restaurant VALUES(426,'Zaika Fast Food','Barganda Road, Giridih Ho',65,0);
INSERT INTO Restaurant VALUES(427,'Mainland China Restaurant','New Link Road, Andheri West',66,26);
INSERT INTO Restaurant VALUES(428,'Hotel Capitol','Ghodbunder Road, Thane West',66,0);
INSERT INTO Restaurant VALUES(429,'Svenska Design Hotels Resta...','SAB TV Road, Andheri West',66,0);
INSERT INTO Restaurant VALUES(430,'UFO Revolving Restaurant','Asha Nagar-Kandivali East',66,0);
INSERT INTO Restaurant VALUES(431,'Baraesti Grill Bar & Beyond','Tagore Road, Tardeo',66,0);
INSERT INTO Restaurant VALUES(432,'Flamboyante Restaurant','Cuffe Parade-Colaba',66,0);
INSERT INTO Restaurant VALUES(433,'Food Inn','Lokhandwala Complex-Andheri West',66,0);
INSERT INTO Restaurant VALUES(434,'Hotel Dwaraka Bar And Restaurants','Kumta,',67,0);
INSERT INTO Restaurant VALUES(435,'Hotel Sadanand','Karwar, Chendiye',67,0);
INSERT INTO Restaurant VALUES(436,'Hotel Vinaya','Chendia, Chendiye',67,0);
INSERT INTO Restaurant VALUES(437,'SRI Gajanan Restaurant','Honavar,',67,0);
INSERT INTO Restaurant VALUES(438,'Shweta Lunch Home','Green Street, Karwar Ho',67,0);
INSERT INTO Restaurant VALUES(439,'Hotel Sona Palace','Highchurchroad, Karwar',67,0);
INSERT INTO Restaurant VALUES(440,'Poornima Restaurant','Main Road, Karwar Ho',67,0);
INSERT INTO Restaurant VALUES(441,'City Grill','Vinayaka Temple, Cbm Compound',68,0);
INSERT INTO Restaurant VALUES(442,'Red Cherry Restaurant','National Highway 5, Gajuwaka',68,0);
INSERT INTO Restaurant VALUES(443,'Mfc My Favourite Chicken','Rk Beach Road, Rk Beach',68,0);
INSERT INTO Restaurant VALUES(444,'Spicy Platter','Brahma Towers, Pedawaltair',68,0);
INSERT INTO Restaurant VALUES(445,'Subway Restaurant','Balaji Nagar, Siripuram',68,0);
INSERT INTO Restaurant VALUES(446,'Bunnys Pizza Bakery & Resta...','Vizag Steel Gate, Kurmannapalem',68,0);
INSERT INTO Restaurant VALUES(447,'Mynt Multi Cuisine Restaurant','MVP colony, Mvp Colony',68,0);
INSERT INTO Restaurant VALUES(448,'Highlands Park Restaurant','C/O Hotel Highlands Park, Gulmarg',69,0);
INSERT INTO Restaurant VALUES(449,'BAKSHI VEG RESTAURANT','Gulmarg, Gulmarg',69,0);
INSERT INTO Restaurant VALUES(450,'Sun N Snow Restaurant','Near J&K Bank, Gulmarg',69,0);
INSERT INTO Restaurant VALUES(451,'Mama Restaurant','Gulmarg',69,0);
INSERT INTO Restaurant VALUES(452,'Royal Garden','C/O Royal Park Hotel, Gulmarg',69,0);
INSERT INTO Restaurant VALUES(453,'Moving Tick','C/O Gulmarg Sahara Hotel, Gulmarg',69,0);
INSERT INTO Restaurant VALUES(454,'Kongposh Restaurant','Gulmarg',69,0);
INSERT INTO Restaurant VALUES(455,'Hotel Saizad Bawarchi','Boisar Palghar Road, Boisar',70,0);
INSERT INTO Restaurant VALUES(456,'Hotel Capitol','Ghodbunder Road, Thane West',70,0);
INSERT INTO Restaurant VALUES(457,'UFO Revolving Restaurant','Asha Nagar-Kandivali East',70,0);
INSERT INTO Restaurant VALUES(458,'Rude Lounge','Lbs Marg, Mulund West',70,0);
INSERT INTO Restaurant VALUES(459,'Mainland China Restaurant','New Link Road, Andheri West',70,26);
INSERT INTO Restaurant VALUES(460,'Flamboyante Restaurant','Cuffe Parade-Colaba',70,0);
INSERT INTO Restaurant VALUES(461,'Svenska Design Hotels Resta...','SAB TV Road, Andheri West',70,0);
INSERT INTO Restaurant VALUES(462,'7 Spice Restaurant','Near Jah Hospital, Gwalior HO',71,0);
INSERT INTO Restaurant VALUES(463,'Salt N Pepper Restaurant','Opposite Medical College, Lashkar',71,0);
INSERT INTO Restaurant VALUES(464,'The Yellow Chilli','Aditya College, City Centre',71,0);
INSERT INTO Restaurant VALUES(465,'Hakeems Restaurant','Nai Dunia Press, City Centre',71,0);
INSERT INTO Restaurant VALUES(466,'Kwality Restaurant','Green Garden Road, City Centre',71,0);
INSERT INTO Restaurant VALUES(467,'Cooks Fast Food & Bakery','Old High Court Road, Lashkar',71,0);
INSERT INTO Restaurant VALUES(468,'Karchi Kadhai Restaurant','Tendulkar Marg, City Centre',71,0);
INSERT INTO Restaurant VALUES(469,'Athidi Restaurant','SAI Baba, Tb Dam Road',72,0);
INSERT INTO Restaurant VALUES(470,'Prince Restaurant','Near Irupaksha Temple, Hampi',72,0);
INSERT INTO Restaurant VALUES(471,'Bellary Biryani Paradise','Hakka Bukka Road, Hospet Ho',72,0);
INSERT INTO Restaurant VALUES(472,'Ice Land','Near Bus Stand, College Road',72,0);
INSERT INTO Restaurant VALUES(473,'Vijayshree Resort And Herit...','Humpi Road, Hampi Road',72,0);
INSERT INTO Restaurant VALUES(474,'Mango Tree Restaurant','Near Virupaksha Temple, Hampi',72,0);
INSERT INTO Restaurant VALUES(475,'BFC Restaurant','Hakka Bukka Road, Hospet Ho',72,0);
INSERT INTO Restaurant VALUES(476,'Naivedyam Bhog','Near Dakhsh Temple, Kankhal',73,0);
INSERT INTO Restaurant VALUES(477,'Dominos Pizza','Main Road, Govind Puri',73,22);
INSERT INTO Restaurant VALUES(478,'Pizza Hut','Ranipur More, Govind Puri',73,25);
INSERT INTO Restaurant VALUES(479,'Pizza Italiano','Ranipur More, Haridwar H O',73,0);
INSERT INTO Restaurant VALUES(480,'Bikanervala','Sidcul, Haridwar H O',73,5);
INSERT INTO Restaurant VALUES(481,'Captains Cavalry Restrobar','Pentagon Mall, Haridwar H O',73,0);
INSERT INTO Restaurant VALUES(482,'Parijata Veg Restaurant','School Field, Kr Puram Hassan',74,0);
INSERT INTO Restaurant VALUES(483,'Hotel New Star','Shubash Square, Subhash Square',74,0);
INSERT INTO Restaurant VALUES(484,'Meridian Restaurant','Sharanya Arcade, Harshamahal Road',74,0);
INSERT INTO Restaurant VALUES(485,'Cafe Coffee Day','Udayapura, Channarayapatna',74,0);
INSERT INTO Restaurant VALUES(486,'Hotel Ashok','B H Road, Arsikere',74,0);
INSERT INTO Restaurant VALUES(487,'Goli Vada Pav','Sahyadri Circle, Salagame',74,6);
INSERT INTO Restaurant VALUES(488,'Mirchi Restaurant','Okli Road, Hazaribagh H O',75,0);
INSERT INTO Restaurant VALUES(489,'Zaika Restaurant','G S, Hazaribagh H O',75,0);
INSERT INTO Restaurant VALUES(490,'Blueberries restaurant','Burhwa Mahadeo, Hazaribagh H O',75,0);
INSERT INTO Restaurant VALUES(491,'Raj Restaurant','Hazaribagh City, Hazaribagh H O',75,0);
INSERT INTO Restaurant VALUES(492,'Hotel Ding Dong','Hazaribag City, Hazaribagh H O',75,0);
INSERT INTO Restaurant VALUES(493,'New Kwality Restaurant','Hotel Sky Lok, Bansilal Chowk',75,0);
INSERT INTO Restaurant VALUES(494,'S.P. Chicken Centre','Pennagaram, Pennagaram',76,0);
INSERT INTO Restaurant VALUES(495,'Hotel Shri Bhavan','Raju Nagar, Pennagaram',76,0);
INSERT INTO Restaurant VALUES(496,'Hotel Anandha Bhavan','Dharmapuri Main Road, Pennagaram',76,0);
INSERT INTO Restaurant VALUES(497,'Hotel Anandham','Bus Stand, Pennagaram',76,0);
INSERT INTO Restaurant VALUES(498,'Saravana Biryani Hotel','Bazzar Street, Pennagaram',76,11);
INSERT INTO Restaurant VALUES(499,'Ranjith Cooldrinks','Bazzar Street, Pennagaram',76,0);
INSERT INTO Restaurant VALUES(500,'Hotel Madhu','Hogenakal Main Road, Pennagaram',76,0);
INSERT INTO Restaurant VALUES(501,'Vishnuji Ki Rasoi','G B Road, Thane West',77,0);
INSERT INTO Restaurant VALUES(502,'Rude Lounge','Hill Road, Bandra West',77,0);
INSERT INTO Restaurant VALUES(503,'Rude Lounge','Lbs Marg, Mulund West',77,0);
INSERT INTO Restaurant VALUES(504,'High Point Veg Restaurant','Lokhandwala Complex-Andheri West',77,0);
INSERT INTO Restaurant VALUES(505,'Rude Lounge','Hanuman Mandir, Malad West',77,0);
INSERT INTO Restaurant VALUES(506,'Spices And Flavours','Hamam Street, Fort',77,0);
INSERT INTO Restaurant VALUES(507,'Gold Coins Restaurant & Ban...','Tardeo Rd, Tardeo',77,0);
INSERT INTO Restaurant VALUES(508,'78 Degrees East Restaurant','Opposite Petrol Bunk, Habsiguda',78,0);
INSERT INTO Restaurant VALUES(509,'Hotel Nakshatra Inn','Abvoe Bakers Q, Dilsukh Nagar',78,0);
INSERT INTO Restaurant VALUES(510,'Hotel One Place','Kphb Bus Stop, KPHB Colony',78,0);
INSERT INTO Restaurant VALUES(511,'Genx Kasani','Plot No:2, Guttala Begumpet',78,0);
INSERT INTO Restaurant VALUES(512,'Swaadh And Tiny Village','Near Botanical Garden, Kondapur',78,0);
INSERT INTO Restaurant VALUES(513,'Tabla Fine Dine And  Banque...','Road No 1, Banjara Hills',78,0);
INSERT INTO Restaurant VALUES(514,'Sizzling Grillz','Kothaguda Cross Road, Kondapur',78,0);
INSERT INTO Restaurant VALUES(515,'Punjab Restaurant','Income Tax, Napier Town Jabalpur',79,0);
INSERT INTO Restaurant VALUES(516,'Atithi Restaurant (Hotel Pa...','Manas Bhawan, Jabalpur Ho',79,0);
INSERT INTO Restaurant VALUES(517,'Peppers Restaurant','Chowk, Napier Town Jabalpur',79,0);
INSERT INTO Restaurant VALUES(518,'R H Chicken Point','Sadar Main Road, Sadar',79,0);
INSERT INTO Restaurant VALUES(519,'The Shaukeens','Sudharshan, Napier Town Jabalpur',79,0);
INSERT INTO Restaurant VALUES(520,'Govindam Catering Services','Gopal Vihar, Damoh Naka',79,0);
INSERT INTO Restaurant VALUES(521,'Moti Mahal Delux','Sadar Main Road, Sadar',79,0);
INSERT INTO Restaurant VALUES(522,'Laxman Avenue Restaurant','Murthy Line Road, Jagdalpur HO',80,0);
INSERT INTO Restaurant VALUES(523,'Suri International Restaurant','Geedam Road, Jagdalpur HO',80,0);
INSERT INTO Restaurant VALUES(524,'Rainbow Restaurant','Palace Road, Jagdalpur HO',80,0);
INSERT INTO Restaurant VALUES(525,'Hotel Chetak Bar & Restaurant','Bus Stand Road, Jagdalpur Ho',80,0);
INSERT INTO Restaurant VALUES(526,'Mahaveer Thali Restaurant','Chhattisgarh, Jagdalpur Ho',80,0);
INSERT INTO Restaurant VALUES(527,'Vaishnavi Restaurant','Kasturba Marg, Jagdalpur HO',80,0);
INSERT INTO Restaurant VALUES(528,'Kutumsar Restaurant','Dhurkoda Road, Jagdalpur HO',80,0);
INSERT INTO Restaurant VALUES(529,'Thali House','Station Road, Station Road Jaipur',81,0);
INSERT INTO Restaurant VALUES(530,'Jammies Kitchen','Green Park, Vaishali Nagar',81,0);
INSERT INTO Restaurant VALUES(531,'Murli Green Multicuisine Re...','Sirsi Road, Vaishali Nagar',81,0);
INSERT INTO Restaurant VALUES(532,'Bayleaf Restaurant','Girdhar Marg, Malviya Nagar',81,0);
INSERT INTO Restaurant VALUES(533,'Basil Restaurant   By Hotel...','Bank Of Baroda, Khatipura',81,0);
INSERT INTO Restaurant VALUES(534,'Sky Waltz Cafe(Highway Resa...','/ Nims University, Achrol',81,0);
INSERT INTO Restaurant VALUES(535,'Hotel Ganesham & Restaurant','Feet Bypass Road, Vaishali Nagar',81,0);
INSERT INTO Restaurant VALUES(536,'Free Tibet Restaurant','On Fort, Jaisalmer Ho',82,0);
INSERT INTO Restaurant VALUES(537,'Restaurant Royal Rasoi','Dhibba Para, Jaisalmer HO',82,0);
INSERT INTO Restaurant VALUES(538,'The Surya Restaurant','Kothari Para, Jaisalmer Ho',82,0);
INSERT INTO Restaurant VALUES(539,'Royal Haveli Roof Top Restaurant','Dhiba Para, Jaisalmer Ho',82,0);
INSERT INTO Restaurant VALUES(540,'Hotel Jaisalgarh','By Pass Road, Jaisalmer Ho',82,0);
INSERT INTO Restaurant VALUES(541,'Trio Restaurants','Gandhi Chowk, Jaisalmer Ho',82,0);
INSERT INTO Restaurant VALUES(542,'Desert Bite','Gram Khadi Bhandar, Jaisalmer Ho',82,0);
INSERT INTO Restaurant VALUES(543,'Vimpis Pizza','Gandhi Nagar, Gandhinagar Jammu',83,0);
INSERT INTO Restaurant VALUES(544,'Imperial Grill','Bahu Plaza, Gandhinagar Jammu',83,0);
INSERT INTO Restaurant VALUES(545,'Zaika Restaurant','Sector 3 Jammu, Trikuta Nagar',83,0);
INSERT INTO Restaurant VALUES(546,'Amritsarian Di Hatti','Raghunath Bazar, R N Bazar',83,0);
INSERT INTO Restaurant VALUES(547,'Dominos Pizza','Samadhian Road, Jammu Tawi',83,22);
INSERT INTO Restaurant VALUES(548,'Dominos Pizza','Canal Road, Jammu Ho',83,22);
INSERT INTO Restaurant VALUES(549,'Dominos Pizza','Rail Head Complex, Jammu Ho',83,22);
INSERT INTO Restaurant VALUES(550,'Ashirwad Club Resort','D P, Jamnagar Khodiyar Colony',84,0);
INSERT INTO Restaurant VALUES(551,'Tavaa Restaurant','Khoja Gate, Jamnagar Ho',84,0);
INSERT INTO Restaurant VALUES(552,'Ashirwad Club Resort','D P Road, Jamnagar Ho',84,0);
INSERT INTO Restaurant VALUES(553,'Dominos Pizza','Cross Bedi, Bedi Bunder Road',84,22);
INSERT INTO Restaurant VALUES(554,'US Pizza','40 Feet Road, Patel Colony',84,0);
INSERT INTO Restaurant VALUES(555,'Pizza Zone','Bedi Bandar Road, Jamnagar Ho',84,0);
INSERT INTO Restaurant VALUES(556,'Rajwadu The Village Restaurant','Dwarka Highway, Patel Colony',84,0);
INSERT INTO Restaurant VALUES(557,'The Blues Restaurant and Bar','Kalimati Road, Sakchi',85,0);
INSERT INTO Restaurant VALUES(558,'Bon Appetit Restaurant','Inner Circle Road, Bistupur',85,0);
INSERT INTO Restaurant VALUES(559,'Gourmet','New Baradwari, Sakchi',85,0);
INSERT INTO Restaurant VALUES(560,'White Rose Restaurant','Aambagan, Sakchi',85,0);
INSERT INTO Restaurant VALUES(561,'Dastarkhan Restaurant','Bistupur Main Road, Bistupur',85,0);
INSERT INTO Restaurant VALUES(562,'Hotel Jiva','Sakchi New Planning Area, Sakchi',85,0);
INSERT INTO Restaurant VALUES(563,'Triangle Bar And Restaurant','Behind Basant Cinema, Sakchi',85,0);
INSERT INTO Restaurant VALUES(564,'Hotel Ambrosia And Restaurants','Sipri Bazar, Sipri Bazar',86,0);
INSERT INTO Restaurant VALUES(565,'Xpress Delivers','Elite Crossing, Jhansi City',86,0);
INSERT INTO Restaurant VALUES(566,'Dominos Pizza','Land No.222, Civil Lines',86,22);
INSERT INTO Restaurant VALUES(567,'Food Delivery in Train at Jhan...','Jhansi Railway Station',86,0);
INSERT INTO Restaurant VALUES(568,'Tulsi Restaurant','Chitra Cinema Chowk, Civil Lines',86,0);
INSERT INTO Restaurant VALUES(569,'Nav Bharat Restaurant','Sadar Thana, Jhansi Sadar Bazar',86,0);
INSERT INTO Restaurant VALUES(570,'Janakash Restaurants','Elite Choraha, Jhansi Ho',86,0);
INSERT INTO Restaurant VALUES(571,'Firepot & Tropical Roof Res...','11 C Road, Sardarpura',87,0);
INSERT INTO Restaurant VALUES(572,'Midtown Ac Veg Restaurant','Station, Railway Station Road',87,0);
INSERT INTO Restaurant VALUES(573,'Hari Vedas','11th C Road, Sardarpura',87,0);
INSERT INTO Restaurant VALUES(574,'Nirali Dhani A Group Of Shr...','Link, Chopasni Road Choraya',87,0);
INSERT INTO Restaurant VALUES(575,'Innings & Rasvyanjan Restau...','Shopping Centre, Shastri Nagar',87,0);
INSERT INTO Restaurant VALUES(576,'Saffron Foodz','Chopasni Main Road, Chopasni Road',87,0);
INSERT INTO Restaurant VALUES(577,'Spicy Kitchen Restaurant','Main Pal Road, Pal Road',87,0);
INSERT INTO Restaurant VALUES(578,'B And B','By Pass Road, Baner',88,0);
INSERT INTO Restaurant VALUES(579,'Hotel Shaurya','Aundh Wakad  Road, Wakad',88,0);
INSERT INTO Restaurant VALUES(580,'Malaka Spice Restaurant','Baner Road, Baner',88,41);
INSERT INTO Restaurant VALUES(581,'Aundh Retreat','D P Road, Aundh',88,0);
INSERT INTO Restaurant VALUES(582,'Malaka Spice Restaurant','Lane No 5, Koregaon Park',88,41);
INSERT INTO Restaurant VALUES(583,'Hotel Dreams Restaurants','MIDC Road, Talawade',88,0);
INSERT INTO Restaurant VALUES(584,'Skye Resto Lounge','To Marriot, Senapati Bapat Road',88,0);
INSERT INTO Restaurant VALUES(585,'Leo Resort','Taleti Road, Junagadh Ho',89,0);
INSERT INTO Restaurant VALUES(586,'Hotel Vrajbhumi','Vanthali Road, Junagadh Ho',89,0);
INSERT INTO Restaurant VALUES(587,'Hotel Giriraj','Vanthali Road, Vanthali',89,0);
INSERT INTO Restaurant VALUES(588,'Patel Vihar Restaurant','Rajkot Highway, Dolatpura',89,0);
INSERT INTO Restaurant VALUES(589,'Patel Parotha House & Dinni...','Kalwa Chowk, Junagadh Ho',89,0);
INSERT INTO Restaurant VALUES(590,'Hot N Spice','Khaun Bazar, Junagadh Ho',89,0);
INSERT INTO Restaurant VALUES(591,'Patel Dining Hall','S T Road, Junagadh Ho',89,0);
INSERT INTO Restaurant VALUES(592,'The Silver Oaks','King Pong Road, Kalimpong Ho',90,0);
INSERT INTO Restaurant VALUES(593,'Cafe Refuel','State Highway 12, Kalimpong Ho',90,0);
INSERT INTO Restaurant VALUES(594,'Vertigo','Rissi Road, Kalimpong Ho',90,0);
INSERT INTO Restaurant VALUES(595,'Mandarin Restaurant','Motor Stand, Kalimpong HO',90,0);
INSERT INTO Restaurant VALUES(596,'Oaks Bar','Silver Oaks Hotel, Kalimpong HO',90,0);
INSERT INTO Restaurant VALUES(597,'Monarch Restaurants','& 1/2 Mile, Kalimpong Ho',90,0);
INSERT INTO Restaurant VALUES(598,'The Room With A View','Rishi Road, Kalimpong Ho',90,0);
INSERT INTO Restaurant VALUES(599,'Lake View Highway Multicuis...','Madurantakam Bypass, Madurantakam',91,0);
INSERT INTO Restaurant VALUES(600,'Moonrakers Restaurant','Othavadi Street, Mamallapuram',91,0);
INSERT INTO Restaurant VALUES(601,'Hotel Kanaka Sarovar','Thimmasamudram, Kanchipuram Rs',91,0);
INSERT INTO Restaurant VALUES(602,'Mannar Military Hotel','Sn Oodai Street, Kanchipuram Ho',91,0);
INSERT INTO Restaurant VALUES(603,'Sri Pugal Restaurant','Vandhavasi Bypass, Kanchipuram Rs',91,0);
INSERT INTO Restaurant VALUES(604,'Amlogs Muticuisine Restaurants','Pillayar Koil Street, Potheri',91,0);
INSERT INTO Restaurant VALUES(605,'Ananda Kolkata Coffee House','Pillaiyar Kovil Street, Potheri',91,0);
INSERT INTO Restaurant VALUES(606,'Hotel Panvel Palace','Old Mumbai Pune Highway, Panvel',92,0);
INSERT INTO Restaurant VALUES(607,'Rude Lounge','Hill Road, Bandra West',92,0);
INSERT INTO Restaurant VALUES(608,'Rude Lounge','Lbs Marg, Mulund West',92,0);
INSERT INTO Restaurant VALUES(609,'High Point Veg Restaurant','Lokhandwala Complex-Andheri West',92,0);
INSERT INTO Restaurant VALUES(610,'Rude Lounge','Hanuman Mandir, Malad West',92,0);
INSERT INTO Restaurant VALUES(611,'Spices And Flavours','Hamam Street, Fort',92,0);
INSERT INTO Restaurant VALUES(612,'Gold Coins Restaurant & Ban...','Tardeo Rd, Tardeo',92,0);
INSERT INTO Restaurant VALUES(613,'Khatta Meetha Restaurant & ...','Company Bagh, Nawabganj H O',93,0);
INSERT INTO Restaurant VALUES(614,'Bharat Restaurant','38/101, Meston Road',93,0);
INSERT INTO Restaurant VALUES(615,'Carnival Fine Dine Restaura...','Parvati Bagla Road, Tilak Nagar',93,0);
INSERT INTO Restaurant VALUES(616,'Rhubarb Fine Dine Restaurant','Govind Nagar Bridge, Fazal Ganj',93,0);
INSERT INTO Restaurant VALUES(617,'The Emperor Restaurants','Opposite Jimc, Saket Nagar',93,0);
INSERT INTO Restaurant VALUES(618,'New Santushti Restaurant','Triveni Market, Kidwai Nagar',93,0);
INSERT INTO Restaurant VALUES(619,'Solitaire Restaurant & Banquet','Mandir School, Swaroop Nagar',93,0);
INSERT INTO Restaurant VALUES(620,'Sun World Restaurants','Kovalam Road, Kanyakumari',94,0);
INSERT INTO Restaurant VALUES(621,'Hotel Ohm Saravana Bhava','Main Road, Kanyakumari',94,11);
INSERT INTO Restaurant VALUES(622,'Mubarak','Main Road Marthandam, Marthandam',94,0);
INSERT INTO Restaurant VALUES(623,'Taj Home Hotel','Complex Main Road, Marthandam',94,0);
INSERT INTO Restaurant VALUES(624,'Royal Paradise','Tiruvattar, Tiruvattar',94,0);
INSERT INTO Restaurant VALUES(625,'Sea Shell Restaurant','East Car Street, Kanyakumari',94,0);
INSERT INTO Restaurant VALUES(626,'Hotel Nuha Family Restaurant A/C','Kanyakumari, Thuckalay',94,0);
INSERT INTO Restaurant VALUES(627,'Carvan Restaurant','Near BSNL Office, Kargil Ho',95,0);
INSERT INTO Restaurant VALUES(628,'Tibetan Foods','Kargil Ho',95,0);
INSERT INTO Restaurant VALUES(629,'Hotel Pineview','Kasauli Road, Kasauli',96,0);
INSERT INTO Restaurant VALUES(630,'Hangout','Village Kimmughat, Kasauli',96,0);
INSERT INTO Restaurant VALUES(631,'Surya Rock Rose Restaurant','Chandigarh & Sh, Kasauli',96,0);
INSERT INTO Restaurant VALUES(632,'Hotel Whispering Winds','To Kasauli Road, Kasauli Solan',96,0);
INSERT INTO Restaurant VALUES(633,'Cafe Koncepts','Main Bazar, Kasauli Solan',96,0);
INSERT INTO Restaurant VALUES(634,'Cafe Coffee Day','Shimla Highway, Sanawar',96,0);
INSERT INTO Restaurant VALUES(635,'Cafe Coffee Day','Nh- 22, Dharampur',96,0);
INSERT INTO Restaurant VALUES(636,'Glory Restaurant','R Shah Rd, Almora Ho',97,0);
INSERT INTO Restaurant VALUES(637,'City Heart Restaurant','Uttrakhand-263601, Almora Ho',97,0);
INSERT INTO Restaurant VALUES(638,'Royal Foods','Dharanaula Almora, Almora Ho',97,0);
INSERT INTO Restaurant VALUES(639,'Bird Song Restaurant','Almora Bageshwar Road, Almora Ho',97,0);
INSERT INTO Restaurant VALUES(640,'The Kumaon Room Restaurant','Ranikhet, Almora Ho',97,0);
INSERT INTO Restaurant VALUES(641,'Joshjus Restaurant','Mall Road, Almora Ho',97,0);
INSERT INTO Restaurant VALUES(642,'Hotel Shreekshetra International','Dhangarpada, Joda',98,0);
INSERT INTO Restaurant VALUES(643,'New Kaveri Bar & Restaurant','Barbil, Keonjhar Bazar',98,0);
INSERT INTO Restaurant VALUES(644,'Shankar Bar','Dhangarpada, Keonjhar Bazar',98,0);
INSERT INTO Restaurant VALUES(645,'Shree Krishna Restaurant','Madhapur,',98,0);
INSERT INTO Restaurant VALUES(646,'Hotel Gunjan','By Pass Road, Ghasipura',98,0);
INSERT INTO Restaurant VALUES(647,'New Dilkhush Non Veg Family...','Rathytra Road, Kamachha',99,0);
INSERT INTO Restaurant VALUES(648,'KINARA RESTURANTS','Pahariya Sarnath Road, Sarnath',99,0);
INSERT INTO Restaurant VALUES(649,'Cafe At Home','Bhu Road, Lanka',99,0);
INSERT INTO Restaurant VALUES(650,'Lemon Grass Fine Dine & Lou...','Near Mocchi Showroom, Lahurabir',99,0);
INSERT INTO Restaurant VALUES(651,'Hindustan Samrat Restautant','Nagar, Orderly Bazar',99,0);
INSERT INTO Restaurant VALUES(652,'ORCHIDS VEG RESTAURANT','Road, Durgakund',99,0);
INSERT INTO Restaurant VALUES(653,'Saffron Veg Restaurant','Girjaghar, Godowlia',99,0);
INSERT INTO Restaurant VALUES(654,'Raja Cafe','Main Road, Khajuraho Ho',100,0);
INSERT INTO Restaurant VALUES(655,'Green Wood Restaurant','Khajuraho Airport, Khajuraho Ho',100,0);
INSERT INTO Restaurant VALUES(656,'Garden View Restaurant','Tikri, Khajuraho Ho',100,0);
INSERT INTO Restaurant VALUES(657,'Kamini Bar','Airport Road, Khajuraho Ho',100,0);
INSERT INTO Restaurant VALUES(658,'Agrasen Restaurant','Jain Temple Road, Khajuraho Ho',100,0);
INSERT INTO Restaurant VALUES(659,'Isabel Palace Restaurant','Airport Road, Khajuraho Ho',100,0);
INSERT INTO Restaurant VALUES(660,'Gautama (Hotel Ramada)','Airport Road, Khajuraho Ho',100,0);

INSERT INTO Restaurant VALUES(661,'Panjappar Chettinad Restaurant','Airport Road',40,1);
INSERT INTO Restaurant VALUES(662,'Panjappar Chettinad Restaurant','AB Road',45,1);
INSERT INTO Restaurant VALUES(663,'Panjappar Chettinad Restaurant','Next to BC Chowk',43,1);
INSERT INTO Restaurant VALUES(664,'Panjappar Chettinad Restaurant','Outer Ring Road',36,1);
INSERT INTO Restaurant VALUES(665,'Panjappar Chettinad Restaurant','Safdarjung Avenue',37,1);
INSERT INTO Restaurant VALUES(666,'Annapoorna Gowrishankar','Airport Road',40,1);
INSERT INTO Restaurant VALUES(667,'Murugan Idli Shop','TB Road, GK',10,9);
INSERT INTO Restaurant VALUES(668,'Hyderabad Keema','Irani Chowk',44,40);
INSERT INTO Restaurant VALUES(669,'Manchester United Bar and Cafe','Omega Mall',71,17);
INSERT INTO Restaurant VALUES(670,'Namma Veedu Vasanta Bhavan','MJ Road, T Nagar',52,10);
INSERT INTO Restaurant VALUES(671,'Haldiram','Tilak Road, Near Railway Station',17,7);
INSERT INTO Restaurant VALUES(672,'Papa Johns Pizzas and Beverages','Sec. 34, P Nagar',36,33);
INSERT INTO Restaurant VALUES(673,'Comesum Food','Near Railway Station',53,31);
INSERT INTO Restaurant VALUES(674,'faasos','BC Stores, FG Road',26,14);
INSERT INTO Restaurant VALUES(675,'Adyar Ananda Bhavan','PK Namdar Road',60,3);
INSERT INTO Restaurant VALUES(676,'Sigree','D.Y Patil Complex',12,23);
INSERT INTO Restaurant VALUES(677,'Goli VadaPav','Next to Chillies Place, ET Nagar',93,6);
INSERT INTO Restaurant VALUES(678,'Heart Cup Cafe','ABC Book Store Complex',65,16);
INSERT INTO Restaurant VALUES(679,'Post 91 Bar & Restaurants','Caldecott Road',74,18);
INSERT INTO Restaurant VALUES(680,'Oh! Calcutta','S.No. 34/I, Indira Nagar',95,24);
INSERT INTO Restaurant VALUES(681,'Annapoorna Gowrishankar','OKT Place',93,2);
INSERT INTO Restaurant VALUES(682,'Haldiram','Near NH-10 Bus-Stop',51,7);
INSERT INTO Restaurant VALUES(683,'Mainland China','GH Road',82,26);
INSERT INTO Restaurant VALUES(684,'Sigree','',75,23);
INSERT INTO Restaurant VALUES(685,'Mainland China','',32,26);
INSERT INTO Restaurant VALUES(686,'Murugan Idli Shop','',51,9);
INSERT INTO Restaurant VALUES(687,'Pizza Hut','',73,25);
INSERT INTO Restaurant VALUES(688,'Murugan Idli Shop','',95,9);
INSERT INTO Restaurant VALUES(689,'Indian Coffee House','GT Road',99,29);
INSERT INTO Restaurant VALUES(690,'Indian Coffee House','',36,29);
INSERT INTO Restaurant VALUES(691,'Cafe Coffee Day','',50,28);
INSERT INTO Restaurant VALUES(692,'McDonalds','',72,37);
INSERT INTO Restaurant VALUES(693,'Oh! Calcutta','',48,24);
INSERT INTO Restaurant VALUES(694,'faasos','',21,14);
INSERT INTO Restaurant VALUES(695,'Adyar Ananda Bhavan','',80,3);
INSERT INTO Restaurant VALUES(696,'Biryani House','A.Chowk, Near Railway Station',97,39);
INSERT INTO Restaurant VALUES(697,'Biryani House','',46,39);
INSERT INTO Restaurant VALUES(698,'Dominoes India Pvt. Ltd.','GL Road',80,22);
INSERT INTO Restaurant VALUES(699,'Manchester United Bar and Cafe','',29,17);
INSERT INTO Restaurant VALUES(700,'Wow Momo','',16,35);
INSERT INTO Restaurant VALUES(701,'McDonalds','',67,37);
INSERT INTO Restaurant VALUES(702,'Namma Veedu Vasanta Bhavan','GOTE Complex',100,10);
INSERT INTO Restaurant VALUES(703,'US Pizza','',99,32);
INSERT INTO Restaurant VALUES(704,'KFC','',77,30);
INSERT INTO Restaurant VALUES(705,'Mainland China','',28,26);
INSERT INTO Restaurant VALUES(706,'Haldiram','GH Tennis Complex',64,7);
INSERT INTO Restaurant VALUES(707,'Speciality Group of Restaurants','Near Railway Station',29,12);
INSERT INTO Restaurant VALUES(708,'Hyderabad Keema','',40,40);
INSERT INTO Restaurant VALUES(709,'Oh! Calcutta','',63,24);
INSERT INTO Restaurant VALUES(710,'Moshe','',69,8);
INSERT INTO Restaurant VALUES(711,'Krishna Bhavan','',63,20);
INSERT INTO Restaurant VALUES(712,'Mad Over Donuts','',70,34);
INSERT INTO Restaurant VALUES(713,'Mad Over Donuts','Next to GP Mall',46,34);
INSERT INTO Restaurant VALUES(714,'Haldiram','',74,7);
INSERT INTO Restaurant VALUES(715,'Mad Over Donuts','',79,34);
INSERT INTO Restaurant VALUES(716,'McDonalds','',16,37);
INSERT INTO Restaurant VALUES(717,'Adyar Ananda Bhavan','',9,3);
INSERT INTO Restaurant VALUES(718,'Murugan Idli Shop','',40,9);
INSERT INTO Restaurant VALUES(719,'Cafe Coffee Day','',89,28);
INSERT INTO Restaurant VALUES(720,'Murugan Idli Shop','Oppo.Railway Station',79,9);
INSERT INTO Restaurant VALUES(721,'US Pizza','',37,32);
INSERT INTO Restaurant VALUES(722,'Post 91 Bar & Restaurants','',84,18);
INSERT INTO Restaurant VALUES(723,'Hyderabad Keema','',60,40);
INSERT INTO Restaurant VALUES(724,'Spices & Sauces','',89,13);
INSERT INTO Restaurant VALUES(725,'Wow Momo','',5,35);
INSERT INTO Restaurant VALUES(726,'Pizza Hut','OT Road',79,25);
INSERT INTO Restaurant VALUES(727,'McDonalds','',58,37);
INSERT INTO Restaurant VALUES(728,'Annapoorna Gowrishankar','',1,2);
INSERT INTO Restaurant VALUES(729,'Papa Johns Pizzas and Beverages','',62,33);
INSERT INTO Restaurant VALUES(730,'Residency Clubs','Circuit House Road',54,19);
INSERT INTO Restaurant VALUES(731,'Goli VadaPav','',15,6);
INSERT INTO Restaurant VALUES(732,'KFC','',20,30);
INSERT INTO Restaurant VALUES(733,'Post 91 Bar & Restaurants','Elphinston Road',77,18);
INSERT INTO Restaurant VALUES(734,'Sigree','',41,23);
INSERT INTO Restaurant VALUES(735,'Krishna Bhavan','Next to Raichur Stores',27,20);
INSERT INTO Restaurant VALUES(736,'McDonalds','Near GH College of Commerce',22,37);
INSERT INTO Restaurant VALUES(737,'Residency Clubs','',29,19);
INSERT INTO Restaurant VALUES(738,'South India Foods','Inside GH Techological College Campus',45,38);
INSERT INTO Restaurant VALUES(739,'Cafe Coffee Day','',41,28);
INSERT INTO Restaurant VALUES(740,'Heart Cup Cafe','Next to Railway Station',28,16);
INSERT INTO Restaurant VALUES(741,'Sigree','',83,23);
INSERT INTO Restaurant VALUES(742,'Adyar Ananda Bhavan','FT Commercial Complex',8,3);
INSERT INTO Restaurant VALUES(743,'Oh! Calcutta','Next to WD Passport Agency, KL Nagar',19,24);
INSERT INTO Restaurant VALUES(744,'Namma Veedu Vasanta Bhavan','DB Nagar, Near Railway Station',59,10);
INSERT INTO Restaurant VALUES(745,'faasos','Near Symbiosis Ice-Creams',17,14);
INSERT INTO Restaurant VALUES(746,'KFC','KMP Mall',81,30);
INSERT INTO Restaurant VALUES(747,'KFC','KGB Agency Road',22,30);
INSERT INTO Restaurant VALUES(748,'Haldiram','AS Nagar, Vyas Road',56,7);
INSERT INTO Restaurant VALUES(749,'Pizza Hut','Viman Nagar',53,25);
INSERT INTO Restaurant VALUES(750,'Manchester United Bar and Cafe','',44,17);
INSERT INTO Restaurant VALUES(751,'Spices & Sauces','',21,13);
INSERT INTO Restaurant VALUES(752,'Joshi Vade Wala','Next to JK Book Shop, Near Railway Station',43,21);
INSERT INTO Restaurant VALUES(753,'Mad Over Donuts','',41,34);
INSERT INTO Restaurant VALUES(754,'Oh! Calcutta','',83,24);
INSERT INTO Restaurant VALUES(755,'Haldiram','',6,7);
INSERT INTO Restaurant VALUES(756,'Pizza Hut','',97,25);
INSERT INTO Restaurant VALUES(757,'Adyar Ananda Bhavan','',64,3);
INSERT INTO Restaurant VALUES(758,'Manchester United Bar and Cafe','Next to Simlipal Breweries',93,17);
INSERT INTO Restaurant VALUES(759,'Mainland China','Near Modi Bhavan',3,26);
INSERT INTO Restaurant VALUES(760,'faasos','Next to Devi Prasad Chaurasia Memorial',52,14);
INSERT INTO Restaurant VALUES(761,'Post 91 Bar & Restaurants','AD Bhavan, Das Road',30,18);
INSERT INTO Restaurant VALUES(762,'Goli VadaPav','Next to Rayur’s, Yadavendra Complex',23,6);
INSERT INTO Restaurant VALUES(763,'Spices & Sauces','Next to Geetanjali Jewellers',36,13);
INSERT INTO Restaurant VALUES(764,'Post 91 Bar & Restaurants','PAN Card Club',71,18);
INSERT INTO Restaurant VALUES(765,'Murugan Idli Shop','Dorabjee Stores, Oppo. Railway Station',35,9);
INSERT INTO Restaurant VALUES(766,'Bikanervala','Bikanerwala Complex',60,5);
INSERT INTO Restaurant VALUES(767,'Comesum Food','Near Railway Station Bus Stop',39,31);
INSERT INTO Restaurant VALUES(768,'Heart Cup Cafe','Next to HJ Memorial',86,16);
INSERT INTO Restaurant VALUES(769,'Biryani House','Near Eateries Place',100,39);
INSERT INTO Restaurant VALUES(770,'Post 91 Bar & Restaurants','ASB Road',46,18);
INSERT INTO Restaurant VALUES(771,'Saravana Bhavan','Olivander’s Estate',65,11);
INSERT INTO Restaurant VALUES(772,'Annapoorna Gowrishankar','Range Hills Estate',75,2);
INSERT INTO Restaurant VALUES(773,'Sigree','Next to Patil Group Reg. Office',77,23);
INSERT INTO Restaurant VALUES(774,'Moshe','Oppo. Shipping Warehouse',64,8);
INSERT INTO Restaurant VALUES(775,'Manchester United Bar and Cafe','Near HT Biking Arena',1,17);
INSERT INTO Restaurant VALUES(776,'Haldiram','Floor 3, TP Park',84,7);
INSERT INTO Restaurant VALUES(777,'US Pizza','OT Mall and Restaurants',14,32);
INSERT INTO Restaurant VALUES(778,'Residency Clubs','Near PAN Card Club',20,19);
INSERT INTO Restaurant VALUES(779,'Heart Cup Cafe','Near Diamond Bar, FB Road',39,16);
INSERT INTO Restaurant VALUES(780,'Goli VadaPav','Next to PP College of Engineering',19,6);
INSERT INTO Restaurant VALUES(781,'Residency Clubs','Near PEC College of Engineering',40,19);
INSERT INTO Restaurant VALUES(782,'Spices & Sauces','Connaught Place Arena',73,13);
INSERT INTO Restaurant VALUES(783,'Speciality Group of Restaurants','Next to Taj Hotel',85,12);
INSERT INTO Restaurant VALUES(784,'Cafe Coffee Day','Near PES College of Engineering,Commerce',32,28);
INSERT INTO Restaurant VALUES(785,'Biryani House','Andheri Chowk, Next to BP Nagar',86,39);
INSERT INTO Restaurant VALUES(786,'Residency Clubs','Next to GF Stationary Store',30,19);
INSERT INTO Restaurant VALUES(787,'faasos','Shopping Arena near GY Chowk',2,14);
INSERT INTO Restaurant VALUES(788,'Krishna Bhavan','Oppo. BBD College of Engineering',75,20);
INSERT INTO Restaurant VALUES(789,'Manchester United Bar and Cafe','Near Department of Agriculture Building, CD Nagar',81,17);
INSERT INTO Restaurant VALUES(790,'Sigree','Near PY College of Engineering',46,23);
INSERT INTO Restaurant VALUES(791,'Namma Veedu Vasanta Bhavan','Next to EF Plots and Flats Office',41,10);
INSERT INTO Restaurant VALUES(792,'Saravana Bhavan','Next to TUG College of Arts and Commerce',53,11);
INSERT INTO Restaurant VALUES(793,'Wow Momo','Near PEC Commercial Plaza',81,35);
INSERT INTO Restaurant VALUES(794,'Spices & Sauces','Oppo. Bay-Zone',3,13);
INSERT INTO Restaurant VALUES(795,'Manchester United Bar and Cafe','TY Mall Complex',52,17);
INSERT INTO Restaurant VALUES(796,'Annapoorna Gowrishankar','Sohrab Hall, Next to Railway Station',39,2);
INSERT INTO Restaurant VALUES(797,'Residency Clubs','MG Road, FT Shoppers Place',73,19);
INSERT INTO Restaurant VALUES(798,'Joshi Vade Wala','Next to GD Chowk',97,21);
INSERT INTO Restaurant VALUES(799,'Dominoes India Pvt. Ltd.','Next to Avani Industrial Space Ltd. Regd. Office',1,22);
INSERT INTO Restaurant VALUES(800,'Post 91 Bar & Restaurants','Camouflage Shoppers Arena',96,18);
