INSERT INTO RestaurantChain VALUES (0,'None');
INSERT INTO RestaurantChain VALUES (1,'Panjappar Chettinad Restaurant');
INSERT INTO RestaurantChain VALUES (2,'Annapoorna Gowrishankar');
INSERT INTO RestaurantChain VALUES (3,'Adyar Ananda Bhavan');
INSERT INTO RestaurantChain VALUES (4,'Barbeque Nation');
INSERT INTO RestaurantChain VALUES (5,'Bikanervala');
INSERT INTO RestaurantChain VALUES (6,'Goli VadaPav');
INSERT INTO RestaurantChain VALUES (7,'Haldirams');
INSERT INTO RestaurantChain VALUES (8,'Moshes');
INSERT INTO RestaurantChain VALUES (9,'Murugan Idli Shop');
INSERT INTO RestaurantChain VALUES (10,'Namma Veedu Vasanta Bhavan');
INSERT INTO RestaurantChain VALUES (11,'Saravana Bhavan');
INSERT INTO RestaurantChain VALUES (12,'Speciality Group of Restaurants');
INSERT INTO RestaurantChain VALUES (13,'Spices & Sauces');
INSERT INTO RestaurantChain VALUES (14,'faasos');
INSERT INTO RestaurantChain VALUES (15,'Xtreme Sports Bar');
INSERT INTO RestaurantChain VALUES (16,'Heart Cup Cafe');
INSERT INTO RestaurantChain VALUES (17,'Manchester United Bar and Cafe');
INSERT INTO RestaurantChain VALUES (18,'Post 91 Bar');
INSERT INTO RestaurantChain VALUES (19,'Residency Clubs');
INSERT INTO RestaurantChain VALUES (20,'Krishna Bhavan');
INSERT INTO RestaurantChain VALUES (21,'Joshi Vade Wala');
INSERT INTO RestaurantChain VALUES (22,'Dominoes India Pvt. Ltd.');
INSERT INTO RestaurantChain VALUES (23,'Sigree');
INSERT INTO RestaurantChain VALUES (24,'Oh! Calcutta');
INSERT INTO RestaurantChain VALUES (25,'Pizza Hut');
INSERT INTO RestaurantChain VALUES (26,'Mainland China');
INSERT INTO RestaurantChain VALUES (27,'Indian Coffee House');
INSERT INTO RestaurantChain VALUES (28,'Cafe Coffee Day');
INSERT INTO RestaurantChain VALUES (29,'Indian Coffee House');
INSERT INTO RestaurantChain VALUES (30,'KFC');
INSERT INTO RestaurantChain VALUES (31,'Comesum Food');
INSERT INTO RestaurantChain VALUES (32,'US Pizza');
INSERT INTO RestaurantChain VALUES (33,'Papa Johns Pizzas and Beverages');
INSERT INTO RestaurantChain VALUES (34,'Mad Over Donuts');
INSERT INTO RestaurantChain VALUES (35,'Wow Momo');
INSERT INTO RestaurantChain VALUES (36,'Koyla Bar and Restaurants');
INSERT INTO RestaurantChain VALUES (37,'McDonalds');
INSERT INTO RestaurantChain VALUES (38,'South India Foods');
INSERT INTO RestaurantChain VALUES (39,'Biryani House');
INSERT INTO RestaurantChain VALUES (40,'Hyderabad Keema');
INSERT INTO RestaurantChain VALUES (41,'Malaka Spice');
