INSERT INTO Spot VALUES (1, 'Agra Fort', 'SpotAddress', 1);
INSERT INTO Spot VALUES (2, 'Jama Masjid', 'SpotAddress', 1);
INSERT INTO Spot VALUES (3, 'Taj Mahal', 'SpotAddress', 1);
INSERT INTO Spot VALUES (4, 'Chini-Ka-Roza', 'SpotAddress', 1);
INSERT INTO Spot VALUES (5, 'Sabarmati Gandhi Ashram', 'SpotAddress', 2);
INSERT INTO Spot VALUES (6, 'Balvatika', 'SpotAddress', 2);
INSERT INTO Spot VALUES (7, 'Ahmed Shahs Mosque', 'SpotAddress', 2);
INSERT INTO Spot VALUES (8, 'Ajmer-e-Sharif', 'SpotAddress', 3);
INSERT INTO Spot VALUES (9, 'Adhai-din-ka-Jhonpra', 'SpotAddress', 3);
INSERT INTO Spot VALUES (10, 'Circuit House', 'SpotAddress', 3);
INSERT INTO Spot VALUES (11, 'Pathiramanal', 'SpotAddress', 4);
INSERT INTO Spot VALUES (12, 'Krishnapuram Palace', 'SpotAddress', 4);
INSERT INTO Spot VALUES (13, 'Alappuzha Beach', 'SpotAddress', 4);
INSERT INTO Spot VALUES (14, 'Siddheshwar Temple', 'SpotAddress', 5);
INSERT INTO Spot VALUES (15, 'Kolaba Sea Fort', 'SpotAddress', 5);
INSERT INTO Spot VALUES (16, 'Jewish Synagogue', 'SpotAddress', 5);
INSERT INTO Spot VALUES (17, 'Akshaya Vat', 'SpotAddress', 6);
INSERT INTO Spot VALUES (18, 'Sangam', 'SpotAddress', 6);
INSERT INTO Spot VALUES (19, 'Hanuman Mandir', 'SpotAddress', 6);
INSERT INTO Spot VALUES (20, 'Bright end Corner', 'SpotAddress', 7);
INSERT INTO Spot VALUES (21, 'Kalimath', 'SpotAddress', 7);
INSERT INTO Spot VALUES (23, 'Amarnath Yatra', 'SpotAddress', 8);
INSERT INTO Spot VALUES (24, 'Golden Temple', 'SpotAddress', 9);
INSERT INTO Spot VALUES (25, 'Akal Takht', 'SpotAddress', 9);
INSERT INTO Spot VALUES (26, 'Baba Atal Rai Tower', 'SpotAddress', 9);
INSERT INTO Spot VALUES (27, 'Jallianwala Bagh', 'SpotAddress', 9);
INSERT INTO Spot VALUES (28, 'Rambagh Gardens', 'SpotAddress', 9);
INSERT INTO Spot VALUES (29, 'Cellular Jail', 'SpotAddress', 10);
INSERT INTO Spot VALUES (30, 'Chatham', 'SpotAddress', 10);
INSERT INTO Spot VALUES (31, 'Gandhi Park', 'SpotAddress', 10);
INSERT INTO Spot VALUES (32, 'Jolly Buoy and Red Skin Islands', 'SpotAddress', 10);
INSERT INTO Spot VALUES (33, 'Samudrika (Naval Marine Museum)', 'SpotAddress', 10);
INSERT INTO Spot VALUES (34, 'Ross Island', 'SpotAddress', 10);
INSERT INTO Spot VALUES (35, 'Anthropological Museum', 'SpotAddress', 10);
INSERT INTO Spot VALUES (36, 'Khuda Baksh Oriental Library', 'SpotAddress', 11);
INSERT INTO Spot VALUES (37, 'Gol Ghar', 'SpotAddress', 11);
INSERT INTO Spot VALUES (38, 'Patna Museum', 'SpotAddress', 11);
INSERT INTO Spot VALUES (39, 'Kumhrar', 'SpotAddress', 11);
INSERT INTO Spot VALUES (40, 'Marina Park', 'SpotAddress', 11);
INSERT INTO Spot VALUES (41, 'The Hanuman Garhi', 'SpotAddress', 16);
INSERT INTO Spot VALUES (42, 'Treta ke Thakur', 'SpotAddress', 16);
INSERT INTO Spot VALUES (43, 'Ramkot', 'SpotAddress', 16);
INSERT INTO Spot VALUES (44, 'Badami Caves', 'SpotAddress', 17);
INSERT INTO Spot VALUES (45, 'Museum & Art Gallery', 'SpotAddress', 17);
INSERT INTO Spot VALUES (46, 'Badami Fort', 'SpotAddress', 17);
INSERT INTO Spot VALUES (47, 'Bhujakhia Pira', 'SpotAddress', 18);
INSERT INTO Spot VALUES (48, 'Bohera', 'SpotAddress', 19);
INSERT INTO Spot VALUES (49, 'Mysore Maharaja’s Palace', 'SpotAddress', 20);
INSERT INTO Spot VALUES (50, 'Saint Philomenas Church', 'SpotAddress', 20);
INSERT INTO Spot VALUES (51, 'Jayachamarajendra Art Gallery', 'SpotAddress', 20);
INSERT INTO Spot VALUES (52, 'Victoria Memorial', 'SpotAddress', 36);
INSERT INTO Spot VALUES (53, 'Science City', 'SpotAddress', 36);
INSERT INTO Spot VALUES (54, 'Millenium Park', 'SpotAddress', 36);
INSERT INTO Spot VALUES (55, 'Kalighat', 'SpotAddress', 36);
INSERT INTO Spot VALUES (56, 'Dolphin Nose', 'SpotAddress', 12);
INSERT INTO Spot VALUES (57, 'Kailasagiri', 'SpotAddress', 12);
INSERT INTO Spot VALUES (58, 'Vuda Park', 'SpotAddress', 12);
INSERT INTO Spot VALUES (59, 'Rk Beach', 'SpotAddress', 12);
INSERT INTO Spot VALUES (60, 'Ishkon Temples', 'SpotAddress',28 );
INSERT INTO Spot VALUES (61, 'Satsang Mandir', 'SpotAddress', 28);
INSERT INTO Spot VALUES (62, 'Indira Gandhi Park', 'SpotAddress', 28);
INSERT INTO Spot VALUES (63, 'Kashi Vishwanath Mandir', 'SpotAddress', 99);
INSERT INTO Spot VALUES (64, 'River Fronts', 'SpotAddress', 99);
INSERT INTO Spot VALUES (65, 'Jantar Mantar', 'SpotAddress', 81);
INSERT INTO Spot VALUES (66, 'Amber Fort Palace', 'SpotAddress', 81);
INSERT INTO Spot VALUES (67, 'Hawa Mahal', 'SpotAddress', 81);
INSERT INTO Spot VALUES (68, 'Bharat Mata Mandir', 'SpotAddress', 73);
INSERT INTO Spot VALUES (69, 'Maya Devi Temple', 'SpotAddress', 73);
INSERT INTO Spot VALUES (70, 'Chandi Devi', 'SpotAddress', 73);
INSERT INTO Spot VALUES (71, 'Kanyakumari Temple', 'SpotAddress', 94);
INSERT INTO Spot VALUES (72, 'Gandhi Memorial', 'SpotAddress', 94);
INSERT INTO Spot VALUES (73, 'Madhumarai Temple', 'SpotAddress', 43);
INSERT INTO Spot VALUES (74, 'Agricultural University', 'SpotAddress', 43);
INSERT INTO Spot VALUES (75, 'Ranganathar Temple', 'SpotAddress', 43);
INSERT INTO Spot VALUES (76, 'Gwalior Fort', 'SpotAddress', 73);
INSERT INTO Spot VALUES (77, 'Sun Temple', 'SpotAddress', 71);
INSERT INTO Spot VALUES (78, 'Ghaus Mohhamed Temple', 'SpotAddress', 71);
INSERT INTO Spot VALUES (79, 'Sarod Ghar', 'SpotAddress', 71);
INSERT INTO Spot VALUES (80, 'Tansen’s Tomb', 'SpotAddress', 71);
INSERT INTO Spot VALUES (81, 'Tiger Hill', 'SpotAddress', 54);
INSERT INTO Spot VALUES (82, 'Senchal Lake', 'SpotAddress', 54);
INSERT INTO Spot VALUES (83, 'Batasia Loop', 'SpotAddress', 54);
INSERT INTO Spot VALUES (84, 'Observatory Hill', 'SpotAddress', 54);
INSERT INTO Spot VALUES (85, 'Marina Beach', 'SpotAddress', 40);
INSERT INTO Spot VALUES (86, 'Anna Salai', 'SpotAddress', 40);
INSERT INTO Spot VALUES (87, 'Egmore Street', 'SpotAddress', 40);
INSERT INTO Spot VALUES (88, 'St.s Marys Church', 'SpotAddress', 40);
INSERT INTO Spot VALUES (89, 'George Town', 'SpotAddress', 40);
INSERT INTO Spot VALUES (90, 'Jain Glass Temple', 'SpotAddress', 93);
INSERT INTO Spot VALUES (91, 'Kamla Retreat', 'SpotAddress', 93);
INSERT INTO Spot VALUES (92, 'Shri Radhakrishna Temple', 'SpotAddress', 93);
INSERT INTO Spot VALUES (93, 'Allen Forrest Zoo', 'SpotAddress', 93);
INSERT INTO Spot VALUES (94, 'Phool Bagh', 'SpotAddress', 93);
INSERT INTO Spot VALUES (95, 'Marine Drive', 'SpotAddress', 46);
INSERT INTO Spot VALUES (96, 'Gundu Islands', 'SpotAddress', 46);
INSERT INTO Spot VALUES (97, 'Cochin Port Cruise', 'SpotAddress', 46);
INSERT INTO Spot VALUES (98, 'Mysore Zoo', 'SpotAddress', 20);
INSERT INTO Spot VALUES (99, 'Folklore Museum', 'SpotAddress', 20);
INSERT INTO Spot VALUES (100, 'Mysore Maharaja’s Palace', 'SpotAddress', 20);
